### ISSUE TITLE
15.0 release

### ISSUE THREAD

**Issue by pomazanbohdan** [docker-library/postgres#1005]
Hello. I would like to see the release build of docker)

**Comment by emansom** [comment]
Built image [`ewout/postgres:15.0`](https://hub.docker.com/r/ewout/postgres/tags) for the impatient.

Official CI should kick in within 24h.

**Comment by tianon** [comment]
I was trying to get it updated all day yesterday but the APT repos had a slight delay in getting the update. :sweat_smile:

https://github.com/docker-library/official-images/pull/13339 is open now :+1:
