### ISSUE TITLE
upgrade issues from 14 to 15 in a docker

### ISSUE THREAD

**Issue by poudenes** [docker-library/postgres#1007]
Hi All,

Last night watchover upgraded my docker image for postgres (now add label for not doing it anymore, only manual)
After the upgrade postgres was not able to start because the databases created in 14 and are not compatible with 15.

Only solution for me was to revert back to 14 and add the :14 label to the image.

How can I upgrade the docker to latest postgres version? Because I was not able to go into the docker so I was able to had the command line. The postgres docker stopped all the time.

**Comment by emansom** [comment]
Export the version 14 database to serialized SQL using `pg_dumpall`, then import the serialized SQL on the version 15 database.

[Here](https://hollo.me/devops/upgrade-postgresql-database-with-docker.html) is an example of the process.

**Comment by poudenes** [comment]
This solved the issue
