### ISSUE TITLE
WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted

### ISSUE THREAD

**Issue by pedz** [docker-library/postgres#1015]
There are at least three instances of this problem coming up:
- [forums.docker.com](https://forums.docker.com/t/could-not-open-statistics-file-pg-stat-tmp-global-stat-operation-not-permitted-with-postgres/118123?u=pedzsan)
- [Stack Exchange 1](https://stackoverflow.com/q/66325175/341980)
- [Stack Exchange 2](https://stackoverflow.com/q/30846804/341980)

What I found can be seen [here](https://stackoverflow.com/a/73656250/341980)

In brief, somehow files inside the container are being owned by root.  While attached to the db container, I see this:
```
root@ec24992481d1:~# find /var/lib/postgresql -user 0 -exec ls -ld {} +
-rw------- 1 root root    8 Sep  9 00:34 /var/lib/postgresql/data/pg_logical/replorigin_checkpoint
-rw------- 1 root root 2225 Sep  9 01:17 /var/lib/postgresql/data/pg_stat_tmp/db_0.stat
-rw------- 1 root root 6665 Sep  9 01:17 /var/lib/postgresql/data/pg_stat_tmp/db_13757.stat
-rw------- 1 root root 7035 Sep  9 01:17 /var/lib/postgresql/data/pg_stat_tmp/db_16384.stat
-rw------- 1 root root   94 Sep  9 00:29 /var/lib/postgresql/data/postmaster.pid
```
I have done `chown -R postgres:postgres /var/lib/postgresql` but later the Warnings start up again and when I attach to the db container, I see that more files are owned by root.

I'm assuming that this is not suppose to happen and also assuming that this is part of the problem.  I tried adding `ps` to the container but I still can't see the processes started by docker compose.

**Comment by DCCInterstellar** [comment]
As of June 19, 2023. I'm having this exact issue on an Unraid Server. Does anyone have any information on how to fix this?

   
![Capture](https://github.com/docker-library/postgres/assets/124222270/0ee4f797-d692-4d86-8aee-5a5f1893ff68)

**Comment by tianon** [comment]
@DCCInterstellar I think you're actually hitting #1100 (you likely need to update libseccomp2 on your host)

**Comment by DCCInterstellar** [comment]
@tianon Thank you! I changed the repository from `postgres:14` to `postgres:14-bullseye` and I no longer get the Permission denied error!

**Comment by tianon** [comment]
> My guess is that this has something to do with the filesystem sharing implementation in Docker Desktop -- beyond that, I'm at a loss for helping debug (as this doesn't seem to be something particular to PostgreSQL but rather to the environment in which it's running or storing data).

This is still my best guess -- can anyone who is suffering from this reproduce with a named volume or without using Docker Desktop / VM shared filesystems?

**Comment by pedz** [comment]
> > My guess is that this has something to do with the filesystem sharing implementation in Docker Desktop -- beyond that, I'm at a loss for helping debug (as this doesn't seem to be something particular to PostgreSQL but rather to the environment in which it's running or storing data).
> 
> This is still my best guess -- can anyone who is suffering from this reproduce with a named volume or without using Docker Desktop / VM shared filesystems?

I switched to using an external volume in my compose file and I've not seen the problem since.  I agree that this doesn't seem to be Postgres specific but it seems to be the only one getting hit by whatever the bug is.

I'm fine with closing this.

**Comment by DCCInterstellar** [comment]
I know this is marked as closed but I wanted to share something I found another way to fix this issue. In your docker-compose file or .env file, you will need to add the PUID and PGID variable to it:

`PUID='0'`
 `PGID='0'`

For example, the 0 is representing in my instance as the root user. Now the root user for the docker container can read,  write, and execute any of those files in the appdata without any issues. 
So far I haven't the errors regarding `could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted`
