### ISSUE TITLE
Unsafe use of echo (may set empty password)

### ISSUE THREAD

**Issue by maffe** [docker-library/postgres#1023]
https://github.com/docker-library/postgres/blob/f8827c3ce62f7a2f560db2b3b1c566965a7ec5c1/15/alpine/docker-entrypoint.sh#L91

If `$POSTGRES_PASSWORD` matches the regular expression `^-[neE]+$`, the password will be set to an empty string because `echo` will interpret it as options. (Different shells allow different options for `echo`, scripts using `echo` with unknown/variable arguments are therefore not portable.)

`printf %s "$POSTGRES_PASSWORD"` should be used instead.

**Comment by maffe** [comment]
I’m not sure if it’s possible to authenticate using an empty password, but using the _correct_ password will not work.

**Comment by tianon** [comment]
Nice!  I don't think a password that starts with `-` and consists of nothing but some combination of `n`, `e`, and `E` is a particularly _good_ idea, but the correct fix here is pretty simple. :sweat_smile:
