### ISSUE TITLE
PG 15: Zstd compression

### ISSUE THREAD

**Issue by JordanP** [docker-library/postgres#1030]
I am trying to experiment with the new Zstd compression algo added in PG 15. It seems this [commit](https://github.com/docker-library/postgres/commit/7b8a5db5524e962cdcc02230f04c36d77d45441d) added support for this in the Dockerfile though I can't make it work:

![image](https://user-images.githubusercontent.com/221981/211018826-361148e3-bbcd-490d-a241-731e73187b74.png)

What am I missing ?

cc @ImreSamu @tianon

**Comment by ImreSamu** [comment]
> What am I missing ?

* no zstd support for the `default_toast_compression` 
   * https://www.postgresql.org/docs/15/runtime-config-client.html#GUC-DEFAULT-TOAST-COMPRESSION
* So you can experiment only with the `wal_compression`
   * https://www.postgresql.org/docs/15/runtime-config-wal.html#GUC-WAL-COMPRESSION

**Comment by JordanP** [comment]
Ah ! Thanks for pointing this out. I feel stupid now. Thanks again :)
