### ISSUE TITLE
Postgres 11.18 for Debian 10 or 9

### ISSUE THREAD

**Issue by cesarjorgemartinez** [docker-library/postgres#1033]
Hi

I see that PG 11.18 only has Debian 11 bullseye.
I need to upgrade from 11.14 to 11.18 but some plugins not exist for bullseye, exist for debian 9 or 10, example timescaledb.
You can provide for these OS?
Because then force upgrade to major version.

Regards

**Comment by cesarjorgemartinez** [comment]
Thanks, I can create a pull request to this repo to do myself the version?

**Comment by tianon** [comment]
No, I mean you can maintain it separately for yourself -- we have no plans
to maintain it.
