### ISSUE TITLE
Help understanding the sizes

### ISSUE THREAD

**Issue by flixman** [docker-library/postgres#1036]
Per hub.docker.com, postgres:15-alpine, 69bd7cc493f8 digest for amd/64, is 89.3 MB. However, should I pull that specific digest, I get an image that is 243 MB (~3x the claimed size). Am I reading wrong the sizes, or there is an inconsistency somewhere?

**Comment by wglambert** [comment]
On the hub it notes that is the "compressed size: This size is calculated by summing the image's layers, which are compressed."

**Comment by flixman** [comment]
@wglambert: I am an idiot, and is late. Thank you!
