### ISSUE TITLE
Database Replication - Standby server

### ISSUE THREAD

**Issue by phlegx** [docker-library/postgres#104]
Hello!

I wanted to ask if it is possible to run postgres as master slave somehow out of the box, or if this is planned to make this work via docker? 

As I didn't find such an option here in the HOWTOS it is probably not yet possible. 

thanks
p

**Comment by tianon** [comment]
The Postgres replication is a little bit complex, but this is definitely doable.  I went through some of https://www.digitalocean.com/community/tutorials/how-to-set-up-master-slave-replication-on-postgresql-on-an-ubuntu-12-04-vps to get something going and it's not too bad.  The user created by our entrypoint script is a `SUPERUSER`, so it does have permission to replicate by default, so I think the most difficult parts here are setting the config (`wal_level`, etc) and doing the initial replication.

**Comment by tianon** [comment]
See also https://github.com/docker-library/postgres/issues/55 and https://github.com/docker-library/postgres/issues/88. :+1:
