### ISSUE TITLE
Add pgAudit

### ISSUE THREAD

**Issue by bryopsida** [docker-library/postgres#1048]
If acceptable, I'd like to submit a PR to add pgAudit so it can be enabled via `CREATE EXTENSION` like many other extensions.  Is this something that would be desired/accepted assuming all requirements are met in the PR?

**Comment by tianon** [comment]
We strive to stay as close to an upstream PostgreSQL distribution as possible, so given this isn't something distributed by them (_and_ that it's not too hard to build/install afterwards, as I understand it), this unfortunately wouldn't be something we would want to include and maintain in the images we publish.
