### ISSUE TITLE
[alpine] `apk add repmgr` will install another copy of postgresql

### ISSUE THREAD

**Issue by coinicon72** [docker-library/postgres#1051]
My target is to deploy a postgresql HA cluster in docker, following is my steps: 

1. ran a `postgres:15.2-alpine` container which will be the primary server, no problem. However, I noticed `apk list -I` not list `postgres` as installed package;
2. install `repmgr` in this container by run `apk add repmgr` command, installation seems ok, but logs said: 
```
/ # apk add repmgr
(1/9) Installing openssh-keygen (9.1_p1-r2)
(2/9) Installing openssh-client-common (9.1_p1-r2)
(3/9) Installing openssh-client-default (9.1_p1-r2)
(4/9) Installing doas (6.8.2-r3)
Executing doas-6.8.2-r3.post-install
(5/9) Installing postgresql-common (1.1-r3)
Executing postgresql-common-1.1-r3.pre-install
(6/9) Installing libpq (15.2-r0)
(7/9) Installing postgresql15-client (15.2-r0)
(8/9) Installing postgresql15 (15.2-r0)
Executing postgresql15-15.2-r0.post-install
*
* If you want to use JIT in PostgreSQL, install postgresql15-jit or
* postgresql-jit (if you didn't install specific major version of postgresql).
*
(9/9) Installing repmgr (5.3.3-r1)
Executing busybox-1.35.0-r29.trigger
Executing postgresql-common-1.1-r3.trigger
* Setting postgresql15 as the default version
pg_versions: WARN: /etc/postgresql exists and it's not a symlink!
OK: 204 MiB in 56 packages
``` 
as you can see, `apk add repmgr` installed another copy of postgresql, this lead to two issues:
1. `repmgr` only install extension in new instance, and repmgr can't work with exist postgres which has no repmgr extension;
2. more disk usage;

Could you please try some thing to make `apk` aware postgres was installed?

I'm not good at linux/alpine, sorry for that.

Thanks a lot!

**Comment by tianon** [comment]
I don't think there's a way for us to do that, but if there is an unobtrusive (esp. simple to maintain) way to block `apk` from installing PostgreSQL again, we'd be open to considering it.

**Comment by coinicon72** [comment]
Ok, I understood.

Thanks again.
