### ISSUE TITLE
Issue with missing folders

### ISSUE THREAD

**Issue by jakeleventhal** [docker-library/postgres#1053]
If you try to save a volume of a database like so:
`-v $(pwd)/localDBData:/var/lib/postgresql/data`
then it will create a directory that mirrors the DB on the host machine.

If i track this `localDBData` folder in git, then clone the repo, empty folders will not be included.

As mentioned in this stack exchange link, the following empty folders are required to exist, or an error is thrown.
https://dba.stackexchange.com/questions/17481/recover-from-postgres-fatal-could-not-open-file-pg-tblspc

Running the following makes the volume work again:
```bashmkdir localDBData/pg_notify/
mkdir localDBData/pg_replslot/
mkdir localDBData/pg_tblspc/
mkdir localDBData/pg_twophase/
mkdir localDBData/pg_snapshots/
mkdir localDBData/pg_logical/snapshots/
mkdir localDBData/pg_logical/mappings/
mkdir localDBData/pg_commit_ts/
```
But this solution is kind of janky. These folders should be automatically created if they do not exist.

**Comment by jakeleventhal** [comment]
I tried to remedy this by putting a `.gitkeep` in each of these folders, but then it complains about that file in pg_tblspc

Either way, i think these folders ought to just get created if they do not exist rather than throwing an error since the folders are empty anyway in many cases.

**Comment by yosifkit** [comment]
Unfortunately that is how PostgreSQL works, we don't want to maintain scripts that reach into PostgreSQL's data directories and files doing things that were already done via `initdb` or by `postgres` itself.

See also https://stackoverflow.com/questions/70464894/postgres-empty-directories-and-github
