### ISSUE TITLE
How can I override the postgresql.conf ?

### ISSUE THREAD

**Issue by ghevge** [docker-library/postgres#1060]
How can I override the postgresql.conf ?
In my Dockerfile I've tried the following:

```
COPY ./postgresql.conf /usr/local/share/postgresql/postgresql.conf
COPY ./postgresql.conf /etc/postgresql.conf
COPY ./postgresql.conf /etc/postgresql/postgresql.conf
COPY ./postgresql.conf /var/lib/postgresql/data/postgresql.conf
RUN echo 'tes = test' >> /var/lib/postgresql/data/postgresql.conf
```

Non of these approaches is changing the default configurations

I'm playing with postgres:15-alpine image.

Thanks

**Comment by yosifkit** [comment]
`/var/lib/postgresql/data/` is a volume, so nothing can be saved there during image build, but that is the location for the config file generated by PostgreSQL's `initdb` and is used by default. It is generated from the `/usr/local/share/postgresql/postgresql.conf.sample` file (which we [adjust](https://github.com/docker-library/postgres/blob/156d0659d047578f06aa8785cf12d547c6a5ccfd/Dockerfile-debian.template#L176) for the [images](https://github.com/docker-library/postgres/blob/156d0659d047578f06aa8785cf12d547c6a5ccfd/Dockerfile-alpine.template#L161)). You can replace that `.sample` and your custom config "sample" would be used to generate the `.conf` at first runtime. Or you can provide a full `.conf` anywhere (readable by `postgres` user) in the image and add `-c 'config_file=/etc/postgresql/postgresql.conf'` to a custom `CMD`

https://github.com/docker-library/docs/tree/df0fd9b92ebfaf3fee80c2319d4bea7455641216/postgres#database-configuration

```Dockerfile
# untested, but this *should* work
FROM postgres:15-alpine
COPY --chown postgres:postgres ./postgresql.conf /etc/postgresql.conf
CMD [ "-c", "config_file=/etc/postgresql/postgresql.conf" ]
```

**Comment by ghevge** [comment]
Thanks for clarifying this!

**Comment by mdluo** [comment]
> `/var/lib/postgresql/data/` is a volume, so nothing can be saved there during image build, but that is the location for the config file generated by PostgreSQL's `initdb` and is used by default. It is generated from the `/usr/local/share/postgresql/postgresql.conf.sample` file (which we [adjust](https://github.com/docker-library/postgres/blob/156d0659d047578f06aa8785cf12d547c6a5ccfd/Dockerfile-debian.template#L176) for the [images](https://github.com/docker-library/postgres/blob/156d0659d047578f06aa8785cf12d547c6a5ccfd/Dockerfile-alpine.template#L161)). You can replace that `.sample` and your custom config "sample" would be used to generate the `.conf` at first runtime. Or you can provide a full `.conf` anywhere (readable by `postgres` user) in the image and add `-c 'config_file=/etc/postgresql/postgresql.conf'` to a custom `CMD`
> 
> https://github.com/docker-library/docs/tree/df0fd9b92ebfaf3fee80c2319d4bea7455641216/postgres#database-configuration
> 
> ```dockerfile
> # untested, but this *should* work
> FROM postgres:15-alpine
> COPY --chown postgres:postgres ./postgresql.conf /etc/postgresql.conf
> CMD [ "-c", "config_file=/etc/postgresql/postgresql.conf" ]
> ```

Minor correction:

```dockerfile
COPY --chown=postgres:postgres ./postgresql.conf /etc/postgresql.conf
CMD [ "-c", "config_file=/etc/postgresql.conf" ]
```
