### ISSUE TITLE
Unable to run postgres command in container

### ISSUE THREAD

**Issue by kunalmamodiya** [docker-library/postgres#1064]
Getting this error while running "postgres -version" command.

"root" execution of the PostgreSQL server is not permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromise.  See the documentation for
more information on how to properly start the server.

**Comment by tianon** [comment]
I think you need another `-`:

```console
$ docker run --rm --pull=always postgres postgres --version
latest: Pulling from library/postgres
Digest: sha256:5a90725b3751c2c7ac311c9384dfc1a8f6e41823e341fb1dceed96a11677303a
Status: Image is up to date for postgres:latest
postgres (PostgreSQL) 15.2 (Debian 15.2-1.pgdg110+1)
```
