### ISSUE TITLE
plperl is not in version 15

### ISSUE THREAD

**Issue by manicar2093** [docker-library/postgres#1066]
Hi!

I'm trying to set a posrgres docker image to use plpearl but it seems this extension does not exists now. I found this [PR](https://github.com/docker-library/postgres/pull/115) where plpearl was added in version 9.

The question is: Is there a way to install this extension in a running container?

Thanks!

**Comment by ImreSamu** [comment]
>The question is: Is there a way to install this extension in a running container?

imho: the recommended way: extending the image
example Dockerfile:

```Dockerfile
FROM postgres:15-bullseye
RUN apt-get update \
      && apt-get install -y --no-install-recommends  \
         postgresql-plperl-15 \
      && rm -rf /var/lib/apt/lists/*
```

see: https://github.com/docker-library/docs/tree/master/postgres#additional-extensions

**Comment by manicar2093** [comment]
@ImreSamu Thanks! That's what I did and it works!
