### ISSUE TITLE
Makes GID, UID and user as variables

### ISSUE THREAD

**Issue by spassignat** [docker-library/postgres#1068]
Hello,

the fixed values 999 for GID and UID and the user name postgres, are not always convenient when using docker-compose with several applications sharing the same host folder for their volumes.

Is it possible to make them variables ? defaulting their values ?

thanks

**Comment by yosifkit** [comment]
Just set `--user`/`user:` to whatever uid/gid that you desire and provide a directory owned by that user for the volume (`/var/lib/postgresql/data`). No variable is necessary, the images are designed to run as any arbitrary user.

https://github.com/docker-library/docs/tree/c235cf87aee09b932b83b6486010571752e80ec1/postgres#arbitrary---user-notes
