### ISSUE TITLE
Container fails to start

### ISSUE THREAD

**Issue by paoloromagnoli** [docker-library/postgres#108]
Just tried to start a new container using: 

docker run --name my-postgres -e POSTGRES_PASSWORD=mypassword -d postgres

and I got the follwoing error:

7c0ffee09adcf2692ed62b4a65d1375a5559d3bd9f0e2c5b86e3eab577b52149
Error response from daemon: Cannot start container 7c0ffee09adcf2692ed62b4a65d1375a5559d3bd9f0e2c5b86e3eab577b52149: failed to update store for object type *libnetwork.endpointCnt: Key not found in store

The problem only appears when I make the Docker daemon only accept connections from clients providing a certificate (tlsverify, tlscacert).

Can you help me with this? 

Here is my docker info:

Containers: 9
Images: 40
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-68173687-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 787.2 MB
 Data Space Total: 107.4 GB
 Data Space Available: 18.55 GB
 Metadata Space Used: 2.019 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.3.1.el7.x86_64
Operating System: Red Hat Enterprise Linux
CPUs: 1
Total Memory: 1.797 GiB
Name: localhost.localdomain
ID: GYN3:CI6A:JN5S:VRUZ:FNB4:2USC:PROE:OTOS:E3C7:G4RE:MAT2:O37J
Username: paoloromagnoli
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by xied75** [comment]
@paoloromagnoli do a simple google search would bring you to this:
https://github.com/docker/compose/issues/2356
According to the guys there it is docker engine's problem, by any means it is very unlikely has anything to do with postgres.

**Comment by paoloromagnoli** [comment]
I went through https://github.com/docker/compose/issues/2356, however it does not help at all. I agree with you, this is issue is definitively not related to postgres so I am posting in the wrong library.

By the way, I was able to workaround this by disabling tslverify, however this causes security issue.
