### ISSUE TITLE
Postgres:12 container is not starting anymore

### ISSUE THREAD

**Issue by daheile** [docker-library/postgres#1103]
Hello,

Since around 1 week, postgres container with tag 12 is not starting anymore.
It fails with
```10:48:57.385 [main] ERROR tc.postgres:12 - Log output from the failed container:
popen failure: Cannot allocate memory
initdb: error: The program "postgres" is needed by initdb but was not found in the
same directory as "/usr/lib/postgresql/12/bin/initdb".
Check your installation.
```
This was working before.

Workaround: All ok using postgres container with tag "12-bullseye".

What has changed?

**Comment by yosifkit** [comment]
The change was adding Debian Bookworm based images as the default. The `postgres:*bullseye` images will continue to be maintained/updated until the respective PostgreSQL end of life or the next Debian release, Debian Trixie.

Likely the same issue as https://github.com/docker-library/postgres/issues/1100.  So, https://github.com/docker-library/postgres/issues/1100#issuecomment-1599660628.

**Comment by wey-gu** [comment]
for those who reached out here, in compose, add this to the service

```yaml
    security_opt:
      - seccomp=unconfined
```
