### ISSUE TITLE
"docker-entrypoint.sh": executable file not found in $PATH: unknown.

### ISSUE THREAD

**Issue by Udayendu** [docker-library/postgres#1111]
### Issue:
  - Currently the Dockerfile is not having the executable permission before marking the ENTRYPOINT with `docker-entrypoint.sh` script. As a result, the docker build is failing with the following error message:
  
    ```
    docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown.
    ```

### How to fix
- Either provide the executable permission  to `docker-entrypoint.sh` manually before running the Dockerfile to build the container image.
- Or run the below command in the Dockerfile after doing the script copy as mentioned in https://github.com/docker-library/postgres/blob/master/15/alpine3.18/Dockerfile#L176C6-L176C42:
    ```
    RUN chmod +x  /usr/local/bin/docker-entrypoint.sh
    ```

Having the fix in the Dockerfile will be a better option so that if some one will do the copy paste of the docker file, still its going to work.

**Comment by yosifkit** [comment]
https://github.com/docker-library/postgres/pull/912#issuecomment-982962087

**Comment by Udayendu** [comment]
@yosifkit if the fix is already there, are you going to backport it ? Usually `chmod 777` is not needed. `Chmod 755` is also working.

**Comment by tianon** [comment]
Our stance is generally that if you want to build our images from source, you either need to use `git clone` to fetch them (which thus gets the appropriate permissions bits on `docker-entrypoint.sh`) or replicate what `git clone` would do yourself.
