### ISSUE TITLE
Check exit statuses of scripts in /docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by orzeh** [docker-library/postgres#112]
I would be nice to have detected non-zero statuses of scripts and executed sql files in `docker-entrypoint.sh`.
First non-zero exit status should stop container setup avoiding possibly inconsistent database state.

WDYT?

Eventually I can make PR with this.

**Comment by yosifkit** [comment]
As far as the shell scripts, those will automatically fail on any line with a simple command that has a non-zero status, since they inherit the `set -e` of the entrypoint, because they are sourced to give them access to the local variables, rather than run in another shell.  For sql scripts, it looks like it might fail to fail with the `&&`, since that makes it no longer a "simple command" ([see `set -e` docs](http://pubs.opengroup.org/onlinepubs/009696799/utilities/set.html)).

**Comment by orzeh** [comment]
Oh, I've missed the `set -e` at the beginning.
So to break on SQL script error the `for` loop can be just slightly modified, as below:

````bash
for f in /docker-entrypoint-initdb.d/*; do
    case "$f" in
        *.sh)  echo "$0: running $f"; . "$f" ;;
        *.sql) 
            echo "$0: running $f" 
            psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" < "$f"
            echo 
            ;;
        *)     echo "$0: ignoring $f" ;;
    esac
    echo
done
```` 

Then `-v ON_ERROR_STOP=1` is needed to `psql` return non-zero exit code (see [docs](http://www.postgresql.org/docs/current/static/app-psql.html#AEN94748)).

**Comment by yosifkit** [comment]
:+1: Seems solid to me!  Thanks for working on this.  Please make sure to follow the indentation of the file, which is tabs :wink:.

**Comment by orzeh** [comment]
Ok, I`ll make PR tomorrow.

**Comment by syntropo** [comment]
Any way to make this new behavior optional? It was actually helpful in my case to ignore errors encountered when running sql files on startup.

**Comment by orzeh** [comment]
Of course it can be parametrized by introducing for example `IGNORE_SQL_ERRORS` flag or so.

In your particular case you can run SQL scripts from `*.sh` files like shown in the [docs](https://hub.docker.com/_/postgres/):

>For example, to add an additional user and database, add the following to /docker-entrypoint-initdb.d/init-user-db.sh:
>
> ````
> #!/bin/bash
> set -e
>
> psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
>    CREATE USER docker;
>    CREATE DATABASE docker;
>    GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
> EOSQL
> ````

but remove the `-v ON_ERROR_STOP=1` switch.
