### ISSUE TITLE
11.21 tag missing and 11 tag points at obsolete version

### ISSUE THREAD

**Issue by NeilW** [docker-library/postgres#1121]
```
$ docker pull postgres:11.21
Error response from daemon: manifest for postgres:11.21 not found: manifest unknown: manifest unknown
```

```
$ docker pull postgres:11
11: Pulling from library/postgres
Digest: sha256:5d2aa4a7b5f9bdadeddcf87cf7f90a176737a02a30d917de4ab2e6a329bd2d45
Status: Downloaded newer image for postgres:11
docker.io/library/postgres:11
```

which is a version using Debian stretch.

**Comment by LaurentGoderre** [comment]
https://github.com/docker-library/postgres/pull/1129 fixes this.

**Comment by LaurentGoderre** [comment]
Looks like this was on purpose to avoid breaking indexes between stretch and other debian versions.

**Comment by LaurentGoderre** [comment]
Here is the rationale. https://github.com/docker-library/postgres/issues/582#issuecomment-862746990

Closing as upgrading has to be a deliberate step.
