### ISSUE TITLE
pg_dump, pg_restore utilities thorwing an error libzstd.so.1 and liblz4.so.1 file not found.

### ISSUE THREAD

**Issue by akshay-joshi** [docker-library/postgres#1130]
pg_dump/pg_restore and other utilities throwing an error libzstd.so.1 and liblz4.so.1 file not found.

**Steps to reproduce:**

- Pull the latest postgres or postgres:16-alpine image.
- Start the container and run pg_dump or pg_restore.

![Docker_Error](https://github.com/docker-library/postgres/assets/1632882/36c09392-d6f3-4518-8c4c-1449d65081e1)

**Comment by ImreSamu** [comment]
> Steps to reproduce:

It is working for me:

```
$ docker run  -it --rm   postgres:16 bash -c  "pg_dump --version && pg_restore --version"
pg_dump (PostgreSQL) 16.0 (Debian 16.0-1.pgdg120+1)
pg_restore (PostgreSQL) 16.0 (Debian 16.0-1.pgdg120+1)

$ docker run  -it --rm   postgres:16-alpine bash -c  "pg_dump --version && pg_restore --version"
pg_dump (PostgreSQL) 16.0
pg_restore (PostgreSQL) 16.0
```

**Comment by akshay-joshi** [comment]
My bad, I think I am using an alpine image and forgot to copy the dependencies. 
Sorry for the noise. Closing the issue.
