### ISSUE TITLE
Update offical docker images to add new postgres 15.5 version

### ISSUE THREAD

**Issue by NilsEngelbach** [docker-library/postgres#1142]
Hello togehter,

Thanks for maintaining the offical postgres image.

I am not sure how the general release process of the offical postgres docker image works, but i guess the this file:
`https://github.com/docker-library/official-images/blob/master/library/postgres`
has to be udpated, to make the image offically available.

Are there further checks pending, before it is added?

Thanks in advance!

**Comment by LaurentGoderre** [comment]
It was updated as per this commit (https://github.com/docker-library/postgres/commit/da624f9e2e26fd185c73532ec52203aa3683f4db) But it still needs to be update the the library repo.

**Comment by LaurentGoderre** [comment]
https://github.com/docker-library/official-images/pull/15699
