### ISSUE TITLE
Image without VOLUME

### ISSUE THREAD

**Issue by gotcha** [docker-library/postgres#117]
We have the following use case: we want to build an image with postgres AND a dataset. 
This image is used by tests that, among others, update the data. By having the data inside the image, we ensure that changes remain confined in the container and that each test run in a new container can count on the same set of data.

Not having UNVOLUME or similar implies that we cannot use the current postgres official image as base image since it declares a volume.

Already mentioned in https://github.com/docker/docker/pull/8177#issuecomment-119595202

**Comment by xied75** [comment]
@gotcha It's not how docker VOLUME actually works, as long as you don't map the volume to your host, docker engine will create a NEW folder to hold your volume files EVERY time you run the image, under /var/lib/docker/volumes, why don't you try to run postgres twice and see what happens? You are not going to get your data again and again.

**Comment by gotcha** [comment]
@xied75 Because we want to include data in the image, we do not want docker to create a directory.

**Comment by tianon** [comment]
Wouldn't setting a custom value for PGDATA in your Dockerfile be a
functional workaround here?

**Comment by coding2012** [comment]
tianon - thanks for the suggestion, that will work for my use case at least :)

**Comment by zouyue735** [comment]
Thought my situation is related to this issue.

I'm using a custom postgres 9.5 image, which is just the official postgres image with the volume line commented out. Data is stored inside by docker commit.

I started my application with docker-compose up -d. But sometimes docker-compose down reports time out when stopping the postgres container. And after that, no matter I do docker stop or docker kill won't stop the container, it just hanged there forever.

I'm using docker version 1.10.1, docker compose version 1.6.0, and a quite recent version of the offical postgres Dockerfile.

**Comment by kotofos** [comment]
Hi, I suggest another workaround - use multistage build
```
FROM postgres as build
FROM alpine:3.8 as postgres
COPY --from=build / /
ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 5432
CMD ["postgres"]
```
