### ISSUE TITLE
include_dirs env var

### ISSUE THREAD

**Issue by arist0v** [docker-library/postgres#1238]
since it is usefull to be able to edit the .conf, it would be nice to have a env var for the include dir so we can specify a path to load more custom .conf file, 

to achieve this i had to create a new entrypoint script, call the original one, kill postgres, edit the .conf to include my dir then restart it.

**Comment by tianon** [comment]
See https://github.com/docker-library/postgres/issues/835#issuecomment-857282516

**Comment by arist0v** [comment]
sorry the search didn'T show anything!!!

**Comment by tianon** [comment]
Same - turns out `include_dirs` is a typo; the actual option is `include_dir` :smile:

**Comment by arist0v** [comment]
> Same - turns out `include_dirs` is a typo; the actual option is `include_dir` 😄

with all the AI now they can'T fix this ;-) thank you
