### ISSUE TITLE
Version '9.4.5-2.pgdg80+1' for 'postgresql-9.4' was not found

### ISSUE THREAD

**Issue by Prudwell** [docker-library/postgres#124]
I think this is same as [this issue](https://github.com/docker-library/postgres/issues/95) from Oct. Creating the 9.4 docker build fails with this error. New pg version in the debian repo [here](http://apt.postgresql.org/pub/repos/apt/pool/9.4/p/postgresql-9.4/)?

After updating the PG_VERSION to 9.4.6-1.pgdg80+1 the build worked. This might need to be changed for all of the major version dockerfiles?

**Comment by yosifkit** [comment]
Yup, there is a PR for it: https://github.com/docker-library/postgres/pull/123.  Thanks!

**Comment by Prudwell** [comment]
Ah didn't look in pull requests sorry. Looks like it's updated to the new version now.
