### ISSUE TITLE
please add a Container shell access and viewing MySQL logs directly

### ISSUE THREAD

**Issue by deepakbhargav78** [docker-library/postgres#1257]

**Comment by deepakbhargav78** [comment]
postgress

**Comment by deepakbhargav78** [comment]
solve as soon as possible

**Comment by tianon** [comment]
This is the repository for the PostgreSQL official image, which has nothing to do with MySQL.  If you need help with your deployment, I would suggest finding a suitable support forum or paying a professional consultant.
