### ISSUE TITLE
Security issues in latest postgres image

### ISSUE THREAD

**Issue by vr2388** [docker-library/postgres#1266]
When we scan the postgres latest image we found **critical and HIGH** security issues in those images.
Attaching the latest image security issue report.
```
postgres:latest (debian 12.6)
=============================
Total: 145 (UNKNOWN: 0, LOW: 101, MEDIUM: 32, HIGH: 11, CRITICAL: 1)
```
And we found more critical issue in **gosu** library
```
usr/local/bin/gosu (gobinary)
=============================
Total: 52 (UNKNOWN: 0, LOW: 1, MEDIUM: 18, HIGH: 30, CRITICAL: 3)

```

We also found same report in dockerhub as well
<img width="1222" alt="image" src="https://github.com/user-attachments/assets/168e3008-99db-41ac-90c1-693691ad11b5">
<img width="1133" alt="image" src="https://github.com/user-attachments/assets/ae817de3-d2b2-4940-86dd-c9d9d36ffb05">

**Comment by tianon** [comment]
See also https://github.com/tianon/gosu/blob/master/SECURITY.md
