### ISSUE TITLE
Missing v17 images for arm64, arm/v7, and arm/v5

### ISSUE THREAD

**Issue by devlux** [docker-library/postgres#1272]
The images for arm64, arm/v7, and linux/arm/v5 are currently missing in the docker registry for the v17.

![image](https://github.com/user-attachments/assets/e9674c97-d8e8-41be-bd3a-dbfa5c34026e)

Also some tags now include a mix of v16 and v17 images, e.g. alpine, latest, etc.

**Comment by simschla** [comment]
same for 17.0-bullseye:
![image](https://github.com/user-attachments/assets/25d267c6-b645-4ace-afd8-6e8147ab5b64)

**Comment by yrashk** [comment]
It looks like ARM images are in but, the new version is showing this:

```
# dpkg --print-architecture
armel
```

where's 16.4 shows this:

```
# dpkg --print-architecture
arm64
```

This is on **bookworm**.

**Comment by tianon** [comment]
This is unfortunately somewhat expected -- the builds for these architectures are still in-queue/in-progress, and will show up eventually (the downstream DOI build queue is very full right now thanks to a small backlog plus Debian update yesterday).

**Comment by yrashk** [comment]
arm64 build is good now.

**Comment by niallnsec** [comment]
@yrashk Are you sure? I'm still not seeing it in docker hub or when pulling any of the version 17 images. If I pull with platform set to linux/arm64 I get an armhf build :/

**Comment by yrashk** [comment]
> @yrashk Are you sure? I'm still not seeing it in docker hub or when pulling any of the version 17 images. If I pull with platform set to linux/arm64 I get an armhf build :/

You are right, I mis-identified new digest for the correct image. Shows `armhf` here, too.

**Comment by tianon** [comment]
Builds are up now. :+1:
