### ISSUE TITLE
Allow not using either HOST_AUTH_METHOD or PASSWORD for initialisation

### ISSUE THREAD

**Issue by casKd-dev** [docker-library/postgres#1281]
Hello everyone,

I suggest adding a option that would allow skipping of authentication method init to the image for people that extend based on this image. I have to currently disable `docker_verify_minimum_env` in `docker-entrypoint.sh` to add my own init scripts and generate my own hba file without anything else. It would be great if this could be something like `POSTGRES_AUTH_INIT=disable` which would skip these steps.

**Comment by tianon** [comment]
Yep, the entrypoint is designed to be source-able and thus composable, so skipping behavior it has that you don't want is going to be something we suggest writing your own entrypoint for (sourcing ours and adjusting the invoked functions, as seen in #1150).
