### ISSUE TITLE
Initdb scripts that connect via TCP/IP?

### ISSUE THREAD

**Issue by tazle** [docker-library/postgres#129]
We would like to run some Java software (DB migrations) through the initdb mechanism, but it would have to connect to Postgres via TCP/IP, which isn't currently possible, since Postgres doesn't yet listen on TCP/IP sockets at that point.

Do you think it would be problematic if Postgres did listen on 127.0.0.1 during initdb? As I understand docker, this shouldn't expose the service to clients prematurely, but would allow initdb scripts to connect using TCP/IP.

**Comment by formerlyKurt** [comment]
I, too, am interested in the answer to this question having the need to run liquibase upgrade scripts during the initialization phase. In this way, once the database initialization phase is completed then we are assured that the upgrade is complete.

Thanks!

**Comment by yosifkit** [comment]
Aw, why do drivers not support connecting on the socket: https://jdbc.postgresql.org/documentation/91/prepare.html.

:+1: yeah let's fix this.
