### ISSUE TITLE
Update DOCKER_PG_LLVM_DEPS for Alpine 3.21

### ISSUE THREAD

**Issue by ImreSamu** [docker-library/postgres#1296]
Currently,
the Alpine `DOCKER_PG_LLVM_DEPS` variable [is locked to LLVM15](https://github.com/docker-library/postgres/blob/0b87a9bbd23f56b1e9e863ecda5cc9e66416c4e0/Dockerfile-alpine.template#L55C1-L58C21)   `{{ def llvmver: "15" -}}`
*  https://github.com/docker-library/postgres/pull/1077  

With the upcoming release of Alpine 3.21, it would be advisable to switch back to the repository's current LLVM version,
which is expected to be LLVM19.

As far as I know, several fixes have been introduced to address the original issue:
* [PG 16.1: "Add support for LLVM 16 and 17" (Thomas Munro, Dmitry Dolgov)](https://www.postgresql.org/docs/16/release-16-1.html)
* [PG 16.2: "Avoid deprecation warning when compiling with LLVM 18 (Thomas Munro)"](https://www.postgresql.org/docs/16/release-16-2.html)
* [PG 16.3: "Fix incompatibility with LLVM 18" (Thomas Munro, Dmitry Dolgov)](https://www.postgresql.org/docs/16/release-16-3.html)
* [PG 16.5: "Fix incorrect LLVM-generated code on ARM64 platforms "](https://www.postgresql.org/docs/16/release-16-5.html#RELEASE-16-5-MIGRATION)

I am not sure what compatibility issues might arise from upgrading existing installations,
but it seems unlikely to cause significant problems in the next Alpine release.

important: 
* The `DOCKER_PG_LLVM_DEPS` variable should definitely be retained for compatibility reasons.  https://github.com/search?q=DOCKER_PG_LLVM_DEPS+language%3ADockerfile&type=code

**Comment by ImreSamu** [comment]
Alpine Linux 3.21.0 Released
* https://www.alpinelinux.org/posts/Alpine-3.21.0-released.html
* LLVM 19

**Comment by yosifkit** [comment]
So, to minimize possible incompatibilities, we only move to a newer llvm for Alpine 3.21. I am working on a PR and I think we still have to hard code to a specific value since installing `llvm-dev` brings in `17` (and I think we still need to set `LLVM_CONFIG` and `CLANG` variables). But is `llvm19` the best choice when Alpine has chosen `llvm16` for their `postgresql` [14](https://git.alpinelinux.org/aports/tree/community/postgresql14/APKBUILD?h=3.20-stable&id=5fa8104598353a1ed88e81bd547a073f1634bbfb#n16) and [15](https://git.alpinelinux.org/aports/tree/community/postgresql15/APKBUILD?h=3.21-stable&id=40544ade947bec1798edb0f749f4e967e842624b#n16) packages?

**Comment by ImreSamu** [comment]
Ouch, this really isn’t as simple as I thought.

imho: Any progress is good, and it would really be great to avoid unnecessary risks because they are not good for the users either – plus, they require extra support from the maintainers.

For this reason, even the LLVM version chosen by the current Alpine seems fine to me.
In other words:
* pg13...pg16:   llvm16
* pg17... :    llvm18

Based on this - assuming that edge~=3.21:
```
$ docker run -it --rm alpine:edge sh -c "apk add postgresql15-jit" | grep llvm
(21/22) Installing llvm16-libs (16.0.6-r8)
$ docker run -it --rm alpine:edge sh -c "apk add postgresql16-jit" | grep llvm
(21/22) Installing llvm16-libs (16.0.6-r8)
$ docker run -it --rm alpine:edge sh -c "apk add postgresql17-jit" | grep llvm
(21/22) Installing llvm18-libs (18.1.8-r1)
```

**Comment by yosifkit** [comment]
PR incoming with the most progressive option: trying them all at llvm19 in Alpine 3.21. Once the Alpine 3.21 images are published to Docker Hub, we can restart the tests to see what works and which should be pulled back on llvm version.
