### ISSUE TITLE
Customizing Postgres with parameterized SQL script

### ISSUE THREAD

**Issue by formerlyKurt** [docker-library/postgres#130]
Is there a way to read environment variables in a .sql file copied to the `/docker-entrypoint-initdb.d/` directory?  I created a file with some basic commands such as:

`CREATE ROLE app WITH 
	LOGIN PASSWORD :password
	NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION IN ROLE master;
`

However, the environment variable is not being read on execution.  Is there a way to do this that I'm missing?

CREATE ROLE
db_1 | ERROR:  syntax error at or near ":" at character 44
db_1 | STATEMENT:  CREATE ROLE app WITH
db_1 | 		LOGIN PASSWORD :password
db_1 | 		NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION IN ROLE master;
db_1 | ERROR:  syntax error at or near ":"

Thanks!

**Comment by yosifkit** [comment]
The sql files are just piped to `psql`.  I think if you want to you own interpolation, you could save the file without ending in `.sql` and just process it in your own shell script in `/docker-entrypoint-initdb.d/`.  Maybe something like:
```bash
#!/bin/bash
sed -r 's/MY_PASSWORD/'"$password"'/' mysql-file | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"
```

**Comment by formerlyKurt** [comment]
Thanks, @yosifkit! I'll give that a try.

**Comment by formerlyKurt** [comment]
Weird -- seems that there is something going wrong with this approach.

Output:
`sed: can't read mysql-file.txt: No such file or directory`

When I `docker exec -it <container-id> bash` into the container, I can see the file.  I can run the command there manually (after `su - postgres`) but somehow this doesn't work when doing this from the `/docker-entrypoint-initdb.d/` directory.

Any ideas here?

**Comment by tianon** [comment]
The entrypoint doesn't "cd" into the initdb directory, so you'll want to
use the full path instead (or put the mysql-file.txt elsewhere to insulate
yourself a little bit better from future changes to our initdb behavior).

Another option would be to install/use "envsubst" in your image, but the
"sed" solution has the benefit of working in the vanilla image as-is.

**Comment by formerlyKurt** [comment]
So I tried going the route of running `psql` myself from a .sh file copied into the `docker-entrypoint-initdb.d/` directory to use the setup/config . Sorry @yosifkit I'd have to run too many `sed` commands to replace the plethora of env variables that I have. But I can't connect to the database. 

I am running the following `psql` command:

`psql -a -e --username postgres -h $DB_HOST -c "CREATE ROLE app WITH LOGIN ENCRYPTED PASSWORD '${POSTGRES_PASSWORD}' CREATEDB;"`

DB_HOST is set to localhost.

I get the following error:

    db_1 |    /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/db-init.sh
    db_1 | psql: could not connect to server: Connection refused
    db_1 | 	Is the server running on host "localhost" (::1) and accepting
    db_1 | 	TCP/IP connections on port 5432?

Seems I'm doing something incorrectly here...just not sure what that is.

**Comment by tianon** [comment]
Can you try without "-h" so that it uses the unix socket instead of trying
to connect?  It's not listening on TCP during initialization so that we
don't get external services thinking the database is up and ready before it
really is.

**Comment by formerlyKurt** [comment]
Well, that works @tianon.  Thanks!
