### ISSUE TITLE
why isn't init-user-db.sh example an sql file?

### ISSUE THREAD

**Issue by greaber** [docker-library/postgres#139]
The docs give an example of adding a shell script to add a user and database and grant the user privileges on the database.  But AFAICT a sql script would work in this case and be a little bit simpler (since the shell script just runs psql).  So maybe it would be better to use a different example?

**Comment by mmarzantowicz** [comment]
You can provide SQL example if you want. The reason for having shell script in docs is simply historic (support for executing shell scripts was added before support for SQL files).

**Comment by tianon** [comment]
This is a bit of an old one, but I think it's also worth noting the shell format explicitly since it's harder to get right.

Closing since this isn't really an issue with the image. :+1:
