### ISSUE TITLE
need help installing node

### ISSUE THREAD

**Issue by greaber** [docker-library/postgres#143]
Hi, I want to install node to use the Azure node api for archiving WAL.  I thought I could just copy the apt commands in the Dockerfile like this:

```
RUN set -x \
    && apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates wget \
    && wget -O /tmp/setup_5.x https://deb.nodesource.com/setup_5.x \
    && bash < /tmp/setup_5.x
    && apt-get install -y nodejs
```

but I am getting a bunch of errors from the apt commands, and it doesn't work.  I find apt a confusing program that I hope one day docker can make obsolete.  What am I doing wrong?

**Comment by Starefossen** [comment]
Looks like you might be missing a backslash `\` at line 5:

```
RUN set -x \
    && apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates wget \
    && wget -O /tmp/setup_5.x https://deb.nodesource.com/setup_5.x \
    && bash < /tmp/setup_5.x \
    && apt-get install -y nodejs
```

**Comment by greaber** [comment]
Oops, yes,  you are right that I have that problem.  It isn't the problem I was worried about, but I can't reproduce that problem now.  It must be that either I had a bad Internet connection or one of the servers I needed to connect to was out.  Sorry for the bother.
