### ISSUE TITLE
What is the recommended way to configure postgres?

### ISSUE THREAD

**Issue by greaber** [docker-library/postgres#144]
I am putting my local overrides in a file `postgres.conf.local` and then doing something like this:

```
RUN { echo; echo "include '/local/postgresql.conf.local'"; } >> "/usr/share/postgresql/$PG_MAJOR/postgresql.conf.sample"
COPY postgresql.conf.local /local
```

Is it how I am supposed to do it?

**Comment by evoyy** [comment]
That should be fine. Since `/usr/share/postgresql/$PG_MAJOR/postgresql.conf.sample` is symlinked to `/usr/share/postgresql/postgresql.conf.sample`, you don't need `$PG_MAJOR`. I copy my config like this:

````
COPY postgresql.conf /usr/share/postgresql/postgresql.conf:ro
````

**Comment by evoyy** [comment]
That should be fine. I do it like this:

````COPY postgresql.conf /usr/share/postgresql/$PG_MAJOR/postgresql.conf.sample````

When initdb is called by docker-entrypoint.sh, the config is copied into the $PGDATA directory.

**Comment by sheerun** [comment]
@evoyy It doesn't work for me for postgres 9.5 image, nothing is copied.

**Comment by sheerun** [comment]
Actually it works, but for some reason postgresql shows "selecting default max_connections ... 100"  instead of 200 min connections I've selected. `SHOW ALL` query shows correct config.

**Comment by speckins** [comment]
Another option is to redefine the CMD in your Dockerfile.  The original one is

    CMD ["postgres"]

but you can add configuration options, e.g.,

    CMD ["postgres",
         "-c", "logging_collector=on",
         "-c", "log_destination=csvlog"]

**Comment by Coinhexa** [comment]
> Another option is to redefine the CMD in your Dockerfile. The original one is
> 
> ```
> CMD ["postgres"]
> ```
> 
> but you can add configuration options, e.g.,
> 
> ```
> CMD ["postgres", \
>      "-c", "logging_collector=on", \
>      "-c", "log_destination=csvlog"]
> ```

How do you put environment variables inside the CMD commands? I dont want to hardcode the names of the certificate files for SSL support
