### ISSUE TITLE
Version '9.3.11-1.pgdg80+1' for 'postgresql-9.3' was not found

### ISSUE THREAD

**Issue by Brenou** [docker-library/postgres#145]
Hi,

It seems to be your current version of postgre is depreciate.
I got this when I build the postres:9.3  : **Version '9.3.11-1.pgdg80+1' for 'postgresql-9.3' was not found**

I checked on http:_//apt.postgresql.org/pub/repos/apt/pool/9.3/p/postgresql-9.3/_  .
I think the new PG_VERSION is 9.3.12-1.pgdg80+1

Can you verify it ?

Thanks

**Comment by vdmitriyev** [comment]
In case someone would like to use Ubuntu (for me it was "FROM ubuntu:14.04"), correct value of "PG_VERSION" for postgresql 9.4 will be 9.4.7-1.pgdg14.04+1 . Other values can be found here - http://apt.postgresql.org/pub/repos/apt/dists/trusty-pgdg/9.4/binary-amd64/ inside "Packages.gz" file.

**Comment by tianon** [comment]
This was fixed a while ago. :+1:

**Comment by vdmitriyev** [comment]
You are welcome!
