### ISSUE TITLE
Centos version

### ISSUE THREAD

**Issue by sylvainmouquet** [docker-library/postgres#147]
The docker image is based on ubuntu but i need to use it from centos version.
It's possible to decline the postgres image from centos version ?

**Comment by mmarzantowicz** [comment]
Image is based on `Debian Jessie` (https://github.com/docker-library/postgres/blob/master/Dockerfile.template#L2) not `Ubuntu`. `PostgreSQL` packages are installed from repository at `http://apt.postgresql.org/pub/repos/apt/`.

Now, what exactly do you want to do with/on `Centos`? You can create your own postgres images based on Centos docker images but you must compensate for potential differences in build process and package layout between RHEL/Centos and Debian.

**Comment by sylvainmouquet** [comment]
I prefer use official docker images that why i dislike create my own image.
Centos provides docker images : https://hub.docker.com/r/centos whose one for postgres https://hub.docker.com/r/centos/postgresql/

**Comment by mmarzantowicz** [comment]
Don't know about your particular need but I'd recommend you this (Debian based) official PostgreSQL image. Centos image, that you provided link to is ... inferior. It uses `supervisord` which is clearly not needed and does not have as many configuration options as official image. Then only used case I can see one would prefer Centos based image is to integrate with some RH software which is not available on other Linux distros.

**Comment by sylvainmouquet** [comment]
Yes I need to use Centos based image because i need to install a proprietary library compatible with Centos only.
