### ISSUE TITLE
How to set fsync=off

### ISSUE THREAD

**Issue by rarkins** [docker-library/postgres#149]
Sorry for the simple question, hopefully the answer is also simple.

If I want to use the standard PG 9.5 image but the only thing I want to change is to set `fsync=off`, how/where should I configure that?

I'm hoping there's a way to do this without completely recreating the entrypoint or conf files.

**Comment by ImreSamu** [comment]
> I want to change is to set fsync=off, how/where should I configure that?

I think it is similar solution than the  ` -c shared_buffers=256MB` example here : 
https://github.com/docker-library/postgres/pull/54#issuecomment-190978193

**Comment by rarkins** [comment]
Thanks, that works. For `docker-compose`, you can simply add this to the `command:` line, e.g. `command: -c fsync=off`

**Comment by simplenotezy** [comment]
@rarkins Awesome, thanks for sharing. Know about a way to do something similar with github actions?
