### ISSUE TITLE
Container exit with code 128

### ISSUE THREAD

**Issue by blazeeboy** [docker-library/postgres#150]
I'm using docker-compose to run a container of `postgres:9.5.2` , the container runs successfully, i'm mapping the data volume to a local directory in `/root/data/<project-name>/db` and passing the required environment variables through `.env` file.

the problem is that in less than 24 hours the container crash with exit code 128, I don't know the reason, and it's not this container only, the other container that depend on this image also exit with the same code, it's a ruby container running `foreman` process.

I suspect that the ruby container crash because of postgres container crashed, but I don't know how to make sure of this claim.

also I have to mention that I set `restart: always` to both containers but It doesn't rerun them, but i think this is a separate problem.

so the question now, is that exit with code 128 is something common in this image or specific to me?
and how to debug it to discover the root cause?

**Comment by yosifkit** [comment]
As long as pid 1 is your main process, I have not seen a case where `restart: always` does not work.  Do you have any useful logs or a way someone could reproduce?

**Comment by blazeeboy** [comment]
- how to know if my process PID is 1
- this `restart: always` problem is not logical i admit, i'll monitor it for another couple days and see how it goes.
- what logs do you think i can trace this problem form? which log file i should map to my machine and investigate it later?

**Comment by yosifkit** [comment]
To see what pids are in the container, you should be able to do `docker exec container-name ps aux` to see what is running.

What does you docker-compose.yml have it it?

**Comment by blazeeboy** [comment]
I suggest we close this story, the problem stopped happening for the last
couple day, and can't reproduce it.

On Mon, May 2, 2016 at 9:58 PM, yosifkit <notifications@github.com> wrote:

> To see what pids are in the container, you should be able to do docker
> exec container-name ps aux to see what is running.
>
> What does you docker-compose.yml have it it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker-library/postgres/issues/150#issuecomment-216344730>
>



-- 
Emad Elsaid
Software Engineer
*Mobile*: +20 114 137 1675
*Web*: http://www.blazeboy.me
*Github*: http://www.github.com/blazeeboy

**Comment by tianon** [comment]
Cool, sounds good! :+1:
