### ISSUE TITLE
Create multiple users and databases

### ISSUE THREAD

**Issue by phlegx** [docker-library/postgres#151]
Hi!

I was wondering on how to create multiple databases with multiple users? As far as I have seen [here](https://hub.docker.com/_/postgres/), currently only one user that has superuser power and the corresponding database can be created trough `POSTGRES_USER` 

Is creating multiple databases and users currently already possible with the ENV variables? If not, is there another way I can use via docker/docker compose?

**Comment by mmarzantowicz** [comment]
I think recommended way is to create new images based on `postgres:xxx` and add custom scripts there. Here is how I do this:

- `Dockerfile`
```
# vim:set ft=dockerfile:
FROM postgres:latest
MAINTAINER ...

# Custom initialization scripts
COPY ./create_user.sh   /docker-entrypoint-initdb.d/10-create_user.sh
COPY ./create_db.sh     /docker-entrypoint-initdb.d/20-create_db.sh
```
- `create_user.sh`
```
#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database role: ${DB_USER}"

$POSTGRES <<-EOSQL
CREATE USER ${DB_USER} WITH CREATEDB PASSWORD '${DB_PASS}';
EOSQL
```
- `create_db.sh`
```
#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database: ${DB_NAME}"

$POSTGRES <<EOSQL
CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};
EOSQL
```

Then I have to run my image with additional environment variables: `DB_NAME`, `DB_USER`, `DB_PASS`. If you want to create more than one db you can go with `DB_XX_NAME` and so on but it's really up to you how to name variables. Also note, that files files should be executable (+x).

For really massive deployments you can use environment file with `docker-compose`.

**Comment by mrts** [comment]
If you don't want to create a new image, it's also possible to mount the multiple DB creation script as a volume, see https://github.com/mrts/docker-postgresql-multiple-databases

**Comment by lewispham** [comment]
But still guys, why shouldn't we support this feature in this image?

**Comment by MartinKaburu** [comment]
If you would like to create multiple databases under one user, try this script https://github.com/MartinKaburu/docker-postgresql-multiple-databases

**Comment by yami12376** [comment]
Why this is not supported in the main image on docker hub?

**Comment by ChrisjanWust** [comment]
> If you would like to create multiple databases under one user or multiple users, use this script https://github.com/MartinKaburu/docker-postgresql-multiple-databases#using-multiple-databases-with-the-official-postgresql-docker-image

How would you use this script in conjunction with a docker volume (which maintaining data persistence)? Honestly, it feels like an ugly solution.

**Comment by tcurdt** [comment]
Is there any chance for this being reopened and improved?

**Comment by yosifkit** [comment]
> Is there any chance for this being reopened and improved?

Short answer, no.
Slightly longer answer: https://github.com/docker-library/postgres/pull/240#issuecomment-314228559

**Comment by tcurdt** [comment]
@yosifkit Could you give an even longer answer, too?

Creating a new image is not great. Mounting a file to `/docker-entrypoint-initdb.d/:` is better - but again not really ideal. Having everything contained in a single yml is the prefered way with docker compose and friends.

So why is the resistance to improve this? I am honestly just curious if there is a good reason.

**Comment by EliYk** [comment]
If anyone needs this, there seems to be this image - 
https://hub.docker.com/r/lmmdock/postgres-multi/

**Comment by robertlagrant** [comment]
Just here to give a rationale for this feature.

I have a raspberry pi (soon to be 2 networked) with k3s on it. I currently have two services on it, that each need a postgres instance. As I'm resource constrained and paranoid, I want them to share a postgres, but not a user. I'd like to declaratively create their users.

I can do that with the DB creation script, but only once. If I add another service afterwards and modify that script, it won't work as that script only runs if there is an empty data directory. From [the docs](https://github.com/docker-library/docs/blob/master/postgres/README.md#initialization-scripts):

> scripts in /docker-entrypoint-initdb.d are only run if you start the container with a data directory that is empty; any pre-existing database will be left untouched on container startup

I'd love to be able to both add users declaratively (the Docker way) and also update passwords if necessary declaratively. Being able to declare multiple users and passwords and have it be reconciled on start would be amazing.

**Comment by tianon** [comment]
This feature, if we implemented it, would have the same behavior as the file you're talking about -- it would only happen on _fresh_ database initialization (just like all our variables/setup do).

What you're looking for is something like an `always-initdb.d` directory that runs a set of SQL files not just on database `initdb` but on _every_ container startup.  We don't support such a thing natively, because the container startup cost for doing so is very real and heavy, but the pieces are all available for building it in a reasonable way:
- https://github.com/docker-library/postgres/pull/496
- https://github.com/docker-library/postgres/pull/1150

**Comment by robertlagrant** [comment]
@tianon ah thanks! I couldn't find that in the docs I was looking in. I will investigate. If you need a PR to document it let me know and I can try that while experimenting.
