### ISSUE TITLE
Unable to start PostgreSQL in container read-only mode

### ISSUE THREAD

**Issue by formerlyKurt** [docker-library/postgres#154]
Is there a way to set the container with the read-only setting turned on?  I am using the 9.5.2 image, have set the `PGDATA` variable to a separate volume container in the compose file but get an error on startup. 

`- PGDATA=/var/lib/postgresql/data/pgdata`

Error:

    db_1      | chmod: changing permissions of ‘/run/postgresql’: Read-only file system
    db_1 exited with code 1

Is this normal?

Thanks!

**Comment by yosifkit** [comment]
You'll need to add a `volume` for `/run/` as well, since that is where postgres puts its pid and socket.  We don't make this volume in the Dockerfile since there is no way to unvolume and it may not be useful for everyone.

**Comment by formerlyKurt** [comment]
Thanks for the reply @yosifkit!  Yes, creating the volume for `/run/` did get me a bit further.  Now I'm getting another error:

    db_1      | LOG:  MultiXact member wraparound protections are now enabled
    db_1      | LOG:  database system is ready to accept connections
    db_1      | LOG:  autovacuum launcher started
    db_1      |  done
    db_1      | server started
    db_1      | /docker-entrypoint.sh: line 71: cannot create temp file for here-document: Read-only file system
    db_1 exited with code 1

Any suggestions for this?

**Comment by tianon** [comment]
Ah, you're going to need a volume on `/tmp` too -- it might be worth making both of those `tmpfs` instead; ie `--tmpfs /tmp --tmpfs /run` or `docker-compose` should have a `tmpfs:` field: https://docs.docker.com/compose/compose-file/#tmpfs

**Comment by formerlyKurt** [comment]
@tianon using `tmpfs` in the compose file brings me back to the original problem above.

Here's how it's laid out in the compose file:

                tmpfs:
                    - /tmp
                    - /run

What am I missing?

**Comment by formerlyKurt** [comment]
Any other suggestions @tianon and @yosifkit?

Thanks!

**Comment by formerlyKurt** [comment]
Using `tmpfs` also need to add `/run/postgresql`:

    tmpfs:
              # For read-only filesystem, need to create a volume/tmpfs for PostgreSQL to run its much
              # needed configuration. The read-only flag does not make volumes and tmpfs read-only.
              - /tmp
              - /run
              - /run/postgresql

**Comment by tianon** [comment]
Indeed, I just ran the following successfully:
```console
$ docker run -it --rm --read-only --tmpfs /run/postgresql --tmpfs /tmp postgres
```

After it was initialized, I successfully connected from a second container and queried it. :smile:

So, it appears that we actually need `/run/postgresql`, but do not need `/run` directly. :+1:

**Comment by formerlyKurt** [comment]
✅ ✅ confirmed that in the compose file too.

**Comment by tianon** [comment]
Woot :tada:

So we're good to close this now? :smile:

**Comment by formerlyKurt** [comment]
Yup!

**Comment by daggerok** [comment]
@iamKurt, please share your compose file
Thanks!
