### ISSUE TITLE
Could you please support for windows containers?

### ISSUE THREAD

**Issue by mrdotmoon** [docker-library/postgres#156]

**Comment by yosifkit** [comment]
You can run this on Windows using [docker-machine](https://docs.docker.com/engine/installation/windows/) or the new [Docker for Windows beta](https://blog.docker.com/2016/03/docker-for-mac-windows-beta/), but if you want a native Windows container based upon `windowsservercore` or `nanoserver`, that is something we'd like to be able to do in the future.

**Comment by Shnitzelil** [comment]
Hi,
Having same request here for windows...

**Comment by tianon** [comment]
Doh!  Didn't notice this duplicate.  I'm going to close this one in favor of https://github.com/docker-library/postgres/issues/324, since it's got more discussion around making this actually happen. :+1:
