### ISSUE TITLE
pg_resetxlog cant be ran with super user

### ISSUE THREAD

**Issue by sisso19** [docker-library/postgres#158]
Hello

Yesterday I updated my docker-engine and something seems to have gone wrong. Currently I am continuously getting this in my logs:

    PANIC:  could not locate a valid checkpoint record
    LOG:  startup process (PID 17) was terminated by signal 6: Aborted
    LOG:  aborting startup due to startup process failure
    LOG:  database system shutdown was interrupted; last known up at 20
    LOG:  invalid primary checkpoint record
    LOG:  invalid secondary checkpoint record

I commited the container to be able to access the shell since the container was always restarting

    docker run -it -v /my/data/dir/:/var/lib/postgres/data/ postgresfailingcontainer /bin/bash

When trying to fix the issue I found a [thread](http://stackoverflow.com/questions/8799474/postgresql-error-panic-could-not-locate-a-valid-checkpoint-record) recommending me to use pg_resetxlog. However I am unable to run the command.
I first tried as root but got a error saying that i needed to run it as the postgres super user

    root@2580e7a629c3:/# pg_resetxlog /var/lib/postgresql/data/
    pg_resetxlog: cannot be executed by "root"

Then I tried it wil the default super user, postgres, but I was unable because the user does not seem to have access to the command.

    root@2580e7a629c3:/# su postgres -c "pg_resetxlog /var/lib/postgres"
    sh: 1: pg_resetxlog: not found

This is how my docker-compose file is defined with this postgres server I am having issues with

    postgres:
      restart: always
      image: postgres
      environment:
        - POSTGRES_PASSWORD=abc123
        - POSTGRES_DB=database
      volumes:
        - /var/docker/postgres/data:/var/lib/postgresql/data

I am unable to see the version of the container that I am running, but this is the entry in docker images 

    postgres                                latest              0f3af79d8673        6 weeks ago         265.7 MB

The date that I am writing 20th may 2016 10:09 GMT+0

**Comment by yosifkit** [comment]
The `su` command is messing with `PATH` so the easiest solution is to just use gosu to drop from root to postgrtes `gosu postgres pg_resetxlog /var/lib/postgresql/data`.  Hopefully that works for you! :smile:

**Comment by sisso19** [comment]
Great, thank you. I was able to run the command but unfortunately, this did not fix my issue.

**Comment by sisso19** [comment]
This **did** fix my problem. I had the incorrect path to my broken postgres database. 
Thank you for your help!

**Comment by dimitriskr** [comment]
In case you have Postgresql 12, the command to run is `gosu postgres pg_resetwal /var/lib/postgresql/data` as pg_resetxlog doesn't exist anymore to that version

**Comment by 631068264** [comment]
bash: gosu: command not found

**Comment by yanko-ivanov** [comment]
A note to add to future devs stumbling upon this, gosu can be installed from here - https://github.com/tianon/gosu

But the package isn't available in the main alpine repo. 
The easiest route to fixing this is actually using the readily available su-exec. So in the context of a docker setup running alpine, follow the instructions above, then once you're in the container - `su-exec postgres pg_resetwal /var/lib/postgresql/data` 
Working for postgres v15.1
