### ISSUE TITLE
gpg: keyserver timed out

### ISSUE THREAD

**Issue by JoAngel8** [docker-library/postgres#161]
Success by this answer : [https://github.com/tianon/gosu/issues/17](url)
----
Do you have a corporate firewall of some kind in place that might be blocking the traffic?

You can try `hkp://p80.pool.sks-keyservers.net:80` or `hkps://hkps.pool.sks-keyservers.net` in place of `ha.pool.sks-keyservers.net`, and might have more success in limited enviroments (since it'll then use port 80 or 443 instead):

gpg --keyserver `hkp://p80.pool.sks-keyservers.net:80` --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4

**Comment by tianon** [comment]
Any particular reason you're building from source and not using the existing image as-is?

Combine automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with additional configuration or functionality injected.

**Comment by JoAngel8** [comment]
Yes, I want to personilize my composition of container.

**Comment by JoAngel8** [comment]
I have to do a sonar5.3 and postgressql container for my work. 

It's also my First Time I have to do this.


Bien cordialement,
JOSEPH-ANGELIQUE Gaudry
