### ISSUE TITLE
Different Database for SQL scripts inside /docker-entrypoint-initdb.d/

### ISSUE THREAD

**Issue by jamisonhyatt** [docker-library/postgres#164]
Is there a way to override the database .sql scripts are executed against?  By default they are run against the 'postgres' database.

I switched my scripts to .sh scripts as a workaround, which was fine for tables...but creating procedures has gotten a little messy with some of the postgres syntax ($$) needing to be escaped.  This requires keeping 2 versions of the proc, the pure sql version and the escaped version.

**Comment by yosifkit** [comment]
Have you tried setting `POSTGRES_DB` on your `docker run`?  This would switch all `sql` files to this new database.

You could keep your sql files, named with something not ending in `.sql` or `.sql.gz`, and then run your sql from your shell script.  Or you can put all your sql in a single quoted here-doc within the shell script (https://en.wikipedia.org/wiki/Here_document#Unix_shells).

**Comment by jamisonhyatt** [comment]
Thanks, specifying `POSTGRES_DB` on run was an easy fix.  I'm new to postgres, and the way it was documented led me to believe that the `postgres` db would not be created if I specified the DB name at runtime.  Turns out it was anyways.  Thanks again.
