### ISSUE TITLE
Nice to have: change docker-entrypoint.sh to entrypoint.sh

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/postgres#165]
It is just a standard in all official images, so it is a bit counterintuitive.

https://github.com/docker-library/postgres/blob/04b1d366d51a942b88fff6c62943f92c7c38d9b6/9.4/Dockerfile#L54-L56

**Comment by yosifkit** [comment]
We've actually been moving the opposite direction to keeping the `docker-` and adding it to the path: https://github.com/docker-library/mysql/blob/c7c1d85475749066b229691ade668bc49139d52f/5.7/Dockerfile#L59-L61

**Comment by pierreozoux** [comment]
Thanks for the info, I'll keep it in mind for the other Dockerfiles.
(I think it is good to have conventions, it allows to save brain cycles ;) )
