### ISSUE TITLE
pgadmin 

### ISSUE THREAD

**Issue by logicminds** [docker-library/postgres#166]
When will pgadmin v4 be included and auto configured?

**Comment by znmeb** [comment]
There is a pgAdmin image, maintained by Dave Page and other pgAdmin developers. See https://www.pgadmin.org/download/pgadmin-4-container/. It seems preferable to me to stick with the "one service per container" philosophy and have pgAdmin and PostgreSQL running in separate containers, especially if pgAdmin developers are maintaining that image.

**Comment by yosifkit** [comment]
Closing old issue. Agree that since pgadmin is a separate service, it should be run and maintained in its own image and container.
