### ISSUE TITLE
Docker Security Benchmark - Running as root warning

### ISSUE THREAD

**Issue by austinnichols101** [docker-library/postgres#170]
**docker-bench-security** (https://github.com/docker/docker-bench-security) reports warnings for the postgres container.  Specifically, section 4.1.

[INFO] 4 - Container Images and Build Files
[WARN] 4.1  - Create a user for the container
[WARN]      **\* Running as root: postgres**

The postgres service IS running as user postgres, but it's being flagged because the foreground process is being launched by user root via gosu.

The issue and workaround are described in detail in the corresponding section (4.1) of the **CIS Docker 1.11.0 Benchmark** document:
https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.11.0_Benchmark_v1.0.0.pdf

**Comment by tianon** [comment]
My question here would be the same as in https://github.com/docker-library/rabbitmq/issues/88#issuecomment-228824970:
> Since the service itself explicitly does not run as root (and given that user namespace support in Docker makes this a trivial non-issue), I'm not sure I understand what the relevance is? Can you elaborate on what issues this causes?

**Comment by wglambert** [comment]
Since this issue seems unrelated to any errors in the image itself, and being a few years without further comment, I'm going to prune the issue.
If you believe this to be in error then let me know and I'll re-open it
