### ISSUE TITLE
Ensure only one running instance on data volume

### ISSUE THREAD

**Issue by fwiesel** [docker-library/postgres#171]
Hi,

currently you can start two containers on the same shared volume, which trashes the data, because the pid-file logic obviously doesn't work across containers and instances.
Both postgres instances come up with PID 1 with pid-namespace separation, and without they still might have the same PID, if run on different hosts.

Currently, I am solving it by wrapping `docker-entrypoint.sh` with something like

``` !bash
exec 9>${LOCKFILE} || exit 1
/usr/bin/flock -n 9 
exec /docker-entrypoint.sh "$@"
```

I was wondering if you would be interested to see that kind of capability integrated in the image itself (obviously not the exact same way of implementing it).

**Comment by tianon** [comment]
I'm really surprised PostgreSQL itself doesn't already do this. :disappointed:

I think I'm really -1 on implementing anything specific to overcome this limitation though, especially given that upstream doesn't do anything special (beyond using a pid file) to prevent it.

Your workaround should serve as a good reference for folks in the future who are running into this issue though. :+1: :heart:
