### ISSUE TITLE
docker daemon restart isn't starting postgres as expected

### ISSUE THREAD

**Issue by marcelmfs** [docker-library/postgres#172]
`latest` postgres container, with:

```
15:46 $ docker version
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:09:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   876f3a7
 Built:        Tue Jul  5 02:20:13 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by yosifkit** [comment]
I am not sure what set of events are leading to this, but are you starting the postgres container with `--restart=always` in the docker flags?
```console
$ docker run -d --restart=always [other docker run options] postgres
```

**Comment by marcelmfs** [comment]
Yes, the restart policy is set to always so if docker's able to detect that the postgres server died in some way it would restart it (I'm using tini as process manager, signal forwarder, BTW). I only face this problem when restarting the docker engine daemon (systemctl restart docker), as one of the last actions on the sysadmin book to see if the stack will come back if the host restarts. And only my two postgres instances do not come back as expected.

**Comment by yosifkit** [comment]
Do you get the same issue on a Linux host that is not running the rc?

**Comment by marcelmfs** [comment]
On a centos7 box, running docker 1.11.1, same thing.

A plain `systemctl restart docker`, though, is way worse, nothing comes back consistently.

rebooting the server behaves as reported in the issue - restarting docker beta alpine's vm.
