### ISSUE TITLE
How to enable pg_stat_statements?

### ISSUE THREAD

**Issue by rarkins** [docker-library/postgres#177]
I would like to enable `pg_stat_statements` on my Docker postgres container. 

As per official documentation:

> The module must be loaded by adding pg_stat_statements to shared_preload_libraries in postgresql.conf

Can I do this somehow without having to fork or extend this project with my own Docker image? I can't find a hit in this repo for either `pg_stat_statements` or `shared_preload_libraries` so thought I'd ask here.

**Comment by bromanko** [comment]
Take a look at the [How to Extend This Image](https://hub.docker.com/_/postgres/) section of the DockerHub repository. You can include a shell script in the `docker-entrypoint-initdb.d` folder. Use this script to adjust the settings in `postgresql.conf`. Here's a naive example I used in a test project:

```bash
#!/usr/bin/env bash
echo "shared_preload_libraries = 'pg_stat_statements'" >> $PGDATA/postgresql.conf
echo "pg_stat_statements.max = 10000" >> $PGDATA/postgresql.conf
echo "pg_stat_statements.track = all" >> $PGDATA/postgresql.conf
```

**Comment by rarkins** [comment]
@bromanko thanks. So could this shell script be included via a Docker volume? i.e. to avoid having to host my own forked container on Docker Hub.

**Comment by bromanko** [comment]
Yup!

**Comment by Alexhha** [comment]
As alternative you can pass these options via -c

```
$ docker run -it --rm -v .... postgres:10.5 \
-c shared_preload_libraries='pg_stat_statements' \
-c pg_stat_statements.max=10000 \
-c pg_stat_statements.track=all
```

**Comment by oliverpool** [comment]
If you are using docker-compose (from https://gist.github.com/lfittl/1b0671ac07b33521ea35fcd22b0120f5#gistcomment-3142997):
```version: '2'

services:
  db:
    image: postgres
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      ...
```
