### ISSUE TITLE
Files don't seem to be copied to the docker-entrypoint-initdb.d folder

### ISSUE THREAD

**Issue by sgronblo** [docker-library/postgres#181]
Tried to create my own `Dockerfile` with the following contents:

```
FROM postgres:9.5

ENV POSTGRES_PASSWORD testtest
```

I also put a wtf.sh that just echoes "WTF!!!!" into a subdirectory named `docker-entrypoint-initdb.d` in the same directory as the Dockerfile. Then I run my docker container with `docker run --name todo_pg -d -p 5432:5432 todo_postgres`. When I do a `docker logs todo_pg` I see the following error: `/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*`. If I log in to the container using: `docker exec -it todo_pg /bin/bash` I can see that the contents of the `/docker-entrypoint-initdb.d` directory is empty. When I check the file https://github.com/docker-library/postgres/blob/04b1d366d51a942b88fff6c62943f92c7c38d9b6/9.5/Dockerfile#L26 I can only see this mkdir command but I can't find any place that would actually copy any .sh or .sql files I put in that directory.

Finally I would like to add that I'm quite a noob at docker so I might be completely misunderstanding how this should work.

**Comment by tianon** [comment]
Your `Dockerfile` needs to actually copy the files into the image; something like this, for example:
```dockerfile
FROM postgres:9.5
ENV POSTGRES_PASSWORD testtest
COPY wtf.sh /docker-entrypoint-initdb.d/
```
or even:
```dockerfile
FROM postgres:9.5
ENV POSTGRES_PASSWORD testtest
COPY *.sh /docker-entrypoint-initdb.d/
```

**Comment by sgronblo** [comment]
I see, I didn't understand from the README.md that I was supposed to handle the copying myself. Thanks for clarifying.
