### ISSUE TITLE
VERSION 9.5.3-1.pgdg80+1 was not found

### ISSUE THREAD

**Issue by RenanJPaula** [docker-library/postgres#185]
I'm trying to generate build and the

-ENV PG_MAJOR 9.5
-ENV PG_VERSION 9.5.3-1.pgdg80+1

is not found...

Thanks for the collaboration!

![whatsapp image 2016-08-11 at 14 44 30](https://cloud.githubusercontent.com/assets/3266640/17602213/0d4fac40-5fe2-11e6-86b6-b4e00cabf36c.jpeg)

**Comment by yosifkit** [comment]
Yeah, we construct the Dockerfile to build a specific version or fail.  I have bumped the Dockerfiles with fc36c25f8ac352f1fea6d0e7cf8d9bd92a4e720f.
