### ISSUE TITLE
Enable ssl

### ISSUE THREAD

**Issue by Xosmond** [docker-library/postgres#192]
i have extended this to make it run on ssl mode, but i need to enter the passphrase on pg_ctl how can i do? i have use the -w option to put the passphrase but i can't because its prompt when i run the container.

**Comment by yosifkit** [comment]
This is not really a problem with the official image, but the only options I can think of are: running it interactively `-it` on docker run (which I am not sure will even work);  just supplying the password in an env on the docker run (and the script can pass it to pg_ctl); or use certs without a password.
