### ISSUE TITLE
Request: Separate, Official PostGIS Repo

### ISSUE THREAD

**Issue by blag** [docker-library/postgres#199]
Hi, I think having a separate, official `postgis` image would be helpful for people who want PostgreSQL+PostGIS. The [`mdillon/postgis`](https://hub.docker.com/r/mdillon/postgis/) image ([repo](https://github.com/appropriate/docker-postgis)) looks pretty good to me, but it isn't an official image in docker-library. Can somebody in the docker-library org (@psftw, @tianon, or @yosifkit),  create an official [postgis repo](https://github.com/docker-library/postgis) and incorporate it?

Let me know if there's anything I can do to help push it in that direction.

Thanks!

**Comment by znmeb** [comment]
+1, although I think it'd be easy to use this image as a base and just do the apt-get install postgis / pgrouting in another Dockerfile. TBH I think that PostGIS / PgRouting and the programming languages (Pl/Python, etc.) should be in the official PostgreSQL image.

**Comment by boozedog** [comment]
+1 for this, particularly if it means we can use Alpine Linux!

**Comment by znmeb** [comment]
I have some free time now - I went ahead and created a whole toolset around this Dockerfile at https://github.com/hackoregon/data-science-pet-containers. But now that I've done that, I think it makes more sense to make PostGIS, pgRouting and all the foreign data wrappers available in Debian part of the base PostgreSQL container, at least for the Debian version.

I don't know anything about Alpine - I don't know what's packaged there. But everything imaginable in the PostGIS space is packaged for Debian. I may just fork this repo and make it into a PostGIS / pgRouting image.

**Comment by ImreSamu** [comment]
The `mdillon/postgis` image (repo) has been started discussing the future maintainership of the image.

* https://github.com/appropriate/docker-postgis/issues/143

We need to find a new home  / maintainers ...
We need to find a global optimum ..

**Comment by tianon** [comment]
That's fine and good, but it's not an official part of PostgreSQL itself, so this isn't the appropriate place to discuss it.

Along that vein, I'm going to close this since this isn't the right place for this discussion (and https://github.com/appropriate/docker-postgis/issues/143 is a much more appropriate venue).
