### ISSUE TITLE
Join pgsql-pkg-docker mailing list to discuss plans for this image

### ISSUE THREAD

**Issue by jberkus** [docker-library/postgres#2]
mwcampbell, tianon, yosifkit:

Please join the new *pgsql-pkg-docker* mailing list so that we can chat about how the official postgres images should be built and maintained.  

http://www.postgresql.org/community/lists/subscribe/

Thanks, looking forward to it.

**Comment by yosifkit** [comment]
This mailing list is mentioned in the [documentation](https://github.com/docker-library/docs/tree/8cb8ac64b196ba29457ee06d3dd03e5bf5c4ecff/postgres#issues).
