### ISSUE TITLE
Can't use a volume mounted from an NFS

### ISSUE THREAD

**Issue by liricooli** [docker-library/postgres#213]
We are currently running a postgres 9.4 container. We map /path/to/mount from the host to /var/lib/postgres/data in the container successfully, and our postgres container is running.

For a specific environment, we need the container to use a volume which is mounted as an NFS storage. 
Unfortunately, postgres does not start.

The error I'm currently getting is from `gosu postgres initdb` command:

```
gosu postgres initdb
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
creating template1 database in /var/lib/postgresql/data/base/1 ... ok
initializing pg_authid ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
syncing data to disk ... initdb: could not fsync file "/var/lib/postgresql/data/base/1": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/base/12136": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/base/12141": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/base": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/global": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_clog": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_dynshmem": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_logical/mappings": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_logical/snapshots": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_logical": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_multixact/members": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_multixact/offsets": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_multixact": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_notify": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_replslot": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_serial": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_snapshots": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_stat": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_stat_tmp": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_subtrans": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_tblspc": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_twophase": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_xlog/archive_status": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_xlog": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/data/pg_tblspc": Invalid argument
ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    postgres -D /var/lib/postgresql/data
or
    pg_ctl -D /var/lib/postgresql/data -l logfile start
```

### System Information
docker version 1.91 host machine is running ubuntu 14.04 

### Steps to Reproduce

1. Mount the NFS with the following command:
`sudo mount.cifs //my-machine/my-shared-folder /path/to/mount -o username=my-user,password=my-password,gid=1000,uid=1000,dir_mode=0700,file_mode=0700`

2. Dockerfile:
I know that there are all kinds of issues with mounting NFS volumes.
To overcome issues, I've changed the uid and gid of postgres to 1000, which is the owner of the mounted folder in the host.
```
FROM postgres:9.4
RUN groupmod --gid=1000 postgres && usermod --gid=1000 --uid=1000 postgres
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["postgres"]
```

3. build the image:
`docker build -t my_postgres my_postgres/`

4. Start the container with /bin/bash so I can run and debug 
`docker run -it -p 5432:5432 -v /path/to/mount:/var/lib/postgresql/data -e DB_USER='my-db-user' -e DB_PASSWORD='my-db-password' -e DB_NAME='dev' -e RUN_MODE='production' my_postgres /bin/bash`

5. Run the first commands of docker-entrypoint.sh
`chown -R postgres "$PGDATA" && chmod g+s /run/postgresql && chown -R postgres:postgres /run/postgresql && gosu postgres initdb`

### Things I've verified
1. User postgres has write access from the container to the mounted volume, for example, running the command:  `gosu postgres `echo "hello" > /var/lib/postgres/data/test.txt` creates a file. also the initdb command succeeds in writing file to this location.

2. Reading and trying various things suggested in these related issues: https://github.com/docker/docker/issues/4213, https://github.com/docker/docker/issues/2259,  https://github.com/docker/docker/issues/7198

**Comment by yosifkit** [comment]
Sorry for the long tail :disappointed:

My guess is that NFS probably does not support some filesystem requirement that PostgreSQL server requires which is why `fsync` is returning "invalid argument".

Possibly related issues/threads:
 - https://www.postgresql.org/message-id/CABUevEzRd6TT89dx5AG_ceLgrvg7KTpCFmM8%3DiKvVL-HRHoM6w%40mail.gmail.com
 - https://forums.docker.com/t/trying-to-get-postgres-to-work-on-persistent-windows-mount-two-issues/12456
 - https://github.com/docker/for-win/issues/445
 - https://www.postgresql.org/docs/9.6/static/creating-cluster.html#CREATING-CLUSTER-NFS

**Comment by tianon** [comment]
Closing given that this is a PostgreSQL limitation, not something we can really solve in the image itself.

**Comment by Itfly** [comment]
@liricooli Did you fix the issue, i also got the problem when deploying postgres with the NFS volume. It stuck on `performing post-bootstrap initialization`

**Comment by liricooli** [comment]
@Itfly nope, sorry. we just worked-around the issue by not using postgres on NFS. also, I didn't spend more time on this issue as I switched jobs.

**Comment by Itfly** [comment]
@liricooli  Thanks.

**Comment by wlisesrivas** [comment]
Any update with this issue guys?

**Comment by tianon** [comment]
@wlisesrivas https://github.com/docker-library/postgres/issues/213#issuecomment-329908750 :wink:
