### ISSUE TITLE
official alpine linux images

### ISSUE THREAD

**Issue by tjamet** [docker-library/postgres#214]
Hi,

Currently only `debian:jessie` is supported in official postgres images. Would it be an option to gain support, inspired from python's `-alpine` as well?

Thanks in advance

**Comment by ptman** [comment]
https://github.com/docker-library/postgres/pull/216

**Comment by tianon** [comment]
Indeed, fixed by #216 :+1:

**Comment by ptman** [comment]
Nothing on docker hub yet?

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/2344 :+1:
