### ISSUE TITLE
9.3 issue

### ISSUE THREAD

**Issue by xuncanzhe** [docker-library/postgres#218]
maybe the ("s!^#?(listen_addresses)\s*=\s*\S+.*!\1 = '\*'!" ) /usr/share/postgresql/postgresql.conf.sample)command have some problem in my computer.
but ("s/^#?(listen_addresses)\s\*=\s\*\S+.\*/\1 = '\**'/") is working.
And about the PG_VERSION  mast be 9.3.15-1.pgdg80+1 will be ok in my computer.

**Comment by tianon** [comment]
Can you provide some more details on what's not working? (especially your `docker run` line and container logs)
