### ISSUE TITLE
Issues with running pg_dump with docker exec?

### ISSUE THREAD

**Issue by rosenfeld** [docker-library/postgres#219]
Hi, today I noticed a weird behavior when trying to restore a dump from my back-ups to my local machine. pg_restore returned successful but without restoring anything from a 600MB dump. With --verbose it reported data-only was implied but I didn't ask for data-only. I was creating the back-up with `docker exec container-name pg_dump -Fc dbname > /tmp/db.dump`. The dump file was created in the Docker host machine as expected but for some reason I was not able to restore from that dump. If I use an external postgresql-client package in the host, then the dump file works as expected. Is `docker exec` appending anything else to the output that could be causing such bad dump file? Maybe the documentation could add a warning if this is the case. If I knew that beforehand I'd probably added some volume mapping to local back-ups (`-v /tmp/db-dumps:/db-dumps`). Anyway, I'm curious. Has someone else experienced such weird behavior? If so, do you know why it doesn't work as expected?

**Comment by rosenfeld** [comment]
The message I got with `--verbose` included this: "pg_restore: implied data-only restore"

**Comment by MFProduction** [comment]
+1

**Comment by tianon** [comment]
Sorry for the delay -- I'm not able to reproduce the issue.  When I run `docker exec --user postgres test pg_dump -Fc postgres > test.dump` and then inspect the resulting file, there's nothing extra in the file (it's simply the binary data generated by `pg_dump` itself):

```console
$ docker exec -i --user postgres test pg_restore < test.dump
--
-- PostgreSQL database dump
--

-- Dumped from database version 10.1
-- Dumped by pg_dump version 10.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgres; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON DATABASE postgres IS 'default administrative connection database';


--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


--
-- PostgreSQL database dump complete
--

```

**Comment by cuongtranx** [comment]
I'm not sure if you want to close this issue, ran into the same problem today.

If I'm `sh` into the container and run `pg_dump` and `pg_restore` inside the container, it works normally.

Running `docker exec` returns the same error  `pg_restore: implied data-only restore`

**Comment by tianon** [comment]
@cuongtranx can you please provide a _complete_ set of minimal example commands to reproduce the issue?

**Comment by cuongtranx** [comment]
Sure: 

`docker exec db-container pg_dump -Fc -U username -d dbname > ./dump`
`docker exec db-container pg_restore -Fc -v -U username -d dbname ./dump`

verbose returns the following message: `error pg_restore: implied data-only restore`

I've tried to create dump as text (without `-Fc` flag) and it seems to run normally. It's the custom format that's having issues.

**Comment by tianon** [comment]
That's not a complete example -- how does `/tmp/dump` get into the container for the second command?  Are you doing a bind mount?  Are those two separate containers with separate `/var/lib/postgresql/data` volumes?

**Comment by eburgueno** [comment]
@tianon We just hit this bug in one of our production setups using `postgres:9.3`. Here's a complete example attached reproducing the problem with `postgres:11`: [sql11.txt](https://github.com/docker-library/postgres/files/3155582/sql11.txt)

**Comment by eburgueno** [comment]
Further to my previous comment, redirecting `pg_dump`'s output while inside the container seems to work:

```
[root@myhost hello]$ docker exec -ti test bash
root@6a5d86a4e520:/# cd /mnt/
root@6a5d86a4e520:/mnt# pg_restore -l hello.dump 
pg_restore: [custom archiver] could not read from input file: end of file
root@6a5d86a4e520:/mnt# pg_dump -U postgres -Fc hello > hello.dump
root@6a5d86a4e520:/mnt# pg_restore -l hello.dump 
;
; Archive created at 2019-05-08 07:03:29 UTC
;     dbname: hello
;     TOC Entries: 15
;     Compression: -1
;     Dump Version: 1.13-0
;     Format: CUSTOM
;     Integer: 4 bytes
;     Offset: 8 bytes
;     Dumped from database version: 11.2 (Debian 11.2-1.pgdg90+1)
;     Dumped by pg_dump version: 11.2 (Debian 11.2-1.pgdg90+1)
;
;
; Selected TOC Entries:
;
196; 1259 16385 TABLE public city postgres
197; 1259 16391 TABLE public country postgres
198; 1259 16398 TABLE public countrylanguage postgres
2879; 0 16385 TABLE DATA public city postgres
2880; 0 16391 TABLE DATA public country postgres
2881; 0 16398 TABLE DATA public countrylanguage postgres
2751; 2606 16405 CONSTRAINT public city city_pkey postgres
2753; 2606 16407 CONSTRAINT public country country_pkey postgres
2755; 2606 16409 CONSTRAINT public countrylanguage countrylanguage_pkey postgres
2756; 2606 16410 FK CONSTRAINT public country country_capital_fkey postgres
2757; 2606 16415 FK CONSTRAINT public countrylanguage countrylanguage_countrycode_fkey postgres
```
So clearly the issue is redirecting `pg_dump`'s output from outside of the container. Perhaps because it's compressed binary data?

**Comment by eburgueno** [comment]
(Apologies. Please ignore previous, deleted comments)

I traced this back to using `docker exec -t` instead of just `docker exec`. The [TTY adds EOL characters](https://github.com/moby/moby/issues/8513#issuecomment-216191236) that corrupt the binary output.

Here's a reproducer: [sql.txt](https://github.com/docker-library/postgres/files/3156379/sql.txt)

**Comment by RafalSkolasinski** [comment]
Sorry for commenting in and old issue but this is the first thread that actually helped me solve a similar problem (I was invoking pg_dump using docker-compose exec).
In my case I had to add `-T` flag to disable the TTY. Just posting it here in case someone will have similar issues.

**Comment by elitan** [comment]
Don't know what's going on here but I had to NOT use `-t` in `docker exec` to get this to work. I had the following error: pg_restore: error: could not read from input file: end of file.

This is the command that worker for me:

`docker exec postgres_docker pg_dump -Fc -U postgres > db.dump`

**Comment by estan** [comment]
Sorry for necroposting, but @elitan I suspect that @RafalSkolasinski above was actually talking about `docker-compose exec`, not docker, since `-T` is the option for `docker-compose exec` to disable allocation of a pseudo-TTY, while in `docker exec` it is the absense of `-t`.
