### ISSUE TITLE
alpine variant missing /usr/share/zoneinfo

### ISSUE THREAD

**Issue by ptman** [docker-library/postgres#220]
LOG:  could not open directory "/usr/share/zoneinfo": No such file or directory

which results in:

    SELECT * FROM pg_timezone_names;
    ERROR:  could not open directory "/usr/share/zoneinfo": No such file or directory

which can be fixed with

    apk add tzdata

**Comment by ptman** [comment]
https://github.com/docker-library/postgres/pull/221

**Comment by tianon** [comment]
This was actually excluded intentionally (https://github.com/docker-library/postgres/blob/03f4064a045114f56fa445eb602339faaf79eeec/Dockerfile-alpine.template#L101-L102):
```dockerfile
# tzdata loading functionality is optional, and fails gracefully
#		tzdata \
```

Once it's added, it cannot be removed again (for users who don't need it), and it does add ~1.288 MB to the image size.

Something like the following should work to add it after the fact (which will then be imported during `docker-entrypoint.sh` and available at runtime):
```dockerfile
FROM postgres:9.6-alpine

RUN apk add --no-cache tzdata
```

**Comment by ptman** [comment]
Thanks for the explanation.

**Comment by lockie** [comment]
For anyone interested: there's an [unofficial repo](https://github.com/onjin/docker-alpine-postgres) of postgres in alpine with tzdata enabled out of the box.

**Comment by tianon** [comment]
Is the timezone data used commonly enough that we should reconsider including it by default?

Another really simple solution would be to mount in zoneinfo from the host, ie `-v /usr/share/zoneinfo:/usr/share/zoneinfo:ro`

**Comment by lockie** [comment]
> Is the timezone data used commonly enough

It sorta is. The Django documentation [suggests](https://docs.djangoproject.com/en/1.10/ref/databases/#optimizing-postgresql-s-configuration) that `timezone` should be set for Postgre for performance reasons.

**Comment by ptman** [comment]
It seems to add 1.288 MB to the image

**Comment by lockie** [comment]
@ptman it is around 1/50 of image size, which is not that terribly much.

**Comment by tianon** [comment]
Yeah, seems sane enough -- someone want to make a PR uncommenting the existing line and removing the comment it has? (probably adding a new one pointing to that Django documentation as a real-world example)
