### ISSUE TITLE
createdb and template

### ISSUE THREAD

**Issue by sda399** [docker-library/postgres#229]
hi,
I’m interested in passing an environment variable for options available in creating a database:
https://www.postgresql.org/docs/9.1/static/sql-createdatabase.html

actually my interest is in setting template, but other options would be nice too

**Comment by yosifkit** [comment]
We don't have any customization on the [`POSTGRES_DB`](https://github.com/docker-library/docs/tree/3c6490f656f0c7e9f7b42f8f7173e1eb27f4c795/postgres#postgres_db) argument, but you can add a custom sql or shell script to [`/docker-entrypoint-initdb.d/`](https://github.com/docker-library/docs/tree/3c6490f656f0c7e9f7b42f8f7173e1eb27f4c795/postgres#how-to-extend-this-image) and it will be executed just after first startup.

**Comment by tianon** [comment]
Indeed, using a short SQL script in `/docker-entrypoint-initdb.d/` is the recommended solution to this need. :+1:
