### ISSUE TITLE
include_relative does not work

### ISSUE THREAD

**Issue by ruslantalpa** [docker-library/postgres#231]
It would be nice to be able to have the files in the `docker-entrypoint-initdb.d` in any directory structure and have only a few files in the root of the directory, then use `\ir` inside them.
This [line](https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh#L106) prevents one from doing that 

```shell
*.sql)    echo "$0: running $f"; "${psql[@]}" < "$f"; echo ;;
```

If it's changed to
```shell
*.sql)    echo "$0: running $f"; "${psql[@]}" -f "$f"; echo ;;
```
then everything works.

I can submit a PR, i just need to know do you need all the entrypoints files for all versions modified or is there a process that the one at the top is copied everywhere?

**Comment by tianon** [comment]
Ahhh, I didn't realize `psql` had a `-f` option! :metal:

If you update `docker-entrypoint.sh` at the top-level, it will be copied to every version via `update.sh` -- if you open a PR which updates the top-level script and leave the box checked which gives maintainers push access to your branch, I'd be happy to run the `./update.sh` bit for you. :+1:

**Comment by ruslantalpa** [comment]
Done https://github.com/docker-library/postgres/pull/234
