### ISSUE TITLE
Correct way to update DDL with existing data

### ISSUE THREAD

**Issue by at88mph** [docker-library/postgres#233]
I'm running Docker 1.12.3 with the latest Postgres image (9.6.1) on Debian Linux 8.5.  All of my relevant SQL scrips are in ```/docker-entrypoint-initdb.d```, which is the cat's meow.  I love what you've done for easing Postgres deployments.

I have a few hundred thousand rows on mounted (persistent) volumes from my container.  If I have to add a column or add a table, what is the correct way to do that?

I could just modify the existing database, but the container itself shouldn't change, should it?  I should, instead, modify the startup scripts in ```/docker-entrypoint-initdb.d```, start a new container, and import the data, it seems to me.  But what if one had millions of rows?  That would be a big import.  Is there a 'correct' way?

Thanks again for this container image!

**Comment by tianon** [comment]
I'd suggest simply executing the new SQL file against your running instance directly via `psql`, ie something like this (adapted from the `via psql` example on https://hub.docker.com/_/postgres/):

`docker run --rm --link some-postgres:postgres postgres psql -h postgres -U your-user -d your-database < /path/to/your/new/file.sql`

(adjusting the value for `-U` and `-d` to suit your PostgreSQL instance)

**Comment by at88mph** [comment]
Thanks, @tianon.  If I do it that way, I'm modifying the container by modifying the Postgres instance inside it.  Perhaps there is no way around that, I'm not sure.

To clarify, I'm trying to avoid modifying the container in favour of updating my base image and spinning up a new container with the new DDL, but using the existing data from the old container.  Whether I can use the mounted data files is another question, too.

Thanks again.

**Comment by tianon** [comment]
@at88mph yeah -- that's modifying the container's mounted volume, not really the container itself, so updating your image to also include the new change is sane, but you don't necessarily need to redeploy with a fresh volume and recreate the entire database to do so :+1:

(I'd highly recommend keeping your mounted volume when you update the container -- as long as you're only updating between patch PostgreSQL versions like 9.6.1 to 9.6.2, this will be fine -- you **won't** want to use this to go between minors like 9.6 to 9.7).

**Comment by tianon** [comment]
Closing, given that this is resolved. :+1:
