### ISSUE TITLE
pg version prior 9.2

### ISSUE THREAD

**Issue by edoardoc** [docker-library/postgres#244]
Hello,

any way to have a docker image with postgres 8.4.x ?
thanks

**Comment by yosifkit** [comment]
We only support versions that are supported by upstream; see EOL dates [here](https://www.postgresql.org/support/versioning/).  But we do not delete old tags from the Docker Hub, so you can still `docker pull postgres:8.4`.

**Comment by tianon** [comment]
See also the Git history of this repo: https://github.com/docker-library/postgres/tree/a6d4922823aa8011513bb9c160c26c689301823a/8.4

**Comment by edoardoc** [comment]
thanks a lot for both answers
