### ISSUE TITLE
Problem with postgres:9.6.1 in a container

### ISSUE THREAD

**Issue by sdikby** [docker-library/postgres#248]
Hi,
i'm using postgres:9.6.1 as a service in a docker container and since a while it is always restarting. I have put some logs. The problem appeared when my disk ran on free space. Now as i freed some space on disk the problem still persists.(freed 15 GB from 1TB)
I hope someone could help.

######
DETAIL:  Could not write to file "pg_subtrans/000B" at offset 32768: No space left on device.
ERROR:  could not access status of transaction 0
DETAIL:  Could not write to file "pg_subtrans/000B" at offset 32768: No space left on device.
LOG:  using stale statistics instead of current ones because stats collector is not responding
PANIC:  could not write to file "pg_xlog/xlogtemp.46426": No space left on device
LOG:  server process (PID 46426) was terminated by signal 6: Aborted
DETAIL:  Failed process was running: autovacuum: ANALYZE public.task_instance
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
LOG:  could not write temporary statistics file "pg_stat/db_16384.tmp": No space left on device
LOG:  could not close temporary statistics file "pg_stat/db_0.tmp": No space left on device
LOG:  could not close temporary statistics file "pg_stat/global.tmp": No space left on device
LOG:  all server processes terminated; reinitializing
FATAL:  could not access status of transaction 0
DETAIL:  Could not write to file "pg_notify/0000" at offset 0: No space left on device.
LOG:  database system is shut down
LOG:  database system was interrupted; last known up at 2017-01-12 21:43:53 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 0/51344D68
LOG:  redo done at 0/52FFFF70
LOG:  last completed transaction was at log time 2017-01-13 11:50:25.736818+00
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  incomplete startup packet
LOG:  unexpected EOF on client connection with an open transaction
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  database system was interrupted; last known up at 2017-01-16 07:45:51 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 0/53000058
LOG:  invalid record length at 0/530016F8: wanted 24, got 0
LOG:  redo done at 0/53000058
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2017-01-16 07:51:55 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2017-01-16 08:11:37 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2017-01-16 08:31:22 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2017-01-16 09:15:58 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2017-01-16 09:27:04 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  unexpected EOF on client connection with an open transaction
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  database system was interrupted; last known up at 2017-01-16 09:31:01 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  invalid record length at 0/53001998: wanted 24, got 0
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  database system was interrupted; last known up at 2017-01-16 09:33:05 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  invalid record length at 0/53001A08: wanted 24, got 0
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
######

**Comment by yosifkit** [comment]
My guess is that Postgres had only written partial state to disk when it became full and is in an unrecoverable state. I would recommend restoring it from a backup.  If you have none, then you may try your luck with the [Postgres community](https://www.postgresql.org/support/) via their mailing lists or IRC.  This is unfortunately not the place for general debugging of issues while running Postgres, but issues specific to how Postgres is "containerized".
