### ISSUE TITLE
Add a README file with content from the Docker Hub page

### ISSUE THREAD

**Issue by JonathanPorta** [docker-library/postgres#25]
The discussion in the comments, especially those with examples, on the Docker Hub Registry page for this repository was super helpful to me. It would be great if a README could be added that contained some of the FAQs and/or comments explaining some of the ways one can customize this image.

I would gladly contribute if someone smarter than me wanted to give it a first pass. ;)

**Comment by yosifkit** [comment]
I'm not sure what needs to be added to the [docs](https://github.com/docker-library/docs/blob/master/postgres/content.md). Closing for now. Feel free to add useful information there.
