### ISSUE TITLE
uid collision on Centos 7 host

### ISSUE THREAD

**Issue by dangogh** [docker-library/postgres#251]
The hard-coded uid=999 value conflicts with the systemd-bus-proxy user on CentOS 7
```
$ grep :999: /etc/passwd
systemd-bus-proxy:x:999:997:systemd Bus Proxy:/:/sbin/nologin
```

This makes it difficult to use a volume mapped to a host directory as it is owned by the above user.   Is there a recommended way to handle this?

**Comment by tianon** [comment]
One solution that will work the most generically is to look into Docker's User Namespaces support to see if it's a fit for your use case (which would allow you to remap the user directly as desired), but barring that, you'll likely be interested in #253. :+1:

**Comment by dangogh** [comment]
great responsiveness..   thanks!   👍

**Comment by beauremus** [comment]
I don't fully understand the solution. @dangogh what did you end up doing?

**Comment by dangogh** [comment]
I ended up in the entrypoint script adding this bash function which sets the owner of the subdir I created to be the same as the volume I had mounted:
```
setowner() {
    own=$(stat -c '%u:%g' $1)
    shift
    [[ -n $@ ]] && chown -R ${own} "$@"
}
...
setowner /myvolume /myvolume/newsubdir
```

**Comment by beauremus** [comment]
Alright. Thanks for the response. Not happy with the hacky solution.

**Comment by dangogh** [comment]
neither am I -- one hack on top of another,  but sometimes it's what you can do
