### ISSUE TITLE
9.6.1: Fails to execute docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by maul-esel** [docker-library/postgres#254]
There seems to be a bug in the latest docker images. Specifically it seems to be introduced by commit 3706d4c4. See [here](https://github.com/docker-library/postgres/commit/3706d4c4562c284ed070286b9fd516151167a40c#diff-4c01fb1160b4ab65f6ff0269906298f3R40): if `(id -u) == 0`, postgres is executed without first importing the scripts from `/docker-entrypoint-initdb.d`. This breaks existing `Dockerfile`s.

**Comment by yosifkit** [comment]
Are you talking about the change that `initdb.d` scripts are no longer run as root?  I had commented about that on the PR introducing this change: https://github.com/docker-library/postgres/pull/253#issuecomment-273933445.

**Comment by maul-esel** [comment]
So the solution would be to pass `--user` to `docker run`? Since this seems intentional, and I personally am no longer affected, I'll close this issue.
