### ISSUE TITLE
/usr/local/include removal

### ISSUE THREAD

**Issue by sbollain** [docker-library/postgres#257]
In the dockerfile includes are removed:
rm -rf /usr/local/include/*

That removal does not allow to install extensions that need to be recompiled like pg_partman
My suggestion is not to remove the include files.
After commenting that line, pg_partman can be installed

**Comment by kurlzor** [comment]
This already has been fixed in #247.

**Comment by sbollain** [comment]
You are right. I did not realize it was alreday fixed. It works perfectly.
Thanks
