### ISSUE TITLE
Volume in dockerfile work against volume in docker-compose

### ISSUE THREAD

**Issue by gsantonja** [docker-library/postgres#265]
line 61 in dockerfile of postgresql 9.6 : > VOLUME /var/lib/postgresql/data 
this line alvways create an anonymous volume when using dockercompose instead of using
volume description 
example in docker compose
Volumes:
  - ./db_data/postgresql:/var/lib/postgresql

this line create a "data" directory but still empty and  a new volume 

you  need to suppress this line for working with docker-compose and download dockerfile and docker-entrypoint.sh in your working directory

**Comment by kurlzor** [comment]
> example in docker compose
> Volumes:
> - ./db_data/postgresql:/var/lib/postgresql

As mentionned [here](https://github.com/docker-library/postgres/issues/103#issuecomment-167631548), `/var/lib/postgresql` should be `/var/lib/postgresql/data`.

**Comment by yosifkit** [comment]
Closing old issue; seems solved.
