### ISSUE TITLE
debian and alpine postgres image not interchangeable

### ISSUE THREAD

**Issue by SISheogorath** [docker-library/postgres#276]
Had a very interesting debugging session a few minutes ago.

Ah while back I simply replaced the "big" `postgres:9.5` image with the lightweight `postgres:9.5-alpine` image and at first everything looked fine. Until it came to some selects which suddenly stop working.

Which tells me that there is some kind of difference in the default configuration between the normal and the alpine version. Maybe that's normal but actually I didn't expect that as everything else worked fine. (no warning on startup and in general everything seemed fine).

I filed all details of my issue hunt at https://github.com/hackmdio/hackmd/issues/430#issuecomment-294941451

And it took me some time to figure it out. So I hope it's helpful to hunt down the real issue that is located underneath the whole thing. For me the switch back fixed it for now but it would be nice to fix it in general in future.

**Comment by tianon** [comment]
This sounds similar to https://github.com/docker-library/postgres/issues/273 :disappointed:

I wonder if musl is doing something odd?  Can it be reproduced with the Alpine package (if it can be, we'll have to punt to upstream, but otherwise we can look at what they're doing that we aren't :smile:)?

**Comment by jayunit100** [comment]
Is it generally a requirement that these are , always , interchangeable ?

**Comment by tianon** [comment]
That's something we strive to accomplish, but it isn't always possible, so no, it's not generally a _requirement_.

I would recommend any user who's looking to switch from a Debian variant to an Alpine variant of an image carefully review the two images and the differences between them.  Often times the Alpine image is less-featured out-of-the-box as a core feature, since that allows for a much smaller base image (and tighter control on exactly what gets included).

**Comment by wglambert** [comment]
Going to close since the question is answered sufficiently, and the note in the [docs](https://github.com/docker-library/docs/tree/master/postgres#postgresalpine) mentions this as well
>The main caveat to note is that it does use [musl libc](http://www.musl-libc.org/) instead of [glibc and friends](http://www.etalabs.net/compare_libcs.html), so certain software might run into issues depending on the depth of their libc requirements.
