### ISSUE TITLE
Proper way to create  folders/tablespaces

### ISSUE THREAD

**Issue by muhahacz** [docker-library/postgres#279]
Very simple dockerfile.. 
```
FROM postgres:9.6
RUN bash -c 'mkdir -pv /var/lib/postgresql/data/{tablespace1,tablespace2,tablespace3}'
...
COPY db-init.sql /docker-entrypoint.d/
```
Its not possible to do it, because /var/lib/postgresql/ needs to be empty for DB/container initialization / .
So is there proper way to setup tablespaces?

db-init.sql
```
CREATE TABLESPACE dbspace LOCATION '/data/tablespace1';
CREATE TABLESPACE dbspace LOCATION '/data/tablespace2';
CREATE TABLESPACE dbspace LOCATION '/data/tablespace3';
```

**Comment by yosifkit** [comment]
You can move your `RUN` to a script in `/docker-entrypoint.d/`. As long as it is alphabetically before your `.sql` file it'll run first.

```bash
#!/bin/bash
set -e

mkdir -pv /var/lib/postgresql/data/{tablespace1,tablespace2,tablespace3}

# you could even move your sql into this file as well
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "
	CREATE TABLESPACE dbspace LOCATION '/data/tablespace1';
	CREATE TABLESPACE dbspace LOCATION '/data/tablespace2';
	CREATE TABLESPACE dbspace LOCATION '/data/tablespace3';
"
```

**Comment by muhahacz** [comment]
Is this really good aproach?

`CREATE TABLESPACE cannot be executed from a function or multi-command string`

Seems, that 
`psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f db-init.sql` 
works.

But i would like to have it all in one file, whole provisioning.
Thanks

**Comment by yosifkit** [comment]
Ah, maybe just split my suggestion into 3 `psql ... -c "CREATE TABLESPACE..."` line

**Comment by tianon** [comment]
Or a `for` loop:
```bash
#!/bin/bash
set -e

for tablespace in tablespace1 tablespace2 tablespace3; do
	mkdir -pv "/var/lib/postgresql/data/$tablespace"
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE TABLESPACE dbspace LOCATION '/data/$tablespace'"
done
```

**Comment by yosifkit** [comment]
Closing old issue; seems solved.
