### ISSUE TITLE
Add a Environment variable to blind the container to 0.0.0.0

### ISSUE THREAD

**Issue by vijayparashar12** [docker-library/postgres#287]
currently, for mac users to access container on host it should bind to 0.0.0.0 address, this is due to way networking is implemented in [Docker for Mac](https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds)

**Comment by yosifkit** [comment]
We already fix that in the Dockerfile: https://github.com/docker-library/postgres/blob/e7222bf98572eec2a7b8875c13825015a163091c/9.6/Dockerfile#L55, which makes it `listen = '*'`

**Comment by vijayparashar12** [comment]
I will test it and close the issue, thanks for quick reply.

**Comment by vijayparashar12** [comment]
tested and verified.
