### ISSUE TITLE
build behind proxy fails because URI to keyserver is wrong 

### ISSUE THREAD

**Issue by c031917** [docker-library/postgres#288]
gpg keyserver URI must be 
hkp://ha.pool.sks-keyservers.net:80 
instead 
ha.pool.sks-keyservers.net
in order to work behind Corporate proxies.

So at the two places in the Dockerfile where gpg keys are pulled it must read:
..
	&& gpg --keyserver-options --keyserver hkp://ha.pool.sks-keyservers.net:80
..

**Comment by yosifkit** [comment]
duplicate #262
