### ISSUE TITLE
Question: What is the best way to get PLV8 in alpine image?

### ISSUE THREAD

**Issue by owais** [docker-library/postgres#290]
It seems that postgresql-contrib does not ship PLV8 extension. Does Alpine have a package for PLV8 or is it best to manually build it at the moment?

**Comment by tianon** [comment]
The `postgres:X.Y-alpine` images compile PostgreSQL from source (https://github.com/docker-library/postgres/blob/e7222bf98572eec2a7b8875c13825015a163091c/Dockerfile-alpine.template#L69-L112), so yes, any extensions necessary should also likely be compiled from source. :+1:

**Comment by deinspanjer** [comment]
There is also the image clkao/postgres-plv8 which I'm very happy with.

**Comment by JRileyH** [comment]
> There is also the image clkao/postgres-plv8 which I'm very happy with.

Which is expressly not alpine.

**Comment by alexeyfadeev** [comment]
@owais @JRileyH 
Look at [our images](https://hub.docker.com/r/sibedge/postgres-plv8),
There are alpine-based versions as well.
