### ISSUE TITLE
Document which variables are available

### ISSUE THREAD

**Issue by bmillemathias** [docker-library/postgres#292]
I'm new to docker and it was difficult how to set a user / db at the start of the docker, after reading on various sources (forums, ...), I've found some variables were available (to now I found `POSTGRES_DB`, `POSTGRES_USER`, `POSTGRES_PASSWORD` but there are perhaps others).

It could be easier to user to document the variables in the `README.md` file. If you provide them I can make a patch.

Regards

**Comment by ImreSamu** [comment]
@bmillemathias : 
according to the README 
* _"See the Docker Hub page for the full readme on how to use this Docker image and for information regarding contributing and issues. .... "_
  * https://hub.docker.com/_/postgres/
  * https://github.com/docker-library/docs/tree/master/postgres

**Comment by yosifkit** [comment]
They should all be on the Docker Hub ([src](https://github.com/docker-library/docs/tree/27a8c10dacfe09e864e79d90eab2f2f109bf4152/postgres#environment-variables)). If there are some missing PRs are welcome.

This repo is just for the build artifacts (`dockerfile`s and related scripts). The readme here does link to the full docs:
> The full readme is generated over in [docker-library/docs](https://github.com/docker-library/docs), specifically in [docker-library/docs/postgres](https://github.com/docker-library/docs/tree/master/postgres).
