### ISSUE TITLE
How to set pipe-user-pages-soft

### ISSUE THREAD

**Issue by whitas** [docker-library/postgres#294]
Hello 

I'm trying to use wal-e for backing up postgresql running in this docker. Unfortunetly this tool doesn't work because of pipe-user-pages-soft limit set in /proc/sys/fs/pipe-user-pages-soft.

I've try to change this value using:

`echo 0 > /proc/sys/fs/pipe-user-pages-soft`

but unfortunately 

`bash: /proc/sys/fs/pipe-user-pages-soft: Read-only file system`

I've tried also 

`sysctl fs.pipe-user-pages-soft`  but without success.

Any suggestions, please ?

**Comment by yosifkit** [comment]
There is a list of namespaced kernel parameters (sysctls) in the [docker docs](https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime), but `fs.pipe-user-pages-soft` is not there; so it will have to be set on the docker host.

**Comment by whitas** [comment]
@yosifkit Thank you for pointing me the right direction.
