### ISSUE TITLE
Postgis not installed

### ISSUE THREAD

**Issue by txomon** [docker-library/postgres#30]
Hi, I am coming from https://github.com/orchardup/docker-postgresql, and seems like it's not full replacement, as postgis isn't being installed. Would it be possible to get postgis also installed?

**Comment by tisdall** [comment]
happy anniversary?  :)

I got here while trying to look for a way to get postgis working in the container.

I'm assuming the way to do it is with the following `Dockerfile`:
```
FROM postgres
RUN apt-get update && apt-get install postgis
```

(I'm asking because I only started working with Docker yesterday)

**Comment by jberkus** [comment]
yeah, except that's not the package name.  Look up the package name for the version of Postgres you're using.

**Comment by tisdall** [comment]
There is a package called `postgis`, but maybe it's a dummy package that points to one of the `postgresql-9.X-postgis-2.X` packages.

**Comment by tisdall** [comment]
oh..  `postgis` seems to pull in the lastest version of postgres despite the version of the image.

**Comment by tisdall** [comment]
So for 9.3 I used the following and it seems to be working fine:
```
FROM postgres:9.3
RUN apt-get update && apt-get -y install postgresql-9.3-postgis-2.1
```

**Comment by md5** [comment]
@tisdall As I commented earlier, I've got a working `postgis` image on Docker Hub at `mdillon/postgis` (among others I'm sure). Here's my `Dockerfile` for Postgres 9.3 with PostGIS 2.1: https://github.com/appropriate/docker-postgis/tree/master/9.3-2.1

**Comment by tisdall** [comment]
@md5 - I posted to hopefully encourage @yosifkit to implement what he suggested so there'd be postgis versions of each postgres image.  However, I really have no idea how much demand there is for that other than myself wanting it.

**Comment by md5** [comment]
I hadn't noticed that comment in my latest read-through of this issue, but
I'm surprised @yosifkit suggested that. PostGIS doesn't seem akin to the
“onbuild" situation to me. It seems like it should be a separate image.

**Comment by md5** [comment]
As for demand, it's non-negligible, but not huge. My `mdillon/postgis` image has 30k+ pulls.

**Comment by tianon** [comment]
I'm definitely +1 on @md5's postgis image, and on keeping it separate.

**Comment by tisdall** [comment]
Okay, I switched over to using `mdillon/postgis`.  Thanks @md5 !

**Comment by md5** [comment]
@tisdall :metal:
