### ISSUE TITLE
can support compiling source code installation PostgreSQL in Debian?

### ISSUE THREAD

**Issue by creamjiang** [docker-library/postgres#301]
can support compiling source code installation PostgreSQL in Debian?

**Comment by tianon** [comment]
Can you elaborate on what value doing so would provide?

**Comment by creamjiang** [comment]
Can be compatible with other projects, such as https://github.com/paunin/postgres-docker-cluster

**Comment by creamjiang** [comment]
Can help me fix it? Support compiling source code installation PostgreSQL in Debian? Because I need to modify the value of PostgreSQL NAMEDATALEN.
At the same time can be integrated https://github.com/paunin/postgres-docker-cluster

**Comment by colearendt** [comment]
I have interest in this as well.  Specifically, it is useful for me if I want to enable build-time configuration changes (i.e. Kerberos for a CI setup).  I could also see how it might be useful if you want to enable other languages, etc.  I'm trying to find a nice way to use these images in this context, but it is proving tricky without forking the repo and building from source instead of with `apt`.

**Comment by yosifkit** [comment]
As the apt repos are provided by postgresql.org, we'd rather not stray from their supported releases.

Closing old issue.

**Comment by colearendt** [comment]
Just for reference in case someone else needs / wants to build from source without discarding this (very good) image. I decided to build `FROM` this image without using the actual install itself. This very well may be insane / non-docker-like, but it worked for my case and gave me much of the _tricky configuration_ for free! Maybe someone will come along and correct my approach - I welcome it 😄 

```Dockerfile
FROM postgres:9.6
# use a different version because I do not trust myself

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
	apt-get install -y \
	apt-transport-https \
	wget && \
	apt-get dist-upgrade -y

# ...

# remove previous postgres install
RUN apt-get remove -y postgresql-$PG_MAJOR postgresql-client-$PG_MAJOR && apt-get autoremove -y

ENV PG_MAJOR=10.1
ENV PG_VERSION=10.1.0
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/${PG_MAJOR}/bin
# build postgres from source
RUN apt-get install -y \
	gcc \
	make \
	libreadline-dev \
	zlib1g-dev \
	libgss-dev \
	libkrb5-dev && \
	wget https://ftp.postgresql.org/pub/source/v${PG_MAJOR}/postgresql-${PG_MAJOR}.tar.gz && \
	gunzip postgresql-${PG_MAJOR}.tar.gz && \
	tar xf postgresql-${PG_MAJOR}.tar && \
	cd postgresql-${PG_MAJOR} && \
	./configure \
	  --with-gssapi \
	  --prefix=/usr/lib/postgresql/${PG_MAJOR} \
	  && \
	make && \
	make install

# ...
```
