### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by rap2hpoutre** [docker-library/postgres#302]
How can I change the default port (5432)? It seems the port is hardcoded.

**Comment by yosifkit** [comment]
This should provide some solutions: https://github.com/docker-library/postgres/issues/196#issuecomment-310209118

**Comment by yosifkit** [comment]
Closing as solved.

**Comment by yami12376** [comment]
But i want it to run inside on different ports. For example 5432 and 5433. Cause when they are running inside on the same port, the cache from Jira/Confluence is going nuts.
