### ISSUE TITLE
FROM debian:stretch (new debian stable) 

### ISSUE THREAD

**Issue by arthurlogilab** [docker-library/postgres#307]
Stretch is the new debian stable. Any plans to use FROM debian:stretch in the debian based images ? 

https://wiki.postgresql.org/wiki/Apt has a stretch distribution.

**Comment by tianon** [comment]
We've updated to `stretch` for `postgres:10`, but updating the older versions has potential for breaking existing users (if they're building on top via a `Dockerfile` which is `FROM postgres:9.6`, for example), so we're wary of doing the upgrade en-masse.

**Comment by wglambert** [comment]
Closed by https://github.com/docker-library/postgres/pull/437
