### ISSUE TITLE
Recent versions seems to have broken auth when POSTGRES_PASSWORD is set

### ISSUE THREAD

**Issue by dpnova** [docker-library/postgres#308]
I've tried 9.6 and 9.5 and alpine variants too.

Getting rid of the POSTGRES_PASSWORD fixes it so I'm generally ok, but this could trip other people up too... looks like it might be the issue at: https://github.com/MagicStack/asyncpg/issues/158

compose:

```
        postgres_sx:
                image: postgres
                environment:
                  - POSTGRES_PASSWORD=postgres
```

```
postgres_sx_1  | FATAL:  password authentication failed for user "postgres"
postgres_sx_1  | DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_sx_1  | FATAL:  password authentication failed for user "postgres"
postgres_sx_1  | DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_sx_1  | FATAL:  password authentication failed for user "postgres"
postgres_sx_1  | DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
services_sx_1  | { error: password authentication failed for user "postgres"
services_sx_1  |     at Connection.parseE (/app/services/sx/node_modules/pg-promise/node_modules/pg/lib/connection.js:539:11)
services_sx_1  |     at Connection.parseMessage (/app/services/sx/node_modules/pg-promise/node_modules/pg/lib/connection.js:366:17)
services_sx_1  |     at Socket.<anonymous> (/app/services/sx/node_modules/pg-promise/node_modules/pg/lib/connection.js:105:22)
services_sx_1  |     at emitOne (events.js:115:13)
services_sx_1  |     at Socket.emit (events.js:210:7)
services_sx_1  |     at addChunk (_stream_readable.js:250:12)
services_sx_1  |     at readableAddChunk (_stream_readable.js:237:11)
services_sx_1  |     at Socket.Readable.push (_stream_readable.js:195:10)
services_sx_1  |     at TCP.onread (net.js:586:20)
```

**Comment by yosifkit** [comment]
Could be related to https://github.com/docker-library/postgres/issues/203#issuecomment-255200501.

**Comment by vitaly-t** [comment]
@dpnova which version of pg-promise are you using? Probably on of 5.x? Try 6.x, and if the problem is still there, it means the issue isn't with the driver, but elsewhere.

**Comment by dpnova** [comment]
@yosifkit I had removed the volumes between each test

@vitaly-t it seems the libs I'm using pull in 5.x. I can try 6.. thanks.


In general it just seems odd that this started happening after I removed my local postgres images and pulled in the same postgres version but latest dockerhub image..

**Comment by vitaly-t** [comment]
> In general it just seems odd that this started happening after I removed my local postgres images and pulled in the same postgres version but latest dockerhub image..

In this case it is very unlikely that swapping the driver will make any difference. But you can still try.

**Comment by yosifkit** [comment]
The Postgres image itself works fine:

```console
$ docker pull postgres:9.6
...
Digest: sha256:e92fe21f695d27be7050284229a1c8c63ac10d88cba58d779c243566e125aa34
$ docker run -d -e POSTGRES_PASSWORD=12345 --name=posty postgres:9.6
$ docker logs --tail=6 posty
PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2017-07-07 20:32:23 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
$ docker run -it --rm --link posty:postgres postgres:9.6 psql -h postgres -U postgres
Password for user postgres: 
psql (9.6.3)
Type "help" for help.

postgres=# 
```

Can you connect to your postgres container via `psql`?

**Comment by dpnova** [comment]
It works fine without POSTGRES_PASSWORD set in docker compose env. For some
reason that's when it breaks. I'll try repro with regular docker.

**Comment by lelit** [comment]
FYI, I distilled [this](https://github.com/lelit/asyncpg-issue158) minimalistic recipe that exhibits the problem, but still using docker compose. @dpnova, were you able to determine if the same happens with plain docker or not?

**Comment by dpnova** [comment]
I've only seen this in docker. Sorry travelling overseas atm

pon, 24. jul 2017. 10.05 PM Emanuele Gaifas <notifications@github.com> је
написао/ла:

**Comment by dpnova** [comment]
Sorry I mean in docker compose.

uto, 25. jul 2017. 08.45 AM David P. Novakovic <dpn@dpn.name> је написао/ла:

**Comment by lelit** [comment]
I added an [alternative recipe](https://github.com/lelit/asyncpg-issue158/commit/e8ac54d1b8af37b799ffa9f7b362dcc8bf005c7b#diff-a5b4eb9289464ffc6a901dfb0a6f086e) using plain docker and got the [same problem](https://github.com/lelit/asyncpg-issue158#with-plain-docker).

**Comment by lelit** [comment]
The problem is still there in [PG10b3](https://github.com/lelit/asyncpg-issue158/commit/b7be6bb049084f33500bcb0e2d34fc9f69b60df4): asyncpg folks could not replicate the problem with a [local build](https://github.com/MagicStack/asyncpg/issues/158#issuecomment-317535926) of PostgreSQL.

**Comment by dpnova** [comment]
As noted over at https://github.com/MagicStack/asyncpg/issues/158 the problem appeared around the same time the changes were made to the image build. I reckon https://github.com/docker-library/postgres/commit/d8abce4e82533aa2673da9ba9a5a8385589ed693 looks suspect

**Comment by lelit** [comment]
FYI, current asyncpg master does not manifest the problem anymore.

**Comment by soosap** [comment]
Hi @lelit I tried to follow this discussion here but not sure how I can fix this.

I still immediately get this error when I set "POSTGRES_PASSWORD" using v10.1.
What is the current state on this? How to fix this?

```
2018-01-02 10:02:24.537 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2018-01-02 10:02:24.537 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2018-01-02 10:02:24.542 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2018-01-02 10:02:24.556 UTC [64] LOG:  database system was shut down at 2018-01-02 10:02:24 UTC
2018-01-02 10:02:24.561 UTC [1] LOG:  database system is ready to accept connections
2018-01-02 10:02:28.734 UTC [71] FATAL:  password authentication failed for user "prasath"
2018-01-02 10:02:28.734 UTC [71] DETAIL:  Password does not match for user "prasath".
	Connection matched pg_hba.conf line 95: "host all all all md5"
2018-01-02 10:02:28.736 UTC [72] FATAL:  password authentication failed for user "prasath"
2018-01-02 10:02:28.736 UTC [72] DETAIL:  Password does not match for user "prasath".
```

**Comment by lelit** [comment]
Sorry @soosap, I'm afraid I can be of little help here, because I shifted focus on other things and the transition to pg10 did not actually happen. As said, an asyncpg upgrade did fix my test suites.

Anyway, maybe you can adapt my https://github.com/lelit/asyncpg-issue158 to your use case?

**Comment by soosap** [comment]
Hi thanks for getting back on this. I found a workaround - when I use POSTGRES_PASSWORD_FILE and mount the password as a file to /run/secrets (effectively making use of Docker Secrets) then I don't get this error.

**Comment by soosap** [comment]
Hi just a quick update! I was mistaken that using POSTGRES_PASSWORD_FILE environment variable instead of POSTGRES_PASSWORD was a valid workaround. As you have mentioned the transition to pg10 did not happen. I am going to stick with `v9.6.7` for now.

**Comment by myhro** [comment]
I was facing the same issue when deploying the PostgreSQL image on Kubernetes. The problem was really subtle, but was caused by **a trailing newline character on my password environment variable**. That's why when creating base64 secrets using the command line, [one should always use][1] `echo -n`:

    $ echo 123 | base64
    MTIzCg==
    $ echo -n 123 | base64
    MTIz

What makes this hard to spot, is that there's no visible difference when inspecting the container's environment variables. Here's an example using the password `hunter2` with a trailing `\n`:

    root@test-postgres-5b8884c9db-vgwcq:/# env | grep POSTGRES_PASSWORD
    POSTGRES_PASSWORD=hunter2
    root@test-postgres-5b8884c9db-vgwcq:/# PGPASSWORD=hunter2 psql -U myapp -h test-postgres
    psql: FATAL:  password authentication failed for user "myapp"
    root@test-postgres-5b8884c9db-vgwcq:/# [[ "$POSTGRES_PASSWORD" = "hunter2" ]]
    root@test-postgres-5b8884c9db-vgwcq:/# echo $?
    1
    root@test-postgres-5b8884c9db-vgwcq:/# echo "$POSTGRES_PASSWORD" | md5sum
    1235d50a49d1d58d7af22ad118827eac  -
    root@test-postgres-5b8884c9db-vgwcq:/# echo "hunter2" | md5sum
    6a0f0731d84afa4082031e3a72354991  -

And without it:

    root@test-postgres-5b8884c9db-zs7m6:/# env | grep POSTGRES_PASSWORD
    POSTGRES_PASSWORD=hunter2
    root@test-postgres-5b8884c9db-zs7m6:/# PGPASSWORD=hunter2 psql -U myapp -h test-postgres
    psql (9.6.8)
    Type "help" for help.

    myapp=# \q
    root@test-postgres-5b8884c9db-zs7m6:/# [[ "$POSTGRES_PASSWORD" = "hunter2" ]]
    root@test-postgres-5b8884c9db-zs7m6:/# echo $?
    0
    root@test-postgres-5b8884c9db-zs7m6:/# echo "$POSTGRES_PASSWORD" | md5sum
    6a0f0731d84afa4082031e3a72354991  -
    root@test-postgres-5b8884c9db-zs7m6:/# echo "hunter2" | md5sum
    6a0f0731d84afa4082031e3a72354991  -

The fact that the PostgreSQL server in this image allows local connections without a password makes the debug of this issue even more confusing:

    root@test-postgres-5b8884c9db-vgwcq:/# psql -U myapp
    psql (9.6.8)
    Type "help" for help.

    myapp=# \q

That's why testing the connection using `psql` without `-h` isn't enough.


[1]: https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-using-kubectl-create-secret

**Comment by tianon** [comment]
Since the original issue here appears solved, I'm going to close. :+1:
