### ISSUE TITLE
Default pg_hba is extremely insecure

### ISSUE THREAD

**Issue by iTech-Developer** [docker-library/postgres#31]
It might be more reasonable to replace the following line in pg_hba
`echo 'host all all 0.0.0.0/0 trust';`
with
`echo 'host all all 0.0.0.0/0 md5';`

Because the current configuration simply enables anyone in the world to connect to the database with no authentication whatsoever, which is really a very serious security problem because it is very likely that someone might leave the default setting of the image!

Quoting PostgreSQL documentation

> trust
> Allow the connection unconditionally. This method allows anyone that can connect to the PostgreSQL database server to login as any PostgreSQL user they wish, without the need for a password or any other authentication

**Comment by Starefossen** [comment]
Yes, this change is plain out stupid. The security model of how Docker links containers together provides all the necessary protection.

**Comment by yosifkit** [comment]
@Starefossen actually links provide zero security unless you are actually running the docker daemon with `--icc=false`; with the default being true any container can talk to any other container on any port that they respond on by just using an IP address.  Yes there is the "security" of the containers living behind the docker bridge NAT, but that might not always be the case especially with IPv6 coming in docker 1.5.

I'll admit that we might have gone too tight on the security that people were initially complaining was "too insecure" here.  The original thought is that you are using something like `fig` to run your apps and so having a separate database per "service" seemed natural and the docker way, but is seems we ought to be a little more flexible for those users that desire to have their monolithic database for all their services to connect to. We are open to PR's, so make a suggestion.

**Comment by joantune** [comment]
This kinda sucks if you want multiple databases and users for one postgresql container which seems to me as a good way to do things (isn't it?) so now if you want any kind of user isolation from the apps, you should provide your pg_hba.conf because only the ```POSTGRES_USER``` has access..
