### ISSUE TITLE
Psql -> cyrillic characters, CTRL+R, ...

### ISSUE THREAD

**Issue by ogolovanov** [docker-library/postgres#310]
Hello.

If i run psql command via 
**docker run --rm -ti postgres:9.6 psql '-hxxx.xxx.xxx.xxx' 'database' 'login'**
i can not enter russian characters and i can not search through history via CTRL+R combination.

But if i build following image and run the same command - i will be able to enter russian characters and use CTRL+R.

I really can't get how can that be possible.
Why your image does not allow that?
Thanks.

> FROM debian:jessie
> RUN apt-get update && apt-get install -y locales locales-all postgresql-client
> ENV LANG en_US.UTF-8
>

**Comment by tianon** [comment]
We set `LANG` appropriately by default (https://github.com/docker-library/postgres/blob/0f55625d25faf7ad6adf821e91612d7df53d9a11/Dockerfile-debian.template#L31-L34), so I'm not sure why this occurs with our image and not the simple version you've created. :confused:

**Comment by ogolovanov** [comment]
Hello.

Problem is here: 
"ENV PATH /usr/lib/postgresql/$PG_MAJOR/bin:$PATH"

So, psql command from /usr/lib/postgresql/9.6/bin/psql used instead of /usr/bin/psql.
The second one works correctly, the first - not.

**Comment by MrYoda** [comment]
Have the same issue with command (on running container based on `postgres:9.5-alpine`):
`docker exec -it --user postgres postgres-test psql`
I can not type or paste any non-ascii symbol. How can I fix it?

**Comment by tianon** [comment]
Sorry, I think this got lost at some point. :disappointed:

I've opened https://github.com/docker-library/postgres/pull/355, which should hopefully fix this. :+1:
