### ISSUE TITLE
/usr/local/bin/docker-entrypoint.sh: line 145: exec: .: cannot execute: Is a directory

### ISSUE THREAD

**Issue by MarcArbour** [docker-library/postgres#312]
Hello,

I am using this repo: https://github.com/docker-library/postgres/tree/d8abce4e82533aa2673da9ba9a5a8385589ed693/9.6/alpine to build myself a custom container.

My 2 local files are an identical copy of the above git repo and these are the only 2 files I have for now. No Windows characters in the files. It builds fine and at runtime, it outputs the following:

`user@dock:~/docker/postgres$ docker run  -it -v pgdata:/var/lib/postgresql/data postgres:3 .
/usr/local/bin/docker-entrypoint.sh: line 145: exec: .: cannot execute: Is a directory
`
Have I done something wrong? The official pull from 9.6.3-alpine works fine, but I need additions to it.

Any pointer or nudge in the right direction would be appreciated.

Regards.

Marc.

**Comment by yosifkit** [comment]
Remove that `.` at the end of your `docker run`. :wink: (otherwise `.` becomes the arguments to `docker-entrypoint.sh` and it tries to `exec .`)

**Comment by MarcArbour** [comment]
Ho WOW!

Thank you for a fast response. And also thank you for a marvelous container to build upon.

Have a great day.

Marc.
