### ISSUE TITLE
Any chance of seeing an ARM64v8 docker image soon?

### ISSUE THREAD

**Issue by gregorkistler** [docker-library/postgres#315]
Hi,

title says it all. After deprecation of the aarch64 organization in Docker Hub I wonder if we will see docker images for Postgres (preferable Alpine based) in the arm64v8 organization soon?
Currently still using the old ones from aarch64.

Thank you.

**Comment by yosifkit** [comment]
As evidenced by the image tags on the [aarch64 repo](https://hub.docker.com/r/aarch64/postgres/tags/) that we tested on, Postgres upstream does not release Debian builds for arm64v8, so we won't have a Debian based image.  We will do an Alpine based one as soon as the Alpine image officially supports multi-architecture (https://github.com/gliderlabs/docker-alpine/issues/304).  The previous images were mostly just @tianon getting the infrastructure in place to support officially building images on multiple arches.

**Comment by gregorkistler** [comment]
Alright thank you. I was already regularly checking Docker Hub as well as @tianon´s Jenkins builds and wondered why I still see no image yet.
So it´s basically just a matter of time - will watch the mentioned issue meanwhile. Feel free to close this one here, or leave it open until the Alpine Postgres arm64v8 were shipped.

**Comment by gregorkistler** [comment]
Will close this one now as we have some [arm64v8 alpine based Postgres images](https://hub.docker.com/r/arm64v8/postgres/tags/) since a few weeks.
Thanks so much.
