### ISSUE TITLE
Postgres 9.4-alphine is always restarting on executing large sql file via spring boot ScriptUtils

### ISSUE THREAD

**Issue by daggerok** [docker-library/postgres#322]
If I running postgres in Docker (alphine version)

```bash
docker run -d --rm --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres postgres:9.4-alpine
```

then org.springframework.jdbc.datasource.init.ScriptUtils is failing on execution large SQL file (~50Mb, 200000+ lines)

but If I'm installing postgress locally, then all executing very quickly with no errors:

```bash
2017-08-08 02:10:21.910  INFO 8816 --- [  restartedMain] o.s.jdbc.datasource.init.ScriptUtils     : Executed SQL script from class path resource [db/testdata.sql] in 32104 ms
```

are there any limitations?
maybe we can increase postgres memory configurations somehow or something like that?

**Comment by tianon** [comment]
Sounds like you're probably running out of RAM or some other similar
resource -- anything useful in the logs of the _database_ container when it
restarts?

**Comment by daggerok** [comment]
Thanks for answer.
Increased memory for Docker up to 5G, works fine.
I will close that issue.
