### ISSUE TITLE
Confirm a container is ready to run after init

### ISSUE THREAD

**Issue by bizmate** [docker-library/postgres#326]
Hi folks,
the innit process is great to just do exactly what it promises and it runs only the first time the data created as the rule is to check if a file was already created before running init to make sure it is ok

ie https://github.com/docker-library/postgres/blob/bef7a7e02643bb0f104ba346395d3cdb78db1480/9.6/docker-entrypoint.sh#L140

In my local processes for development I tend to use docker compose and unless i want a custom check to verify that a container is running i then listed to logs for a specific sentence. For instace for an apache container i check that this has run 
`[Tue Aug 15 12:57:35.380606 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'`

If the init is running in the postgres container i can wait for 
`PostgreSQL init process complete; ready for start up.`

Any objection to run an else condition to echo
`PostgreSQL init process skipped; ready for start up.`

I can create a PR but wanted to check with you before.

**Comment by yosifkit** [comment]
I'd instead recommend checking for connectivity, rather than a log message.  That is what we do in the [Wordpress image](https://github.com/docker-library/wordpress/blob/28bdfe39463a2e73effd6aa49a6a97821d148cff/php7.1/apache/docker-entrypoint.sh#L194-L213).  The log message will stick around in the logs on a container restart and will then appear again for each restart.

**Comment by bizmate** [comment]
Connectivity does not tell if the init has finished and I would rather not rely on a custom query to verify the dataset/config is ready when i can lazily and cheaply check a log. This is also because my init might do nothing or a lot depending on what scripts i mount in the init folder. 
A simple echo (as there is one already when the process runs) that the init was skipped would at least confirm that there is nothing else spinning in the container and you can assume the your container is ready as you expect it because the init was run in a previous spin (for instance if like me you also use volumes).

**Comment by yosifkit** [comment]
Actually remote connectivity does tell if the init has finished (i.e. any connection from another container or the host). For the init process, the postgres server is started in localhost only mode, so once it is available remotely, it has already finished any init scripts and been restarted to listen publicly.

**Comment by Simran-B** [comment]
FYI When using Docker Compose `healthcheck` to determine readiness, it is crucial to use the hostname (defined by the `services` key), like `pg_isready --host=THE_HOSTNAME`, to not incorrectly return successfully because Postgres accepts local connections during initialization.

**Comment by tianon** [comment]
See https://github.com/docker-library/healthcheck/blob/40afbf64d69cf933af0da4df6383958a29113601/postgres/docker-healthcheck for an example implementation that does effectively that, but in a generalized way (using the external IP via forced TCP connection) :+1:
