### ISSUE TITLE
add support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [docker-library/postgres#329]
I want to use this image on arm64 architecture but I'm not find the package support arm64 
http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/InRelease  .So I want to know this image whether or not support arm64.

**Comment by tianon** [comment]
That's correct; officially, upstream's repository only supports `Architectures: amd64 i386 ppc64el`.

Once Alpine adds multi-arch support, we'll have an easier time adding more architectures for the Alpine variants at least, since those compile PostgreSQL from source.

**Comment by tianon** [comment]
(Hence why https://github.com/docker-library/official-images/blob/fc0cc76485a8ac9d7dc6c0decede2def264f5d47/library/postgres has `Architectures: amd64, i386, ppc64le`.)

**Comment by longquan7** [comment]
@tianon OK,thanks

**Comment by longquan7** [comment]
This image support arm64 and add it to the https://hub.docker.com/u/arm64v8/ .
