### ISSUE TITLE
Restore from WAL

### ISSUE THREAD

**Issue by andrewgy8** [docker-library/postgres#334]
I have an image which has wal-e installed and working.  It successfully on `backup-push` sends my WAL to the remote drive.  

However when I run `backup-fetch`, I get the error 

```
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-fetch".
        STRUCTURED: time=2017-09-05T07:45:24.721673-00 pid=3839
wal_e.main   ERROR    MSG: attempting to overwrite a live data directory
        DETAIL: Found a postmaster.pid lockfile, and aborting
        HINT: Shut down postgres. If there is a stale lockfile, then remove it after being very sure postgres is not running.
        STRUCTURED: time=2017-09-05T07:45:24.750882-00 pid=3839
```

So I follow the error and shut down with `pg_ctl stop` and I get:

```
pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
```

Then I move to another shutdown method `pkill postgres`.

When i do that it seems to work in shutting down postgres, but then kicks me out of the container and runs the restart protocol.  

To fix this, I could get rid of the `restart:always` in my compose file, but I don't want to do this.  

Any other ideas on how to restore from WAL using wal-e?

**Comment by yosifkit** [comment]
The running postgres server is the main process of the container, if it dies, the container dies as you saw.  If this backup restore needs to run before postgres starts, you could do something like:

```console
$ docker run -d -v volume-mapping:/var/lib/postgresql/data posgres:9.6 sh -c 'backup-fetch args && docker-entrypoint.sh postgres'
