### ISSUE TITLE
Allow to unpack bzip2 dumps

### ISSUE THREAD

**Issue by isqad** [docker-library/postgres#335]
Hello!
I'd like to use bzip2 archives for dumps, what do you think about it?

**Comment by wglambert** [comment]
This works http://www.solomonson.com/content/using-bzip-pgdump

> To dump data from a table:
> 
> pg_dump -hlocalhost -Upostgres -a -t table database|bzip2 > tabledata.bz2
> 
> To restore:
> 
> bzip2 -c -d tabledata.bz2 | psql -hlocalhost -Upostgres database
