### ISSUE TITLE
Official way to include extensions

### ISSUE THREAD

**Issue by gmile** [docker-library/postgres#340]
What is the _official way_ of adding postgres extensions, given postgres-alpine is a base image?

I tried to add `postgresql-pglogical` and `postgis` extensions by installing respective `apk` packages, but this process, despite being the most intuitive and straightforward, failed for me.

Here's my `Dockerfile`:

```Dockerfile
FROM postgres:9.6.4-alpine

RUN apk add --update --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ postgresql-pglogical postgis
```

Opening a now-closed [issue](https://bugs.alpinelinux.org/issues/7772) in apline linux tracker made me realize that in a container above I ended up having two postgreses installed:

* one coming from the base image,
* one coming from the `apk` (`apk` has to make sure that for given packages to install all dependencies are met; for `postgresql-pglogical` and `postgis` package called `postgres` is a dependency).

I can see other issues asking for clarification around adding extensions:

* Installing plv8 #290 
* Installing pgtap #306

Maybe it makes sense to include a statement in a readme? Something like:

> For any postgres extension not listed in [postgres-contrib](https://www.postgresql.org/docs/9.6/static/contrib.html), make sure to compile them in your own image.

**Comment by tianon** [comment]
Yeah, I think noting this in the image description is probably a good idea
to help reduce the potential for confusion around it. 👍

**Comment by tianon** [comment]
https://github.com/docker-library/docs/pull/1204 :+1:

**Comment by 62mkv** [comment]
would be cool to mention "official" way to activate already installed extensions; for example. I have to run `CREATE EXTENSION "uuid-ossp";` *every time* I re-run the container with volume removal.

**Comment by luanphamquoine** [comment]
Not any mean `offcial` but here is a working solution: https://www.reddit.com/r/docker/comments/ea70rz/why_did_adding_a_postgres_extension_to_the_base/

**Comment by phluan** [comment]
Not any mean `offcial` but here is a working solution: 

```
FROM postgres:12 AS extension_builder

# Already download extension code
RUN cd /
RUN mkdir external_extensions
RUN mkdir /external_extensions/sequential-uuids
COPY lib/sequential-uuids/ /external_extensions/sequential-uuids/
WORKDIR /external_extensions/sequential-uuids/

RUN apt-get update && apt install build-essential libicu-dev postgresql-server-dev-all -y --no-install-recommends
RUN make clean && make install

FROM postgres:12
# run find / -name 'sequential_uuids*' to find newly compiled files and copy to next stage
COPY --from=extension_builder /usr/lib/postgresql/12/lib /usr/lib/postgresql/12/lib
COPY --from=extension_builder /usr/share/postgresql/12/extension /usr/share/postgresql/12/extension
```

credit: https://www.reddit.com/r/docker/comments/ea70rz/why_did_adding_a_postgres_extension_to_the_base/

**Comment by yuuuxt** [comment]
based on @phluan 's work, here's the `Dockerfile`s I'm using: https://hub.docker.com/r/yuuuxt/postgres_seq_uuid/dockerfile
