### ISSUE TITLE
postgres container throwing up the following error

### ISSUE THREAD

**Issue by VenkateshSrini** [docker-library/postgres#341]
Hi,
I'm getting the below error at container startup
LOG:  database system was interrupted; last known up at 2017-09-17 03:49:03 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  invalid record length at 0/1500808: wanted 24, got 0
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started

As a result the scripts that I copied to init-db is also not executed. Please see the attached dockerfile and sql scripts.

I use the below commands
docker rm postgres-server -- force
docker run --name postgres-server -p 5600:5432 -v pgdata:/var/lib/postgresql/data --restart=always postgres

[Dockerfile .txt](https://github.com/docker-library/postgres/files/1308823/Dockerfile.txt)
[schema.txt](https://github.com/docker-library/postgres/files/1308824/schema.txt)

Please help me to resolve the same

**Comment by yosifkit** [comment]
Any scripts in `initdb.d` are only run when the container is started with no database files.  If you only delete the container but not the named volume (`pgdata`), then it will not run your script.

See also https://github.com/docker-library/postgres/issues/203#issuecomment-255200501.

**Comment by lanshark** [comment]
I am experiencing exactly the same issue, but not using init_db.
