### ISSUE TITLE
POSTGRES_PASSWORD_FILE or POSTGRES_DB_PASSWORD_FILE

### ISSUE THREAD

**Issue by vasicvuk** [docker-library/postgres#352]
In documentation for Docker secret POSTGRES_PASSWORD_FILE is used. With 9.6:apline version password from Secret is not set but when i use ENV variable POSTGRES_DB_PASSWORD_FILE it works.

Should it be POSTGRES_DB_PASSWORD_FILE as it is in documentation or it is error ?

**Comment by yosifkit** [comment]
It shouldn't be `_DB_` for any of the variables we use.  There is a comment about [`XYZ_DB_PASSWORD`](https://github.com/docker-library/postgres/blob/b7cb3c6eacea93be2259381033be3cc435649369/9.6/alpine/docker-entrypoint.sh#L4-L8), but it is wrong and the only place mentioning `_DB_PASSWORD`.

https://github.com/docker-library/postgres/blob/b7cb3c6eacea93be2259381033be3cc435649369/9.6/alpine/docker-entrypoint.sh#L65-L66

```console
$ echo 'secret' > notpasswords
$ docker run -d --name pg -e POSTGRES_PASSWORD_FILE=/notpasswords -v "$PWD/notpasswords:/notpasswords" postgres:9.6-alpine
$ docker run -it --rm --link pg postgres:9.6 bash
root@c37d1f3f2910:/# psql -h pg -U postgres
Password for user postgres: 
psql (9.6.5)
Type "help" for help.

postgres=#
```

**Comment by yosifkit** [comment]
I did find one source mentioning `POSTGRES_DB_PASSWORD_FILE`, and it was on Docker's blog with its related dockersamples/atsea-shop-app`.  I made a PR to fix: https://github.com/dockersamples/atsea-sample-shop-app/pull/100.

**Comment by vasicvuk** [comment]
With 9.6 alpine version POSTGRES_PASSWORD_FILE is not working but POSTGRES_DB_PASSWORD_FILE works.  Looking at the image source i also didn't find POSTGRES_DB_PASSWORD_FILE anywhere but there is actually a problem that POSTGRES_PASSWORD_FILE is ignored somehow.

**Comment by tianon** [comment]
You're probably getting a successful database from
"POSTGRES_DB_PASSWORD_FILE", but I'd wager that your logs have a note
informing you that your database is actually passwordless.

Can you please provide a simple way to reproduce the issue with
"POSTGRES_PASSWORD_FILE"?
(because we cannot seem to reproduce it)

**Comment by yosifkit** [comment]
Is it a completely new database each time?  If you are reusing the database files via a volume/bind mount, the initialization will not happen and a new password will now be set. See https://github.com/docker-library/postgres/issues/203#issuecomment-255200501.

**Comment by vasicvuk** [comment]
You are right. POSTGRES_DB_PASSWORD_FILE will not create password at all. I found out that when creating a secret from Windows echo command ads new line at the end of the secret (\r\n) and that is not trimmed inside Docker image when putting password over (POSTGRES_PASSWORD_FILE) so i guess that is the problem

**Comment by tianon** [comment]
Glad you got it figured out! :+1:

**Comment by azdrojowa123** [comment]
> You are right. POSTGRES_DB_PASSWORD_FILE will not create password at all. I found out that when creating a secret from Windows echo command ads new line at the end of the secret (\r\n) and that is not trimmed inside Docker image when putting password over (POSTGRES_PASSWORD_FILE) so i guess that is the problem

Thank you very much ! 
I was dealing with it for a day
