### ISSUE TITLE
Searching for a clean way to add header/dev files

### ISSUE THREAD

**Issue by realknorke** [docker-library/postgres#367]
Hi,

I'm using the postgres image for a while now. Now I need to add a stored procedure written in C. To compile the function's code I need the header files, usually installed under /usr/include/postgresql-X.Y/

In docker-library/postgres are no header files present. What is the cleanest way to add the appropriate .h files to be able to generate a .so file with my stored procedure?

Sadly, I cannot install any postgresql-dev-X.Y package in the container because there is no package on your apt repo server (http://apt.postgresql.org/pub/repos/apt/).

My plan is to use a build container based on postgres:9.6 to compile a shared object artifact which I can later just docker-ADD to another postgres:9.6 container (without the build-essentials/gcc overhead).

**Comment by tianon** [comment]
I think the package name you're looking for is actually `postgresql-server-dev-X.Y` (not simply `postgresql-dev-X.Y` as referenced).

**Comment by realknorke** [comment]
Argh, I found my mistake.

I saw the `apt-get update` calls in the Dockerfile and assumed that the package list is more or less up to date when EXECing into the container. But I didn't saw the `rm -rf /var/lib/apt/lists/*` and thus `apt search` returned not much.
Long story short: I forgot to trigger another `apt-get update`.

You can close/resolve this issue. Thanks for the help and sorry for this invalid issue. :)
