### ISSUE TITLE
Need an image release of 9.4.15-1.pgdg80+1

### ISSUE THREAD

**Issue by pumazi** [docker-library/postgres#370]
I'm looking for a release of Postgres image containing version `9.4.15-1.pgdg80+1`.

I see the commits on master for this, but then the current rendered Dockerfile for this says `9.4.15` rather than `9.4.15-1.pgdg80+1`. So that seems strange...

Then there seems to be the issue that hub.docker.com only has a tag for `9.4.14`. So that leads me to believe that the `9.4.15*` image hasn't been released at all.

I'm not really aware of how the image release sequence of events caries out. So please forgive me if I'm jumping to conclusions that are opposite of what really happens.

**Comment by pumazi** [comment]
This is causing issues for me because my Dockerfile extends `postgres:9.4`. Within the Dockerfile I've got the common `RUN set -xe && apt-get update && ...` lines, which means postgres is getting updated to `9.4.15-1.pgdg80+1`. Then another lines upgrades triggers the upgrade of `postgres-9.4`.

I'd image under most circumstances this wouldn't be an issue, but for a yet to be determined reason it's causing my resulting container to not allow external connections.

**Comment by tianon** [comment]
See https://github.com/docker-library/postgres/blob/b84ddd1619ee3a7f6e318bb9ac33f39818b3b548/README.md, especially the following bit:

> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/postgres" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/postgres), especially [PRs with the "library/postgres" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fpostgres). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

We have @docker-library-bot which auto-commits any buildable/test-passing result of running `./update.sh` (which bumps the version numbers), and then creating that final PR to update `library/postgres` (which is what updates the actual image) is a manual process; see https://github.com/docker-library/official-images/pull/3698. :+1:
