### ISSUE TITLE
Postgres 10 images do not use --waldir instead of --xlogdir

### ISSUE THREAD

**Issue by jzampieron** [docker-library/postgres#372]
The Postgres 10 docker entrypoint passes *invalid* parameters to initdb.

The --xlogdir parameter has been replaced with --waldir.

Trying to use the POSTGRES_INITDB_XLOGDIR env variable fails entirely on startup with 
an empty folder.

**Comment by yosifkit** [comment]
Oh, it was just [rename](https://wiki.postgresql.org/wiki/New_in_postgres_10#Renaming_of_.22xlog.22_to_.22wal.22_Globally_.28and_location.2Flsn.29). It seems no one has tried to use it since we created the 10 beta image in June.  Thanks for pointing it out; let me work up a PR. :smiley_cat:

**Comment by jzampieron** [comment]
Excellent. For anyone searching. I worked around this issue using "POSTGRES_INITDB_ARGS" with the `--waldir` parameter set appropriated.

**Comment by yosifkit** [comment]
Updated images should be pushed to Docker Hub shortly: https://github.com/docker-library/official-images/pull/3718.
