### ISSUE TITLE
Postgresql 10 with PL/Tcl support  

### ISSUE THREAD

**Issue by Pajinek** [docker-library/postgres#376]
Hi. I would like to use postgresql 10 with PL/Tcl as previous version 9. 
I did same steps - installed package postgresql-pltcl-10  for PL/Tcl support.

```
ii  postgresql-10              10.1-1.pgdg90+1            amd64      
ii  postgresql-client-10       10.0-1.pgdg90+1            amd64        
ii  postgresql-client-common   187.pgdg90+1               all        
ii  postgresql-common          187.pgdg90+1               all          
ii  postgresql-pltcl-10        10.1-1.pgdg90+1            amd64        
```

But when I tried to create lang pltclu I receive following error:

```
>> createlang pltclu spaceschema
Error: pg_wrapper: createlang was not found in /usr/lib/postgresql/10/bin
```

This procedure works on postgresql 9+. What was changed in new version?

Regards

**Comment by dequis** [comment]
The [postgres 10 release notes][1] say:

>Remove createlang and droplang command-line applications (Peter Eisentraut)
>
>These had been deprecated since PostgreSQL 9.1. Instead, use CREATE EXTENSION and DROP EXTENSION directly.

So do this instead.

    psql -c 'CREATE EXTENSION pltcl'


[1]: https://www.postgresql.org/docs/10/static/release-10.html

**Comment by Pajinek** [comment]
Hi, I found another way yet. I was surprised that command still exist.

`psql -c 'CREATE LANGUAGE pltcl;'`
