### ISSUE TITLE
Windows installation problem for postgresql. Error in make command

### ISSUE THREAD

**Issue by roopteja123** [docker-library/postgres#397]
I am new to postgresql. I want to install postgresql through source code in windows. I am using MinGW and msys for installation. Configure command is working fine with me. When i execute make command I am getting errors. Would any one please help me to rectify these errors.
<pre>[gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -I../../../../src/include -I./src/include/port/win32 -DEXEC_BACKEND  -I/home/roopteja.itha/openssl/include -I/home/roopteja.itha/uuid "-I../../../../src/include/port/win32" -DBUILDING_DLL  -c -o spgtextproc.o spgtextproc.c
In file included from ../../../../src/include/c.h:101:0,
                 from ../../../../src/include/postgres.h:47,
                 from spgtextproc.c:40:
../../../../src/include/pg_config_os.h:333:18: error: unknown type name '_locale_t'
 #define locale_t _locale_t
                  ^
../../../../src/include/utils/pg_locale.h:69:9: note: in expansion of macro 'locale_t'
 typedef locale_t pg_locale_t;
         ^~~~~~~~
make[4]: *** [spgtextproc.o] Error 1
make[4]: Leaving directory `/home/roopteja.itha/postgresql-9.5.10/src/backend/access/spgist'
make[3]: *** [spgist-recursive] Error 2
make[3]: Leaving directory `/home/roopteja.itha/postgresql-9.5.10/src/backend/access'
make[2]: *** [access-recursive] Error 2
make[2]: Leaving directory `/home/roopteja.itha/postgresql-9.5.10/src/backend'
make[1]: *** [all-backend-recurse] Error 2
make[1]: Leaving directory `/home/roopteja.itha/postgresql-9.5.10/src'
make: *** [all-src-recurse] Error 2]</pre>

**Comment by yosifkit** [comment]
This is the git repo for the Docker images that contain PostgreSQL.  Although we do build from source in our Alpine Linux based images, we do not know much about building it on Windows.  You will probably have better luck posting on stackoverflow or possibly one of the PostgreSQL mailing lists (https://www.postgresql.org/list/).  Maybe this will help: https://www.postgresql.org/docs/current/static/install-windows.html.
