### ISSUE TITLE
Provide build argument to upgrade all system packages

### ISSUE THREAD

**Issue by lorddaedra** [docker-library/postgres#399]
Can you do something like that? (I did not tested code but it looks simple: if user need latest versions of all packages, he/she just provide upgrade_packages_arg and Docker will include command `apk upgrade --no-cache` which will upgrade all system packages...

Just after FROM add 

```
ARG upgrade_packages_arg
RUN set -ex; \
if [ "not$upgrade_packages_arg" = "not" ]; \
then \
    echo Skip upgrading installed packages, set --build-arg upgrade_packages_arg to something if you need it; \ 
else \
    echo Upgrading packages; \
    apk upgrade --no-cache; \
fi
```

`docker build -t "..." --build-arg upgrade_packages_arg=upgrade .`

In ideal world I would like such argument added to all official (with `_` prefix) images, based on Alpine, including Python image, for example...

Problem which I try to solve by this code - I do not want to maintain my own images only because of I prefer to use upgraded images, it will be better fix on your side...

**Comment by lorddaedra** [comment]
Or, as alternative, you can provide way to `monkeypatch` your images via docker build command.

I don't know, but something like that:
`docker build -t "..." --monkeypatch insert:after:FROM:apk upgrade --no-cache .`

Both ways will allow users use your code (do not maintain own code) to build custom images. Build command can be created once and used forever on CI, but if you need to maintain custom images - you need at least replace some versions etc. So it's eat much more time than just monkeypatching or configuring your images via build arguments...

**Comment by yosifkit** [comment]
We do not use `apt-get upgrade` in the official images, but you are welcome to do it in a dependent image if that is something important to you.

> You should avoid `RUN apt-get upgrade` or `dist-upgrade`, as many of the “essential” packages from the parent images won’t upgrade inside an unprivileged container. If a package contained in the parent image is out-of-date, you should contact its maintainers. If you know there’s a particular package, `foo`, that needs to be updated, use `apt-get install -y foo` to update automatically.
>
> \- https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run

```dockerfile
FROM postgres:10
RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*
```

Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with the required modifications.
