### ISSUE TITLE
postgres /docker-entrypoint.sh not running scripts in /docker-entrypoint-initdb.d/

### ISSUE THREAD

**Issue by kevinburke** [docker-library/postgres#40]
I'm having trouble writing a script to /docker-entrypoint-initdb.d/ and having Docker run it from /docker-entrypoint.sh.

- It looks like /docker-entrypoint.sh is supposed to source any scripts it finds in /docker-entrypoint-initdb.d/. I verified I'm running this version of the script by `cat`ing the script and verifying this is the expected behavior.

- I followed the instructions in "justfalter"'s comment here: https://registry.hub.docker.com/_/postgres/ to add a fix-acl.sh file and put it in the correct folder. I double checked the folder name was correct.

- I also mirrored the commands in the /docker-entrypoint.sh script to check that the script could be sourced and would produce the desired behavior.

- When I do "docker run", it's clear that Postgres starts but the specified line was not added to `pg_hba.conf`. I double checked this by verifying the mtime of `pg_hba.conf` - it wasn't touched or overwritten after my script ran. I also tried having my script `touch` various files to just verify that it ran, with no success.

I'm at a loss for how to continue debugging this; I placed a file in the place that it's supposed to go, verified that the script runner that starts postgres should run it, and verified that the script does what I want, and I don't see any output (a changed pg_hba.conf, or even a simple file). 

I'm running the newest version of everything; starting Docker inside of a Ubuntu Virtualbox being provisioned from Vagrant. I share one folder from the Docker container to the host VM - the data folder containing pg_hba.conf.

Would appreciate your help!
Kevin

**Comment by jmls** [comment]
I hit this problem - the issue is that the script is only run if there is no postgres data directory ;) 

````
if [ -z "$(ls -A "$PGDATA")" ]; then
````

I think it would be better to have the script run a "initdb" function for all brand spanking new installations, and  a "always run" function

hth

**Comment by md5** [comment]
There isn't any way that I know of to detect a newly created container. The
PGDATA check is probably the best this image can do.

**Comment by Cactusbone** [comment]
sometime the scripts could be used to perform update operations on the existing data.
for example updating an extension on all affected dbs. 
It would be nice to have a base install scripts folder and an update scripts one

**Comment by jayfk** [comment]
> I hit this problem - the issue is that the script is only run if there is no postgres data directory ;)
> 
>` if [ -z "$(ls -A "$PGDATA")" ]; then`
> I think it would be better to have the script run a "initdb" function for all brand spanking new installations, and a "always run" function

I agree. This makes it extremely hard to supply your own `postgresql.conf` with a `Dockerfile` that uses the official postgres image as base.

**Comment by yosifkit** [comment]
@jayfk, #72 should fix that part.

**Comment by danwyry** [comment]
I too am experiencing this problem with postgres:9.4 images. 
My Dockerfile does copy the scripts into the /docker-entrypoint-initdb.d but it none is run (just .sh scrpits, no .sql). 
I already checked file permissions (root:root  755) for the scripts. 
Any advise con this ?

**Comment by danwyry** [comment]
I too met this problem and have been trying to debug it for a week already. 
my .sh scripts in docker-entrypoint-init.d/ never run. 
I tryed extending Dockerfile from 9.4 image, and also I tryed building it myself from a copy of the original Dockerfile and docker-entrypoint.sh. It seems to be that the docker-entrypoint.sh never gets into the 
     if [ "$1" = 'postgres' ]; then 
condition on line 17 of the script.
I ran out of   ideas. Any help on this  ?

**Comment by yosifkit** [comment]
@danwyry, what are you running?  Any information you can give to help us reproduce the issue?

**Comment by danwyry** [comment]
Sure, this is what I tryied so far: 
I downloaded 9.4's Dockerfile and docker-entrypoint.sh to a directory on my computer
I added the  functions detailed below  to docker-entrypoint.sh and called them right after the set_listen_address '*'  function is called.
on my docker-compose.yml I put : 
build: my_postgres 
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  volumes_from:
   - data
  ports:
   - "5434:5432"

being 'my_postgres' the directory name under which y located the Dockerfile and entrypoint. 

I ran docker-compose build. 
It ran with no errors, but postgresql.conf. 

I performed several hardcoded tests to see where the docker-entrypoint.sh exits and realized itś not even getting past the follwing condition (which in the original file is in line 17)
   '''if [ "$1" = 'postgres' ]; then'''

These are the functions I added that configure some settings on postgresql.conf (I already tested them on their own and they work ok). : 

set_bytea_output() {
    sed -ri '/^[# ]*[# ]*[# ]*bytea_output[ ]*=[ ]*.*/d' "$PGDATA/postgresql.conf" 
   echo "bytea_output = '$1'" >> "$PGDATA/postgresql.conf" 

}
set_standard_conforming_strings() {
  sed -ri '/^[# ]*[# ]*[# ]*standard_conforming_strings[ ]*=[ ]*.*/d' "$PGDATA/postgresql.conf" 
  echo "standard_conforming_strings = $1" >> "$PGDATA/postgresql.conf" 
}

**Comment by yosifkit** [comment]
Hmmm... I am unable to reproduce.  I started with the [docker-entrypoint.sh](https://github.com/docker-library/postgres/blob/ed23320582f4ec5b0e5e35c99d98966dacbc6ed8/docker-entrypoint.sh) and added your functions with some output to see it works.  I guessed on the values to apply.

```diff
diff --git a/docker-entrypoint.sh b/docker-entrypoint.sh
index 87d7e3b..3334092 100755
--- a/docker-entrypoint.sh
+++ b/docker-entrypoint.sh
@@ -6,6 +6,16 @@ set_listen_addresses() {
        sed -ri "s/^#?(listen_addresses\s*=\s*)\S+/\1'$sedEscapedValue'/" "$PGDATA/postgresql.conf"
 }
 
+set_bytea_output() {
+       sed -ri '/^[# ]*[# ]*[# ]*bytea_output[ ]*=[ ]*.*/d' "$PGDATA/postgresql.conf"
+       echo "bytea_output = '$1'" >> "$PGDATA/postgresql.conf"
+}
+set_standard_conforming_strings() {
+       sed -ri '/^[# ]*[# ]*[# ]*standard_conforming_strings[ ]*=[ ]*.*/d' "$PGDATA/postgresql.conf"
+       echo "standard_conforming_strings = $1" >> "$PGDATA/postgresql.conf"
+}
+
 if [ "$1" = 'postgres' ]; then
        mkdir -p "$PGDATA"
        chown -R postgres "$PGDATA"
@@ -84,6 +94,13 @@ if [ "$1" = 'postgres' ]; then
 
                gosu postgres pg_ctl -D "$PGDATA" -m fast -w stop
                set_listen_addresses '*'
+               set_bytea_output 'hex'
+               set_standard_conforming_strings 'off'
+               echo '*****************************'
+               echo '*****************************'
+               cat "$PGDATA/postgresql.conf"
+               echo '*****************************'
+               echo '*****************************'
 
                echo
                echo 'PostgreSQL init process complete; ready for start up.'
```

Then I ran postgres with the modified entrypoint:
```console
$ docker run -it --rm -v ~/postgres/modified-docker-entrypoint.sh:/docker-entrypoint
.sh:ro -e POSTGRES_PASSWORD=password postgres:9.4
```

**Comment by danwyry** [comment]
would you mind trying it within a docker-compose configuration to see if maybe that's making any difference?

**Comment by mericano1** [comment]
Hi @danwyry did you ever get your scripts running? I am having the same issue using docker-compose

**Comment by danwyry** [comment]
nope, couldn't do it. But I stopped trying after a while

**Comment by yosifkit** [comment]
@danwyry, my newest idea is that the volume was persisting. With docker compose it tries really hard to keep volumes (ie your initialized database files).  Most of the entrypoint script only runs on first initialization.  `docker-compose rm -v` should get rid of all the containers and their volumes if you want to start fresh on the database.

**Comment by brendan-rius** [comment]
Any ETA on when we would be able to easily re-launch the init script (via a command maybe?), without removing the volumes?

**Comment by blag** [comment]
I had this exact same issue and it was solved by removing the volume associated with the container in `docker-compose.yml`.

@brendan-rius If you just need the data saved in the volume (and you don't have anything else stored there), you should be able to run your postgres container (see the "... or via psql" section [here](https://hub.docker.com/_/postgres/)) manually, dump your database, remove the volume, recreate everything, and import the database again.

**Comment by ekimia** [comment]
is there an easy way to just set all listen addresses so my code can access postgres? My code isnt copied into the image in development mode.

**Comment by yosifkit** [comment]
@ekimia, what do you mean? If you have any shell scripts in `/docker-entrypoint-initdb.d/` then they can access postgres via `localhost`.

If you are talking about accessing postgres from another container, then your code will have to wait for postgres to be ready, after it has done its initialization and run through any `initdb` scripts.

**Comment by yosifkit** [comment]
I feel like the original issue here has been solved.  If you are still having trouble getting `/docker-entrypoint-initdb.d/` scripts to run, please open a new issue with as much information as possible.

**Comment by wyuenho** [comment]
I just ran into this problem. I feel this should be made clear in the [image description here](https://hub.docker.com/_/postgres/).

**Comment by HiImJayHireMe** [comment]
So I ran into this also... I did find a solution that works for me.  It's very cheese-y but the way around it seems to be to "build" a new image.  

This is what I tried (and it didn't run the scripts for me):
```
# docker-compose.yml (NOT working)
services:
  db:
     image: mysql5:7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: "${DBROOT}"
     ports:
       - "3306:3306"
     volumes:
       - ./db-scripts:/docker-entrypoint-initdb.d
       - ./db-scripts:/env/mysql/conf.d
     volumes_from:
       - container:db
```
where `db` is the name of the mysql volume container.  This was my solution:

```
# Dockerfiledb
FROM mysql:5.7
```

```
# docker-compose.yml (working)
services:
  db:
     build:
       dockerfile: Dockerfiledb
       context: .
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: "${DBROOT}"
     ports:
       - "3306:3306"
     volumes:
       - ./db-scripts:/docker-entrypoint-initdb.d
       - ./db-scripts:/env/mysql/conf.d
     volumes_from:
       - container:db
```
I suppose this satisfies the requirement that it is a "new" container.


As an aside (not included in the above file but including in my actual code), I include something like:
```
volumes:
  data:  # <---- named volume created from base mysql volume container
    external: true
```
I noticed that if I don't use named volumes, it starts eating up HD space.  Might be something else I'm doing wrong but that seems to correlate with the problem fix.
