### ISSUE TITLE
Documents mention POSTGRES_PASSWORD rather than PGPASSWORD

### ISSUE THREAD

**Issue by Miserlou** [docker-library/postgres#402]
This may (or may not?) be a documentation bug.

The docs say that a the password environment variable can be supplied with the `POSTGRES_PASSWORD` key. So, I was expecting to be able to use that key like so:

```bash
docker run -it -e POSTGRES_PASSWORD=mysecretpassword --rm --link mydb:postgres postgres:9.6.6 psql -c "create database my_cool_database" -h postgres -U postgres
```

Unfortunately, this causes the password prompt for user `postgres`.

Instead, I found (after some mailing-list archive digging) that we must use the `PGPASSWORD` key, which isn't mentioned anywhere in the documents.

```bash
docker run -it -e PGPASSWORD=mysecretpassword --rm --link mydb:postgres postgres:9.6.6 psql -c "create database my_cool_database" -h postgres -U postgres
```

Perhaps the docs could mention how `POSTGRES_PASSWORD` could be used here, or how `POSTGRES_PASSWORD` could be used instead, if that's possible.

Thanks!
Rich

**Comment by tianon** [comment]
`PGPASSWORD` is an environment variable used by `psql` itself -- `POSTGRES_PASSWORD` is an environment variable used by our `initdb` script:

https://github.com/docker-library/postgres/blob/aaf209829e072bec11bca1f6f0b52e756dfc096e/10/docker-entrypoint.sh#L63-L87

**Comment by Miserlou** [comment]
Yeah, this issue about how that gets documented.

**Comment by qedrakmar** [comment]
This is fair.  I'll make an update to https://github.com/docker-library/docs/tree/master/postgres
