### ISSUE TITLE
Built in ability to customiza pg_hba

### ISSUE THREAD

**Issue by blaggacao** [docker-library/postgres#407]
Before the `exec "$@"`:

```bash
# Load a security configuration at normal runtime
file_env 'POSTGRES_HBA'
rm "$PGDATA/pg_hba.conf" && cp "$PGDATA/pg_hba.orig" "$PGDATA/pg_hba.conf"
{
	echo
	echo
	echo 
	echo "# Additional security configuration ..."
} >> "$PGDATA/pg_hba.conf"
if [ "$POSTGRES_HBA" ]; then
	{
		echo "$POSTGRES_HBA"
	} >> "$PGDATA/pg_hba.conf"
else
	cat "$PGDATA/pg_hba.docker-default" >> "$PGDATA/pg_hba.conf"
fi
```

Replacing
```bash
{
	echo
	echo "host all all all $authMethod"
} >> "$PGDATA/pg_hba.conf"
```
by
```bash
cp $PGDATA/pg_hba.conf $PGDATA/pg_hba.orig
{
	echo "host   all             all             all                     $authMethod"
} >> "$PGDATA/pg_hba.docker-default"
```

**Comment by AnthonyMastrean** [comment]
In the meantime, what is the recommendation for modifying `pg_hba.conf`? Create an image FROM this one and COPY your own?

**Comment by yosifkit** [comment]
You can override `pg_hba.conf` via a script in `/docker-entrypoint-initdb.d/`; those are run after the initial setup by our script and once all scipts/sql files in `initdb.d` are done, the temporary server (listens only on unix socket) is then stopped and started to listen on the network so the changes would then be in effect.

If you have other scripts in `initdb.d` that need the changes applied, then I think a `pg_ctl reload -D "$PGDATA"` should work.

**Comment by AnthonyMastrean** [comment]
But, scripts in `/docker-entrypoint-initdb.d/` are only run _once_ if `$PGDATA` isn't [initialized]((https://github.com/docker-library/postgres/blob/master/9.6/docker-entrypoint.sh#L57)) yet, right? How would you make revisions to your `pg_hba.conf` after 1st run, if needed? (Especially when running w/ persistent volumes)
