### ISSUE TITLE
9.5.11 docker image not published

### ISSUE THREAD

**Issue by thijslemmens** [docker-library/postgres#410]
After reading the release anouncement (https://www.postgresql.org/about/news/1829/), I wanted to update our own images with the latest versions, but I cannot find the 9.5.11 on docker hub.
Has it been forgotten?

**Comment by yosifkit** [comment]
The 9.5 image has not been updated because the 9.5 postgres apt repo has not been updated: http://apt.postgresql.org/pub/repos/apt/.  We have to wait until the apt repo has the new version.
