### ISSUE TITLE
Update alpine image to 3.7

### ISSUE THREAD

**Issue by NicoTexas** [docker-library/postgres#413]
Please update the Postgres alpine images to Alpine 3.7.
Right now they are based on Alpine 3.5

From
```
FROM alpine:3.5
```
to
```
FROM alpine:3.7
```

**Comment by yosifkit** [comment]
Duplicate #400.

**Comment by NicoTexas** [comment]
So, no plan to upgrade underlying Alpine version for 9.5.x, or 9.6.x?
