### ISSUE TITLE
Missing locale

### ISSUE THREAD

**Issue by xarg** [docker-library/postgres#415]
Seems like the latest 10.2 image (maybe earlier?) does not have the locale set correctly:

```
pg0_1        | 2018-02-16 17:08:35.744 UTC [1] LOG:  invalid value for parameter "lc_messages": "en_US.utf8"                                                                                                                           
pg0_1        | 2018-02-16 17:08:35.744 UTC [1] LOG:  invalid value for parameter "lc_monetary": "en_US.utf8"                                                                                                                           
pg0_1        | 2018-02-16 17:08:35.745 UTC [1] LOG:  invalid value for parameter "lc_numeric": "en_US.utf8"        
pg0_1        | 2018-02-16 17:08:35.745 UTC [1] LOG:  invalid value for parameter "lc_time": "en_US.utf8"           
pg0_1        | 2018-02-16 17:08:35.745 UTC [1] FATAL:  configuration file "/var/lib/postgresql/data/10/postgresql.conf" contains errors         
```

When I run locale commands in the container:
```
# locale                                                                                                 
locale: Cannot set LC_CTYPE to default locale: No such file or directory                                           
locale: Cannot set LC_MESSAGES to default locale: No such file or directory                                        
locale: Cannot set LC_ALL to default locale: No such file or directory                                             
LANG=en_US.utf8                                          
LANGUAGE=                                                
LC_CTYPE="en_US.utf8"                                    
LC_NUMERIC="en_US.utf8"     
LC_TIME="en_US.utf8"        
LC_COLLATE="en_US.utf8"                                                                                            
LC_MONETARY="en_US.utf8"                                                                                           
LC_MESSAGES="en_US.utf8"                                 
LC_PAPER="en_US.utf8"                                    
LC_NAME="en_US.utf8"                                     
LC_ADDRESS="en_US.utf8"                                  
LC_TELEPHONE="en_US.utf8"                                
LC_MEASUREMENT="en_US.utf8"                              
LC_IDENTIFICATION="en_US.utf8"                           
LC_ALL= 
```

To fix it I did this:
`RUN localedef -i en_US -f UTF-8 en_US.UTF-8`

Hope it helps.

**Comment by wglambert** [comment]
Issue looked resolved in `10.2` and `latest` builds that I checked.

If issue is still present then I'll re-open.

**Comment by areed** [comment]
I get the same issue with this Dockerfile:
```
FROM postgres:10.7

RUN apt-get update && apt-get upgrade -y
```

The localedef command documented above fixes it.

**Comment by tianon** [comment]
Doing `apt-get upgrade` in a `Dockerfile` is very strongly not recommended (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get):

> Avoid `RUN apt-get upgrade` and `dist-upgrade`, as many of the “essential” packages from the parent images cannot upgrade inside an [unprivileged container](https://docs.docker.com/engine/reference/run/#security-configuration). If a package contained in the parent image is out-of-date, contact its maintainers. If you know there is a particular package, `foo`, that needs to be updated, use `apt-get install -y foo` to update automatically.

(Which doesn't mention anything about the size duplication of having essentially the same packages re-installed in a later layer.)

**Comment by henri9813** [comment]
Hello, 

This problem seems to be present on image 9.6 running in Kubernetes.
```
STATEMENT:  CREATE DATABASE fusionauth ENCODING 'UTF-8' LC_CTYPE 'en_US.UTF-8' LC_COLLATE 'en_US.UTF-8' TEMPLATE template0
ERROR:  invalid locale name: "English_United States"
STATEMENT:  CREATE DATABASE fusionauth ENCODING 'UTF-8' LC_CTYPE 'English_United States' LC_COLLATE 'English_United States' TEMPLATE template0
```

Did you fixed the 9.6 image ?

Best regards

**Comment by danielb2** [comment]
I have this issue on alpinelinux and there's no localedef command that I can find. is there another way?

**Comment by wglambert** [comment]
See https://github.com/docker-library/docs/blob/master/postgres/README.md#locale-customization

Alpine-based variants starting with Postgres 15 support ICU locales

**Comment by danielb2** [comment]
> See https://github.com/docker-library/docs/blob/master/postgres/README.md#locale-customization
> 
> Alpine-based variants starting with Postgres 15 support ICU locales

oh yes you're right. I didn't need this for pg15
