### ISSUE TITLE
How can I grant postgres user root privileges?

### ISSUE THREAD

**Issue by dapalmi** [docker-library/postgres#419]
How can I grant the postgres user root privileges?
I try to run a command from a third party app that I installed in the container on startup that requires root privileges.

**Comment by dapalmi** [comment]
Or is there any way to start a command with root privileges on startup (defined in Dockerfile)?

**Comment by yosifkit** [comment]
The user created by `POSTGRES_USER` (or the `postgres` user if that env is unspecified) is a superuser:

https://github.com/docker-library/postgres/blob/20c85c686ac1cc4424f3c690e0f971560efd240e/docker-entrypoint.sh#L101-L121

On first start, you can have scripts that run for the first initialization: https://github.com/docker-library/docs/tree/ed25ca2dfdde0d1f428eec592b5207116aadbcff/postgres#how-to-extend-this-image

**Comment by dapalmi** [comment]
But why do I get an error when I copy a script into docker-entrypoint-initdb.b with a command that requires root privileges if postgres is a superuser?

**Comment by yosifkit** [comment]
What does your script look like?

If you are talking about a shell script that needs the system `root` user and not `root` database user, then yes it will not work since at that point everything is running as the less privileged user `postgres`. So you cannot do things like install packages from apt; that should be done in a Dockerfile `FROM` this one.

**Comment by dapalmi** [comment]
Yes. Sorry. I should have mentioned that I need the system root user. I use a Dockerfile FROM postgres with RUN apt-get, install etc. to initialize a third-party-app. But on startup I need to run only one command with system root privileges to start the third-party-app. I thought that’s gonna be an easy thing to do. But it seems really complicated now.
