### ISSUE TITLE
Slow query time with Postgres 10 inside Docker vs bare-metal for AWS Linux 2

### ISSUE THREAD

**Issue by ynakm** [docker-library/postgres#422]
I've been trying to deploy Postgres within Docker for portability reason, and noticed that query performance as measured by "explain analyze" has been painfully slow compared to bare metal. For a table with 1.7 million rows, a query on bare metal Postgres takes about 1.2 sec vs 4.8 sec on Dockered Postgres, an increase of 4 times! This comparison is done with the same mounted volume for both bare-metal and Docker (for Docker, I'm using the -v option) The volume is a gp2 volume, mounted through AWS console, 60GB.

Couple of things I tried:

1) Increase shared memory buffer option in postgresql.conf, which has negligible effect 
2) Tried several volume mapping options (delegated, cached, consistent), also negligible effect
3) Upgrading Docker from 17.06-ce to 17.12-ce, which has no effect on performance

This is all done in AWS Linux 2 instance. The docker run command I use:

docker run -p 5432:5432 --name postgres -v /vol/pgsql/10.0/data:/var/lib/postgresql/data postgres:latest

Any idea on what's wrong with running Postgres within Docker? Am I missing any optimization? I'm only using Docker out-of-the-box configurations.

Here's the query plan for bare-metal (top) and Docker (bottom)
```

explain analyze select sum(countstarted), starttime from CompositionElementAggregate1 group by starttime;
                                                                               QUERY PLAN                                                              
                 
-------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------
 Finalize GroupAggregate  (cost=55246.24..55252.74 rows=200 width=40) (actual time=1173.552..1196.714 rows=4611 loops=1)
   Group Key: starttime
   ->  Sort  (cost=55246.24..55247.24 rows=400 width=40) (actual time=1173.540..1181.145 rows=13799 loops=1)
         Sort Key: starttime
         Sort Method: quicksort  Memory: 1463kB
         ->  Gather  (cost=55186.45..55228.95 rows=400 width=40) (actual time=1144.735..1161.795 rows=13799 loops=1)
               Workers Planned: 2
               Workers Launched: 2
               ->  Partial HashAggregate  (cost=54186.45..54188.95 rows=200 width=40) (actual time=1142.315..1147.535 rows=4600 loops=3)
                     Group Key: starttime
                     ->  Parallel Seq Scan on compositionelementaggregate1  (cost=0.00..51661.63 rows=504963 width=16) (actual time=0.033..606.934 rows
=585297 loops=3)
 Planning time: 0.096 ms
 Execution time: 1199.230 ms
(13 rows)


explain analyze select sum(countstarted), starttime from CompositionElementAggregate1 group by starttime;
                                                                               QUERY PLAN                                                              
                  
-------------------------------------------------------------------------------------------------------------------------------------------------------
------------------
 Finalize GroupAggregate  (cost=55246.24..55252.74 rows=200 width=40) (actual time=4579.309..4688.106 rows=4611 loops=1)
   Group Key: starttime
   ->  Sort  (cost=55246.24..55247.24 rows=400 width=40) (actual time=4579.281..4623.522 rows=13808 loops=1)
         Sort Key: starttime
         Sort Method: quicksort  Memory: 1463kB
         ->  Gather  (cost=55186.45..55228.95 rows=400 width=40) (actual time=4454.649..4531.503 rows=13808 loops=1)
               Workers Planned: 2
               Workers Launched: 2
               ->  Partial HashAggregate  (cost=54186.45..54188.95 rows=200 width=40) (actual time=4451.450..4469.493 rows=4603 loops=3)
                     Group Key: starttime
                     ->  Parallel Seq Scan on compositionelementaggregate1  (cost=0.00..51661.63 rows=504963 width=16) (actual time=0.049..2260.735 row
s=585297 loops=3)
 Planning time: 0.113 ms
 Execution time: 4702.844 ms
(13 rows)

**Comment by tianon** [comment]
I'm confused by this point:

> Tried several volume mapping options (delegated, cached, consistent), also negligible effect

Those mapping options only exist for Docker for Mac -- are you comparing AWS performance to that of Docker for Mac's shared volumes?  Or are you comparing PostgreSQL installed directly on the AWS VM to PostgreSQL inside Docker connected to the same volume on the same AWS VM?

**Comment by tianon** [comment]
It's probably also worth redoing your tests on a Debian AWS instance instead (using the same packages that get installed in the image) -- we don't do anything custom to configure PostgreSQL beyond what the upstream-built packages supply.

**Comment by pavelry** [comment]
EC2 free t2.micro; 
Amazon Linux 2 LTS Candidate 2; 
Docker version 17.06.2-ce;
All installations were used by default and didn't have any "optimizations".

Bare-metal [postgres ](https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7.5-x86_64/)10:
_QUERY PLAN
Finalize GroupAggregate  (cost=51348.25..51348.48 rows=9 width=14) (actual time=1228.829..1228.857 rows=9 loops=1)	
  Group Key: author	
  ->  Sort  (cost=51348.25..51348.30 rows=18 width=14) (actual time=1228.821..1228.833 rows=27 loops=1)	
        Sort Key: author	
        Sort Method: quicksort  Memory: 26kB	
        ->  Gather  (cost=51345.99..51347.88 rows=18 width=14) (actual time=1228.634..1228.778 rows=27 loops=1)	
              Workers Planned: 2	
              Workers Launched: 2	
              ->  Partial HashAggregate  (cost=50345.99..50346.08 rows=9 width=14) (actual time=1221.920..1221.925 rows=9 loops=3)	
                    Group Key: author	
                    ->  Parallel Seq Scan on document_template  (cost=0.00..48262.99 rows=416599 width=6) (actual time=0.036..586.299 rows=333333 loops=3)	
Planning time: 0.063 ms	
Execution time: 1231.159 ms_

[Official ](https://hub.docker.com/_/postgres/)postgres 10 docker image (debian and alpine has the same result):
_QUERY PLAN
Finalize GroupAggregate  (cost=51337.63..51337.85 rows=9 width=14) (actual time=1497.996..1498.035 rows=9 loops=1)	
  Group Key: author	
  ->  Sort  (cost=51337.63..51337.67 rows=18 width=14) (actual time=1497.986..1498.002 rows=27 loops=1)	
        Sort Key: author	
        Sort Method: quicksort  Memory: 26kB	
        ->  Gather  (cost=51335.36..51337.25 rows=18 width=14) (actual time=1497.580..1497.934 rows=27 loops=1)	
              Workers Planned: 2	
              Workers Launched: 2	
              ->  Partial HashAggregate  (cost=50335.36..50335.45 rows=9 width=14) (actual time=1490.743..1490.750 rows=9 loops=3)	
                    Group Key: author	
                    ->  Parallel Seq Scan on document_template  (cost=0.00..48252.24 rows=416624 width=6) (actual time=0.043..750.380 rows=333333 loops=3)	
Planning time: 0.062 ms	
Execution time: 1499.179 ms_

Docker overhead for this env. and [test case](http://sqlfiddle.com/#!15/c24fc/2) (I used 10^6 rows) ~ 17%

**Comment by tianon** [comment]
Were these tests performed using the exact same PostgreSQL packages? (not just the same environment -- these images do not use Amazon Linux)

The packages provided by this image are Debian, so a fair test would be a single EC2 instance running Debian, installing the upstream-provided PostgreSQL packages in the same way as this image does, and comparing the performance of the packages installed on the host to the packages from the container.

**Comment by tianon** [comment]
There's an issue for `mysql` over in https://github.com/docker-library/mysql/issues/456#issuecomment-409012368 where I've suggested a similar methodology for performing a proper and fair performance test of Docker vs non-Docker.

Given that there's not likely to be anything we've done in the image that could cause this disparity (it's either in the default PostgreSQL configuration or an issue with Docker / the Linux kernel), I'm going to close this for now.  If there are things upstream recommends we change that could improve this, we'd love to consider them!
