### ISSUE TITLE
Stop the container if running docker-entrypoint-initdb.d scripts error out

### ISSUE THREAD

**Issue by rvernica** [docker-library/postgres#432]
At start-up the container "executes" the files found in `docker-entrypoint-initdb.d`. If errors are encountered the container continues to operate normally. It might be better for the container to fail to start in this case. I'm using it as part of a Docker Compose setup and containers which depend on it think it initialized successfully.

The initializing files I add in `docker-entrypoint-initdb.d` are SQL scripts.

**Comment by yosifkit** [comment]
We run any SQL scripts with `psql -v ON_ERROR_STOP=1` and the bash script is running with `set -e` so it should naturally exit the container.

Are you perhaps setting `restart` policy and so postgres restarts and has an initialized database and so skips the rest of the initdb scripts?

**Comment by rvernica** [comment]
You are correct, there was a restart policy in place. Thanks for the clarification. Sorry for the trouble.

**Comment by djechelon** [comment]
Is there a way to run those scripts with `ON_ERROR_STOP=0`?

**Comment by ddombrowsky** [comment]
> Is there a way to run those scripts with `ON_ERROR_STOP=0`?

`postgres` will automatically run `*.sh` files also, so you could just create a script that calls `psql` manually to skip the errors.

I stumbled into the opposite problem where this was the case for me, and I _wanted_ it to exit, so I needed to put `-v ON_ERROR_STOP=0` into my script.
