### ISSUE TITLE
can not pull postgres 

### ISSUE THREAD

**Issue by huuhieupham189** [docker-library/postgres#434]
Can't pull postgres with docker
![image](https://user-images.githubusercontent.com/24770033/39080743-11baeb5a-455f-11e8-8acf-a2547b24f153.png)

**Comment by yosifkit** [comment]
Correct, there is no `postgres` image for Windows.  You need to pull it from a Linux machine.  There is discussion of supporting windows based images in https://github.com/docker-library/postgres/issues/324.
