### ISSUE TITLE
could not connect to server: Connection refused

### ISSUE THREAD

**Issue by Gauravba** [docker-library/postgres#441]
Till yesterday when we tried to build the docker  container of postgress from postgress image  9.5 it was working fine today when i clean the images and download the new image again i was getting this error
we are using this command to pull the image 

$docker build -t $(DB_IMAGENAME) postgres/postgres/

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....LOG:  database system was shut down at 2018-05-10 11:48:29 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
CREATE DATABASE

ALTER ROLE

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-user-db.sh
psql: could not connect to server: Connection refused
        Is the server running on host "0.0.0.0" and accepting
        TCP/IP connections on port 5432?

**Comment by stanleyawang** [comment]
i was using postgres 9.6 and had the same issues .... decided to upgrade to 9.6.6 and it was ok

**Comment by yosifkit** [comment]
The original issue looks like the result of https://github.com/docker-library/postgres/pull/440. In your initialization shell scripts from `/docker-entrypoint-initdb.d/` you should use `"${psql[@]}"` in place of `psql` directly, since that array already uses the user and password from the environment vars and connects via the unix socket rather than via a TCP/IP connection on `127.0.0.1` which is no longer available.

You can also just use psql yourself, but be sure not to specify an IP address like `127.0.0.1` so that it will use the unix socket:
```console
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" ...
```

**Comment by Gauravba** [comment]
thanks removing host worked we were giving host ip

**Comment by XSecr3t** [comment]
Hello

I have same troublem

I try setting msfdb from termux wiki but why fail?  

> Mr.XSecr3t@localhost:/data/data/com.termux/files/usr/var/lib
$ cd $HOME/metasploit-framework/config
Mr.XSecr3t@localhost:~/metasploit-framework/config
$ ls
application.rb        database.yml.travis
boot.rb               database.yml.vagrant
cucumber.yml          environment.rb
database.yml          environments
database.yml.example
Mr.XSecr3t@localhost:~/metasploit-framework/config
$ initdb $PREFIX/var/lib/postgresql
The files belonging to this database system will be owned by user "u0_a210".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /data/data/com.termux/files/usr/var/lib/postgresql ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... sysv
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start

Mr.XSecr3t@localhost:~/metasploit-framework/config
$ pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start
waiting for server to start.... done
server started
Mr.XSecr3t@localhost:~/metasploit-framework/config
$ msfconsole
[-] Failed to connect to the database: FATAL:  role "msf" does not exist

> db_status
[*] postgresql selected, no connection
msf > createuser msf
[*] exec: createuser msf

createuser: could not connect to database postgres: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/data/data/com.termux/files/usr/tmp//.s.PGSQL.5432"?
msf >

Is this something wrong? 
Thank you if you reply my problems :(
