### ISSUE TITLE
Upgrade to PostgreSQL 10.4?

### ISSUE THREAD

**Issue by pedrofurtado** [docker-library/postgres#444]

**Comment by decaz** [comment]
Yes, unfortunately there is no 10.4 version at the Docker Hub.

**Comment by tianon** [comment]
https://github.com/docker-library/postgres/commit/fe8c9a4a309a889dc057d53bf3769c25c1522c65, and https://github.com/docker-library/postgres#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet:

> ## See a change merged here that doesn't show up on Docker Hub yet?
> 
> Check [the "library/postgres" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/postgres), especially [PRs with the "library/postgres" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fpostgres).
> 
> For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

We'll be making a PR sometime today.
