### ISSUE TITLE
Set timezone in Postgres Docker Image

### ISSUE THREAD

**Issue by pedrofurtado** [docker-library/postgres#458]
My application uses `America\Sao_Paulo` timezone. How do I set the timezone in my Dockerfile of Postgres 10.4 docker image? Do I need to add a ENV command ?

**Comment by wglambert** [comment]
Duplicate of https://github.com/docker-library/ruby/issues/218

**Comment by yosifkit** [comment]
Duplicate of https://github.com/docker-library/postgres/issues/137
