### ISSUE TITLE
Using postgresql with external volume from Mac 

### ISSUE THREAD

**Issue by volkanunsal** [docker-library/postgres#46]
I am trying to mount it directly from the Mac file system.

``` bash
docker run  -v $HOME/postgres_data:/var/lib/postgresql kartoza/postgi
```

This results in a bunch of errors about user permissions:

```
initdb: could not create directory "/var/lib/postgresql/9.3/main/global": Permission denied
2015-01-07 16:33:52 UTC FATAL:  data directory "/var/lib/postgresql/9.3/main" has wrong ownership
2015-01-07 16:33:52 UTC HINT:  The server must be started by the user that owns the data directory.
```

Can a directory shared from Mac file system ever have the read/write permissions that postgres apparently needs?

**Comment by yosifkit** [comment]
This seems to be related to https://github.com/boot2docker/boot2docker/issues/629

**Comment by sebglon** [comment]
I have the same error on linux

**Comment by chaintan17** [comment]
I also have this issue using osx docker toolbox

**Comment by yosifkit** [comment]
There is discussion over on https://github.com/docker-library/mysql/issues/99 dealing with the same issue.  Perhaps we need to add something like https://github.com/docker-library/mysql/pull/161 to postgres?
