### ISSUE TITLE
Unable to run docker postgres

### ISSUE THREAD

**Issue by TeodorKolev** [docker-library/postgres#462]
```
$ docker run -ti -p 3000:3000  appname
* Starting PostgreSQL 10 database server                                        * Removed stale pid file.
Error: /usr/lib/postgresql/10/bin/pg_ctl /usr/lib/postgresql/10/bin/pg_ctl start -D /var/lib/postgresql/10/main -l /var/log/postgresql/postgresql-10-main.log -s -o  -c co
nfig_file="/etc/postgresql/10/main/postgresql.conf"  exited with status 1:
2018-06-17 08:44:20.755 UTC [33] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2018-06-17 08:44:20.755 UTC [33] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2018-06-17 08:44:20.755 UTC [33] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2018-06-17 08:44:20.937 UTC [33] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2018-06-17 08:44:21.249 UTC [34] LOG:  database system was interrupted; last known up at 2018-06-17 08:17:55 UTC
pg_ctl: server did not start in time
```
### Information
  - Windows Version: 8.1
  - Docker for Windows Version: Toolbox 18.03.0-ce, build 0520e24302

### Steps to reproduce the behavior
It is working from Ubuntu!
[More info](https://stackoverflow.com/questions/50895190/docker-did-not-start-postgres-server)

**Comment by wglambert** [comment]
```dockerfile
FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
  postgresql \
  libpq-dev \
  git \
  wget
RUN wget -qO- https://get.haskellstack.org/ | sh
RUN git clone https://github.com/begriffs/postgrest.git
WORKDIR postgrest
RUN stack build --install-ghc --copy-bins --local-bin-path /usr/local/bin
ADD init.sh /init.sh
ADD pgrest.conf /pgrest.conf
ADD init.sql /init.sql
RUN chmod u+x /init.sh
WORKDIR /
USER postgres
RUN /etc/init.d/postgresql start &&\
 psql --command "CREATE USER appname_admin WITH PASSWORD 'appname' LOGIN SUPERUSER;" &&\
 psql --command "CREATE USER appname_user WITH PASSWORD 'appname' LOGIN;" &&\
 createdb -O appname_admin appname &&\
 psql appname < /init.sql
USER root
ENTRYPOINT sh /init.sh
EXPOSE 3000
```

Your image doesn't build for me
```console
$ docker build . -t appname
Sending build context to Docker daemon   2.56kB
Step 1/17 : FROM ubuntu
 ---> 113a43faa138
Step 2/17 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 951585419af6
Step 3/17 : RUN apt-get update && apt-get install -y   postgresql   libpq-dev   git   wget
 ---> Using cache
 ---> f4ef97c805e9
Step 4/17 : RUN wget -qO- https://get.haskellstack.org/ | sh
 ---> Using cache
 ---> 3cba6253da13
Step 5/17 : RUN git clone https://github.com/begriffs/postgrest.git
 ---> Using cache
 ---> 26dfb0a4d8fc
Step 6/17 : WORKDIR postgrest
 ---> Using cache
 ---> da414bdd9e36
Step 7/17 : RUN stack build --install-ghc --copy-bins --local-bin-path /usr/local/bin
 ---> Running in 50588db00a88
Downloading lts-9.6 build plan ...
Downloaded lts-9.6 build plan.
Preparing to install GHC to an isolated location.
. . .
text-printer-0.5: download                                                   
text-printer-0.5: configure                                                  
text-printer-0.5: build                                                      
The command '/bin/sh -c stack build --install-ghc --copy-bins --local-bin-path /usr/local/bin' returned a non-zero code: 137
```

Also the image is `FROM ubuntu` which we don't maintain. This image also doesn't appear to be an issue with the ubuntu image either; you could also try [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)

If it works on an ubuntu host then perhaps you could look into any anomalous behavior with Docker for Windows. However there's nothing we can help you with.

**Comment by LettyCoach** [comment]
The above error occurs.
Please check my Dockerfile:

---DockerFile---

#---------------------------------
# For Docker
#---------------------------------
FROM ubuntu:22.04


#---------------------------------
# For Ubuntu
#---------------------------------
#シェル指定
SHELL ["/usr/bin/bash", "-l", "-c"]

#初回のアップデートを強制
RUN apt update && apt upgrade -y

#最低限のメンテナンスツール
#2回目以降のapt installでも毎回updateをして、dockerの差分buildによるキャッシュの悪さを回避する
RUN apt-get update && apt-get install -y ca-certificates curl dnsutils gnupg gnupg2 htop iputils-ping lsb-release net-tools sqlite3 vim wget lftp



#---------------------------------
# For PostgreSQL
#---------------------------------
ENV TZ=Asia/Tokyo
ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP:ja
ENV LC_ALL=ja_JP.UTF-8


#無人インストール化
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y locales-all
RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN apt-get update && apt-get install -y postgresql-15

#初期設定
USER postgres
RUN /etc/init.d/postgresql start && \
        psql -c "alter user postgres with encrypted password 'postgres'" && \
        psql -c "create user docker with password 'docker' superuser;" && \
        psql -c "create database docker owner docker;" && \
        psql -d docker -c "create schema authorization docker;" && \
        psql -c "create role readonly with login password 'readonly';" && \
        psql -c "grant pg_read_all_data to readonly;"
RUN echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/15/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/15/main/postgresql.conf
USER root

#ポート解放
EXPOSE 5432


#---------------------------------
# For .NET 6
# Ubuntu22.04から公式レポジトリ経由での取得が可能
#---------------------------------
# RUN apt-get update && apt-get install -y dotnet6


#---------------------------------
# For .NET 7
#---------------------------------
RUN wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb
#RUN apt-get update && apt-get install -y apt-transport-https
RUN apt-get update && apt-get install -y dotnet-sdk-7.0 aspnetcore-runtime-7.0


#---------------------------------
# For Docker
#---------------------------------
#コンテナ起動時に各サービス・プロセスを起動
COPY ./startup.sh /startup.sh
RUN chmod 744 /startup.sh
STOPSIGNAL SIGINT
ENTRYPOINT /startup.sh


------startup.sh---------
#!/bin/sh

#終了処理
handle(){
  /etc/init.d/fcgiwrap stop
  /etc/init.d/ngix stop
  /etc/init.d/postgresql stop
  exit 0
}
trap handle TERM INT

#起動処理
# /usr/libexec/tomcat9/tomcat-start.sh &
# /usr/bin/node /mnt/bind/nodejs/webserver.js &
# /etc/init.d/fcgiwrap start
# /etc/init.d/nginx start
/etc/init.d/postgresql start
/bin/bash
