### ISSUE TITLE
su-exec: /usr/local/bin/docker-entrypoint.sh: Permission denied

### ISSUE THREAD

**Issue by StrategistXIV** [docker-library/postgres#467]
Hello guys,

I have seen that there were already issues with this error message, but the solutions there did not work for me, since I run the plain image without any modifications

When I run the following commands:

`docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword postgres:alpine`

`docker run --name some-postgres --privileged=true -e POSTGRES_PASSWORD=mysecretpassword postgres:alpine`

`docker run --name some-postgres --privileged=true -e POSTGRES_PASSWORD=mysecretpassword --user=root postgres:alpine`

I keep getting the error message:

> su-exec: /usr/local/bin/docker-entrypoint.sh: Permission denied

I am using a custom daemon.json file for my Docker instance:

```
    "debug": true,

    "max-concurrent-downloads": 10,
    "max-concurrent-uploads": 10,

    "init": false,

    "experimental": false,

    "default-shm-size": "64M",
    "shutdown-timeout": 15,
    "oom-score-adjust": -500,

    "hosts": ["tcp://0.0.0.0:2375", "fd://"],
    "tls": true,
    "tlscacert": "/etc/docker/ca.pem",
    "tlscert": "/etc/docker/cert.pem",
    "tlskey": "/etc/docker/key.pem",
    "tlsverify": true,

    "storage-driver": "overlay2",
    "storage-opts": [],

    "live-restore": false,

    "log-level": "info",
    "log-driver": "json-file",
    "log-opts": {
      "max-size": "10m",
      "max-file": "2"
    },
    "raw-logs": false,

    "mtu": 0,

    "userland-proxy": false,
    "userland-proxy-path": "/usr/libexec/docker-proxy",

    "selinux-enabled": false,
    "no-new-privileges": false
```

I am wondering what I am doing wrong, maybe I need some kind of setting in my daemon.json in order for it to work?

___________________________

EDIT: I tried running Docker without daemon.json as well, but I still get the same result.

**Comment by StrategistXIV** [comment]
I found the issue, it was on my side: I basically set some permissions on some docker protected files which were not  supposed to be there. Thanks for your effort :+1:

**Comment by askasp** [comment]
Sorry for necroing, but i got the exactly same problem. What docker protected files had you changed permissions on?

**Comment by Cornichon622** [comment]
Had the same issue, I had set `force_mask` to `private` in the `storage.options.overlay` table of Podman's `storage.conf` file.

Note that I had to delete Podman's runroot and graphroot directory each time I made a change to this config file, otherwise it doesn't apply.
