### ISSUE TITLE
Upgrade docker image to 10.5 version?

### ISSUE THREAD

**Issue by pedrofurtado** [docker-library/postgres#477]
As soon as possible, upgrade the docker image to 10.5 version ( https://github.com/postgres/postgres/releases/tag/REL_10_5 ) :tada:

**Comment by code-chris** [comment]
This version is unreleased right now. The 09.08.2018 seems to be the release-date:
https://github.com/postgres/postgres/commit/9468474902fa90cf533211d7e8011a11328bae3f#diff-37c53107dd94322c089d58a0b668293fR9

**Comment by macropin** [comment]
It's released!

**Comment by yosifkit** [comment]
https://github.com/docker-library/postgres#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

:wink: https://github.com/docker-library/official-images/pull/4713
