### ISSUE TITLE
Image deletes Data Volume when started

### ISSUE THREAD

**Issue by planctron** [docker-library/postgres#491]
Using the current 9.4 image we suffered data loss while recreating the container.
The init scripts should not allow overwriting of data when starting with a non empty container.

Background: We use Portainer as container admin and used the feature "recreate".
The last recent volume was suggested for a new start.
We would have chosen this volume since we wanted to use our recent db content.
The data was lost. 
It appears, the volume was initialized, which is a VERY UNEXPECTED step!

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue.

From https://github.com/docker-library/postgres/issues/203#issuecomment-255200501
>The postgres user, and database creation only happens on the first start (ie, /var/lib/postgresql/data must not already contain database files).

**Comment by yosifkit** [comment]
Yeah, the initialization of database files is only done when the it doesn't detect an already initialized database:

https://github.com/docker-library/postgres/blob/2337858365ada252da545b4a280a0fe89579d47e/docker-entrypoint.sh#L56-L57

On top of that, the `initdb` command from PostgreSQL used to create the init database files fail to run if the volume is already full:

```console
$ docker run -it --rm --user postgres postgres bash
postgres@deb6ad38b101:/$ cd /var/lib/postgresql/data/
postgres@deb6ad38b101:~/data$ ls -l
total 0
postgres@deb6ad38b101:~/data$ initdb --username=postgres
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

postgres@deb6ad38b101:~/data$ ls -l
total 112
drwx------ 5 postgres postgres  4096 Aug 30 17:29 base
drwx------ 2 postgres postgres  4096 Aug 30 17:29 global
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_commit_ts
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_dynshmem
-rw------- 1 postgres postgres  4513 Aug 30 17:29 pg_hba.conf
-rw------- 1 postgres postgres  1636 Aug 30 17:29 pg_ident.conf
drwx------ 4 postgres postgres  4096 Aug 30 17:29 pg_logical
drwx------ 4 postgres postgres  4096 Aug 30 17:29 pg_multixact
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_notify
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_replslot
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_serial
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_snapshots
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_stat
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_stat_tmp
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_subtrans
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_tblspc
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_twophase
-rw------- 1 postgres postgres     3 Aug 30 17:29 PG_VERSION
drwx------ 3 postgres postgres  4096 Aug 30 17:29 pg_wal
drwx------ 2 postgres postgres  4096 Aug 30 17:29 pg_xact
-rw------- 1 postgres postgres    88 Aug 30 17:29 postgresql.auto.conf
-rw------- 1 postgres postgres 22729 Aug 30 17:29 postgresql.conf
postgres@deb6ad38b101:~/data$ initdb --username=postgres
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: directory "/var/lib/postgresql/data" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data" or run initdb
with an argument other than "/var/lib/postgresql/data".
```

**Comment by planctron** [comment]
Well, thank you.
If the line below is part of the documentation, it would not count as a  bug.
But please!?
This causes a very dangerous situation since when Creating a container with
a -v(olume) option,  it would be natural thing to use an existing directory.

The correct behaviour would be to REFUSE a start and point out that the
volume must be unused !!

Don't you agree?

Do you still need specifics?

Gregor



On 8/30/18, wglambert <notifications@github.com> wrote:
> Can you give all the commands you ran and any relevant contextual
> information or files for reproducing the issue.
>
> From
> https://github.com/docker-library/postgres/issues/203#issuecomment-255200501
>>The postgres user, and database creation only happens on the first start
>> (ie, /var/lib/postgresql/data must not already contain database files).
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/docker-library/postgres/issues/491#issuecomment-417383998


-- 
Gregor Huyskens
+49.621.9535.4066
+66.94.648.2451
+49.1573.202.9428

**Comment by tianon** [comment]
That's exactly what the image does (as explained and proven by @yosifkit above) -- if you provide a volume that includes data, the container will either start postgres using that existing data or will fail to start the container.

What's happened in your case is unrelated to this image -- did you use `--rm` when you started your container?  Did you name your volume?  Was your volume deleted by Portainer or Docker somehow?  Did you actually attach the volume you thought you did?

Regardless, the image already behaves exactly as you've described, so even though we're sorry this has happened to you, there's really nothing we can do (or could've done) to help you prevent it (it was an operator error or bug in Portainer somewhere).

**Comment by planctron** [comment]
I appreciate your detailed and quick response to my report.
I will try to reproduce the situation.
I was sure  to have attached the same volume - even if I admit there
is room for error since
the names used were uuids which I compared only by a few characters is
mostly enough.
All my volumes have clearly distinct names.
I will search for the cause with a simple repetition.

Sorry if I fell into any trap and spoiled your time.
Thank you for your great work to support postgresql!

Gregor


On 8/30/18, Tianon Gravi <notifications@github.com> wrote:
> That's exactly what the image does (as explained and proven by @yosifkit
> above) -- if you provide a volume that includes data, the container will
> either start postgres using that existing data or will fail to start the
> container.
>
> What's happened in your case is unrelated to this image -- did you use
> `--rm` when you started your container?  Did you name your volume?  Was your
> volume deleted by Portainer or Docker somehow?  Did you actually attach the
> volume you thought you did?
>
> Regardless, the image already behaves exactly as you've described, so even
> though we're sorry this has happened to you, there's really nothing we can
> do (or could've done) to help you prevent it (it was an operator error or
> bug in Portainer somewhere).
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/docker-library/postgres/issues/491#issuecomment-417409435


-- 
Gregor Huyskens
+49.621.9535.4066
+66.94.648.2451
+49.1573.202.9428
