### ISSUE TITLE
Container failed to exit within 10 seconds of signal 15 - using the force

### ISSUE THREAD

**Issue by Mapteg34** [docker-library/postgres#503]
Problems with postgres containers on stop dockerd:
INFO[2018-09-26T08:52:48.801870920+03:00] Container 6d6215c65b6dc5938748fbdc8a66c69c0a6840a5585f8e414714d85d2013e0cf failed to exit within 10 seconds of signal 15 - using the force 
INFO[2018-09-26T08:52:48.803440591+03:00] Container 28fd985fed66ff8c5fbdc2a3b841b38df7f54d097273c7b75c6112c2339df108 failed to exit within 10 seconds of signal 15 - using the force 
INFO[2018-09-26T08:52:48.807968327+03:00] Container 87ed44d6487e1f4e9159668a14239289a2f5e066f4309e603ed2a50e0341c0de failed to exit within 10 seconds of signal 15 - using the force 
INFO[2018-09-26T08:52:48.823489364+03:00] Container 1e129391e73d3bdd5868931c6aa0b9d58b5908b184c3f566497904848b4d16e4 failed to exit within 10 seconds of signal 15 - using the force

Any way to increase limits or decrease time of postgresql stopping operation?

**Comment by wglambert** [comment]
https://docs.docker.com/v17.09/engine/reference/commandline/stop/

`-t 30` would give you a grace period of 30

**Comment by tianon** [comment]
You can also use `--stop-timeout` when you run the container to provide a bigger default for the container itself (so you don't have to remember to use a bigger timeout when running `docker stop`).

**Comment by Shrimant** [comment]
Hi...For me, the timeout set was 30seconds and I still got into this issue. Version: 19.03.5. Windows version: Windows Server 2016; AWS AMI: Base Windows Server 2016 image.
