### ISSUE TITLE
small issue with keyserver

### ISSUE THREAD

**Issue by ggmartins** [docker-library/postgres#518]
Just a heads up with a small issue I had and fixed but replacing the keyservers url:

https://github.com/docker-library/postgres/blob/master/11/Dockerfile#L31

It works with
```&& gpg --keyserver  hkp://p80.pool.sks-keyservers.net:80```
Thanks to @tianon for
https://github.com/tianon/gosu/issues/17

**Comment by tianon** [comment]
See also https://github.com/docker-library/official-images/issues/4252.

We use a server in front of the gossip servers via DNS hijack which makes it a lot more reliable on the whole (discussed/linked from that thread).
