### ISSUE TITLE
An ability to run sh/sql each start (like docker-entrypoint-initdb.d)

### ISSUE THREAD

**Issue by viatsyshyn** [docker-library/postgres#542]
For example /docker-entrypoint.d/ folder with scripts that execute each start (maintenance, db schema migrations, health checks, etc). DB server should be started like in case with docker-entrypoint-initdb.d

**Comment by tianon** [comment]
See https://github.com/docker-library/postgres/pull/496, which when finalized will allow you to implement this without much code (I swear there was another issue about this very thing, but I can't find it right now 😅).

**Comment by viatsyshyn** [comment]
@tianon, yes this definitely addresses my case. Hope that makes to master soon. Also I'd vote for quick way to drop in a script (like docker-entrypoint-always.d).
