### ISSUE TITLE
The POSTGRESQL_ADMIN_PASSWORD  env variable

### ISSUE THREAD

**Issue by tahv0** [docker-library/postgres#567]
Hi,

Is the POSTGRESQL_ADMIN_PASSWORD environment variable still in use? Or has it ever been?
I added it to my docker-compose.yml based on some tutorial, but then it seems that there is no such a variable at all?

Possibly duplicate with https://github.com/docker-library/postgres/issues/565

**Comment by wglambert** [comment]
I don't think we've ever used that env var name

[`POSTGRES_PASSWORD`](https://github.com/docker-library/docs/tree/master/postgres#postgres_password) is what you're looking for, and setting the `POSTGRES_USER` will change the superuser account from using the default "postgres" user

**Comment by faust64** [comment]
For those ending up here with a similar question: the `POSTGRESQL_ADMIN_PASSWORD` is a thing you may have seen OpenShift, as they use a different Postgres image (centos/postgresql-12-centos7, centos/postgresql-10-centos7, ....or the older used to be named openshift/postgresql-92-centos7).
