### ISSUE TITLE
Pre-migrated images

### ISSUE THREAD

**Issue by nightscape** [docker-library/postgres#57]
I wanted to do some pre-migrations as part of the build so that the container can start quicker in tests.
AFAIS this is not currently possible, as `/var/lib/postgresql/data` is specified as a `VOLUME` and during `docker build` all changes to the `VOLUME`s seem to be no-ops. In contrast, first creating a directory and later mounting that same directory as `VOLUME` will copy all files over.

See this minimal example, first with the `VOLUME` being mounted at the end
```
Step 0 : FROM debian:wheezy

Step 1 : RUN mkdir /myvol

Step 2 : RUN ls -lah /myvol
total 8.0K
drwxr-xr-x  2 root root 4.0K Apr 22 23:27 .
drwxr-xr-x 29 root root 4.0K Apr 22 23:27 ..

Step 3 : RUN echo "hello world" > /myvol/greeting

Step 4 : RUN ls -lah /myvol
total 12K
drwxr-xr-x  2 root root 4.0K Apr 22 23:27 .
drwxr-xr-x 30 root root 4.0K Apr 22 23:27 ..
-rw-r--r--  1 root root   12 Apr 22 23:27 greeting

Step 5 : VOLUME /myvol

Step 6 : RUN ls -lah /myvol
total 12K
drwxr-xr-x  2 root root 4.0K Apr 22 23:27 .
drwxr-xr-x 30 root root 4.0K Apr 22 23:27 ..
-rw-r--r--  1 root root   12 Apr 22 23:27 greeting
```
Now, when you mount the VOLUME already at the beginning:
```
Step 0 : FROM debian:wheezy

Step 1 : VOLUME /myvol

Step 2 : RUN ls -lah /myvol
total 8.0K
drwxr-xr-x  2 root root 4.0K Apr 22 23:29 .
drwxr-xr-x 29 root root 4.0K Apr 22 23:29 ..

Step 3 : RUN echo "hello world" > /myvol/greeting

Step 4 : RUN ls -lah /myvol
total 8.0K
drwxr-xr-x  2 root root 4.0K Apr 22 23:29 .
drwxr-xr-x 29 root root 4.0K Apr 22 23:29 ..
```

Do you see any way around this or another possibility to perform operations on the DB that make it into the image (vs. being executed only on `docker run`)?

**Comment by md5** [comment]
You might explore changing the default datadir to another path.

**Comment by tianon** [comment]
Indeed, I believe @jpetazzo had success with just changing "PGDATA" ("ENV
PGDATA ..." or "-e PGDATA=...").

**Comment by nightscape** [comment]
OK, setting PGDATA works nicely.
Does anyone know by any chance why Docker behaves this way?
I can first add things into directory and have stuff copied when I issue the `VOLUME` directive, but when I do the `VOLUME` thing too early, all changes are lost. Seems rather unintuitive...

**Comment by jpetazzo** [comment]
As it happens, this might explain what is happening:
http://jpetazzo.github.io/2015/01/19/dockerfile-and-data-in-volumes/

Let me know what you think?

On Thu, Apr 23, 2015 at 5:17 AM, Martin Mauch <notifications@github.com>
wrote:

> OK, setting PGDATA works nicely.
> Does anyone know by any chance why Docker behaves this way?
> I can first add things into directory and have stuff copied when I issue
> the VOLUME directive, but when I do the VOLUME thing too early, all
> changes are lost. Seems rather unintuitive...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker-library/postgres/issues/57#issuecomment-95566373>
> .
>



-- 
@jpetazzo <https://twitter.com/jpetazzo>
"Is it safe to run applications into containers?"
http://www.slideshare.net/jpetazzo/docker-linux-containers-lxc-and-security

**Comment by md5** [comment]
Great post @jpetazzo

**Comment by nightscape** [comment]
@jpetazzo: nice article!
Explanations and work-arounds for this issue are good enough for me, so I'll close it :)
