### ISSUE TITLE
Docker build failed version 10.7 Step 5/24

### ISSUE THREAD

**Issue by amrrus** [docker-library/postgres#572]
Docker build failed with version 10 of Dockerfile into step 5/24

**Comment by wglambert** [comment]
Step 5 is package installation and verification with `gpg`, if you try building the image a few more times it will probably work

https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035
>TLDR; GPG servers are extremely flaky . . .

This is what we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749

**Comment by wglambert** [comment]
See also https://github.com/docker-library/faq#openpgp--gnupg-keys-and-verification
