### ISSUE TITLE
Image reports that it's "up" before it's actually listening

### ISSUE THREAD

**Issue by rdowne** [docker-library/postgres#58]
If I have a docker compose file, listing a server that must talk to postgres, and a postgres instance, linked together, docker starts the service that depends on postgres before postgres has finished starting. 

Log excerpt attached.  Current workaround is to include a "sleep 5 &&" prefixed to the start command for the application server, but this is very much non-ideal.

db_1    | PostgreSQL stand-alone backend 9.3.6
db_1    | backend> backend> 
db_1    | PostgreSQL stand-alone backend 9.3.6
db_1    | backend> backend> 
db_1    | PostgreSQL stand-alone backend 9.3.6
db_1    | backend> backend> 
db_1    | PostgreSQL stand-alone backend 9.3.6
db_1    | backend> backend> 
db_1    | PostgreSQL stand-alone backend 9.3.6
app_1   | 2015-04-22 23:46:12,445 INFO success: flask_server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app_1   | 2015-04-22 23:46:12,445 INFO success: cache_syncd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
db_1    | backend> backend> 
db_1    | PostgreSQL stand-alone backend 9.3.6
db_1    | backend> backend> 
db_1    | PostgreSQL stand-alone backend 9.3.6
db_1    | backend> backend> 
db_1    | PostgreSQL stand-alone backend 9.3.6
db_1    | backend> backend> 
db_1    | PostgreSQL stand-alone backend 9.3.6
db_1    | backend> backend> LOG:  database system was shut down at 2015-04-22 23:46:13 UTC
db_1    | LOG:  database system is ready to accept connections
db_1    | LOG:  autovacuum launcher started

**Comment by md5** [comment]
Docker considers the container to be "up" as soon as the process starts. There isn't a mechanism for that process to tell Docker that it has actually started listening on a port.

You may have better luck modifying your application or the Docker image you're using to run it to wait until the database is available. Here's how that's handled in the `wordpress` image: https://github.com/docker-library/wordpress/blob/d7be0b140da5e9ccddd0eab818e89e088ab1d5ef/docker-entrypoint.sh#L123-L134
