### ISSUE TITLE
default Collate/Ctype 

### ISSUE THREAD

**Issue by hellower** [docker-library/postgres#587]
Postgesql 's default 
Collate/Ctype is 'en_US.utf8';

Instead of Ctype = en_US.utf8
How about changing to Collate / Ctype = C?

I think that
Outside of non-English speaking countries,
this default collate / ctype is not used at all.

reference.
https://simply.name/pg-lc-collate.html
https://justatheory.com/2004/08/postgres-always-use-c-locale/

sorry for poor english.

**Comment by wglambert** [comment]
On database initialization you can set the `LANG` environment variable to configure locales, such as `LANG=C`

```console
$ docker run -d --rm --name postgres -e LANG=C -e MYSQL_ROOT_PASSWORD=pass postgres
5c09f95d1506b87b91dc6835effdda2c2e9b5dc37a929054ef34a0f52d0898cc

$ docker exec -it postgres psql -U postgres
psql (11.1 (Debian 11.1-1.pgdg90+1))
Type "help" for help.

postgres=# SELECT name, setting FROM pg_settings WHERE category ~ 'Locale';
            name            |      setting       
----------------------------+--------------------
 client_encoding            | SQL_ASCII
 DateStyle                  | ISO, MDY
 default_text_search_config | pg_catalog.english
 extra_float_digits         | 0
 IntervalStyle              | postgres
 lc_collate                 | C
 lc_ctype                   | C
 lc_messages                | C
 lc_monetary                | C
 lc_numeric                 | C
 lc_time                    | C
 server_encoding            | SQL_ASCII
 TimeZone                   | UTC
 timezone_abbreviations     | Default
(14 rows)

```

https://github.com/docker-library/docs/tree/master/postgres#locale-customization

**Comment by hellower** [comment]
I do know about this.  (initialization).
It was suggested that changing the default value would not require regenerating the database.
Anyway, thanks

**Comment by wglambert** [comment]
Yeah it looks like if you do that then your indexes could be out of order 
https://www.postgresql.org/message-id/2705.1499704920%40sss.pgh.pa.us

But this isn't something we would mess with on an already initialized database
