### ISSUE TITLE
escaping issue on docker overview page

### ISSUE THREAD

**Issue by xzilla** [docker-library/postgres#593]
On the main dockerhub page for postgres (https://hub.docker.com/_/postgres) the example code for the initialization script has an escape for `<--eosql`, however the matching closing tag seems to be missing. I say seems to because in the license section, there is a `</-eosql>` at the very end of that section which doesn't seem to correspond to anytihing; perhaps that is somehow the missing close from above? 

As a side note, the Readme.md file in the github repo does not seem to have this issue.

**Comment by yosifkit** [comment]
That is definitely a Docker Hub rendering issue and not, as you note, a problem with the source (https://github.com/docker-library/docs/tree/234b40a4e97ddda04f8f247ba348343e851c8ab8/postgres#initialization-scripts).

There is nothing we can do directly, but you could try raising an issue at https://github.com/docker/hub-feedback
