### ISSUE TITLE
Strange failures in latest builds of the docker images of 9, 10 and 11

### ISSUE THREAD

**Issue by slapers** [docker-library/postgres#594]
We are seeing strange failures on the latest builds of the docker images which can be reproduced using the following procedure:

```
docker run -d --name pgfailure -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=admin postgres:10.9
docker exec -it pgfailure psql -U admin

CREATE TABLE failer_table
(
    id   uuid NOT NULL CONSTRAINT failer_table_pkey PRIMARY KEY,
    col1 uuid,
    col2 uuid,
    col3 varchar(255),
    col4 boolean,
    col5 uuid
);

CREATE INDEX failer_table_col4_index ON failer_table (col4);
CREATE INDEX failer_table_col5_index ON failer_table (col5);

ALTER TABLE "failer_table" 
 ALTER COLUMN "col1" TYPE uuid, 
 ALTER COLUMN "col1" SET NOT NULL, 
 ALTER COLUMN "col2" TYPE uuid, 
 ALTER COLUMN "col2" SET NOT NULL, 
 ALTER COLUMN "col3" TYPE varchar(255), 
 ALTER COLUMN "col3" SET NOT NULL, 
 ALTER COLUMN "col4" TYPE boolean, 
 ALTER COLUMN "col4" SET DEFAULT false, 
 ALTER COLUMN "col5" TYPE uuid, 
 ALTER COLUMN "col5" SET NOT NULL;
```

Running this agains all the latest docker builds gives:
```
ERROR:  relation "failer_table_col4_index" already exists
```

We can reproduce this problem on all latest tags: `9.6.14`, `10.9`, `11.4`
The issue does not occur when testing against the previous builds: `9.6.13`, `10.8`, `11.3`

We did not test any of the other builds.

**Comment by wglambert** [comment]
This also affects the Alpine variant; looking at the upstream changes between two affected versions:
https://www.postgresql.org/docs/release/11.4/
https://www.postgresql.org/docs/release/10.9/

This change seems most related 

- Fix failure of `ALTER TABLE ... ALTER COLUMN TYPE` when the table has a partial exclusion constraint (Tom Lane)

**Comment by felicianotech** [comment]
I believe this is affecting CircleCI users as well who are using images based off these images.

**Comment by tomdcc** [comment]
FYI this is [PG bug 15865](https://www.postgresql.org/message-id/905.1561076455%40sss.pgh.pa.us) which will be fixed in the next patch releases, whenever those happen.

**Comment by wglambert** [comment]
Release notes for 9.6.15 https://www.postgresql.org/docs/9.6/release-9-6-15.html
10.10 https://www.postgresql.org/docs/10/release-10-10.html
11.5 https://www.postgresql.org/docs/11/release-11-5.html

- Fix failure of ALTER TABLE ... ALTER COLUMN TYPE when altering multiple columns' types in one command (Tom Lane)
This fixes a regression introduced in the most recent minor releases: indexes using the altered columns were not processed correctly, leading to strange failures during ALTER TABLE.

Closing with the merge of https://github.com/docker-library/official-images/pull/6430
