### ISSUE TITLE
Missing 12.1 and 12.1-alpine tags

### ISSUE THREAD

**Issue by stevo-knievo** [docker-library/postgres#634]
Postgres 12.1 was released on the 14th of November 2019. Unfortunately, I can't find the tags for the 12.1 release on [docker hub](https://hub.docker.com/_/postgres).
I saw the [Dockerfile](https://github.com/docker-library/postgres/blob/master/12/Dockerfile) for version 12 got updated to `12.1-1.pgdg100+1`. I deleted my local container image and pulled the latest container: `docker pull postgres:latest`. Then I ran the following command: `SELECT version();`

`PostgreSQL 12.0 (Debian 12.0-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit`

Mabey I do something wrong. Local container caching issue? I also tried removing all stopped containers: `docker system prune -a`.

I'm more than happy to do a PR to getting the tags online on [docker hub](https://hub.docker.com/_/postgres). But unfortunately, I need a little bit assists.

Thanks in advance

**Comment by tianon** [comment]
See https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what and https://github.com/docker-library/official-images/pull/6989.

**Comment by stevo-knievo** [comment]
Thanks a lot for your quick response @tianon and the Infos. I had no idea how the whole process works, thanks again. I really appreciate all your work and every contributor's work. You guys doing an amazing job.
