### ISSUE TITLE
Release 9.2.10, 9.3.7 and 9.4.2 tags on official repo

### ISSUE THREAD

**Issue by Kwastie** [docker-library/postgres#64]
Not sure where to report this issue..

The readme at https://registry.hub.docker.com/_/postgres/ suggests that the 9.2.10, 9.3.7 and 9.4.2 tags are available, but they aren't.

The code was changed 4 days ago, but no builds where created (or pushed).

**Comment by yosifkit** [comment]
Looks like we got ahead of the pushes with the docs updates.  They are pushing as I type.  They were added to the official images build server with https://github.com/docker-library/official-images/pull/752.

**Comment by yosifkit** [comment]
They should hopefully be up within the next hour.

**Comment by Kwastie** [comment]
Thanks, images are available!
