### ISSUE TITLE
Still timezone

### ISSUE THREAD

**Issue by vosonwang** [docker-library/postgres#640]
I know volume isn't empty then the entrypoint doesn't run and my data doesn't get modified

It works fine with an empty database directory

but when I try this in datagrid,not in container:

show timezone ;

   TimeZone   
--------------
UTC

😢

(container)
$ docker exec -it postgres psql -Upostgres
psql (11.6 (Debian 11.6-1.pgdg90+1))
Type "help" for help.

postgres=# show timezone;
   TimeZone   
--------------
 Asia/Jakarta
(1 row)

**Comment by wglambert** [comment]
Use the `TZ` environment variable to set the timezone

https://github.com/docker-library/postgres/issues/610#issuecomment-533616603
