### ISSUE TITLE
postgres:12.0-alpine upgrade to postgres:12.1-alpine double size

### ISSUE THREAD

**Issue by hyperniklas** [docker-library/postgres#651]
Is there any reason for the size increase from 12.0-alpine **72.8 MB** to 12.1-alpine **146.2 MB**?

**Comment by wglambert** [comment]
`Postgres:11.6-alpine` and `12.1-alpine` now include support for JIT compilation https://github.com/docker-library/postgres/pull/643

https://github.com/docker-library/postgres/issues/475
