### ISSUE TITLE
Problems installing packages on Alpine based images

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker-library/postgres#654]
I'm using the 9.6 Alpine Dockerfile and I wanted to install some extra packages.

```dockerfile
FROM postgres:9.6-alpine

RUN set -eux \
    && apk add --no-cache \
        postgresql-contrib-$PG_MAJOR
```

When I build this image, I get an awkward APK error:

```
$ docker build --tag example .
...
+ apk add --no-cache postgresql-contrib-9.6
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  postgresql-contrib-9.6 (missing):
    required by: world[postgresql-contrib-9.6]
```

When I search in the [package repository](https://pkgs.alpinelinux.org/packages?name=postgresql-contrib&branch=v3.10&arch=x86_64), I notice that the only postgresql-contrib package is version 11.6. This [StackOverflow answer](https://superuser.com/a/1486407) explains (emphasis mine)

> Unfortunately, Alpine-Linux Package Management **_drops older packages_** when there are newer versions available. This makes is hard to use Alpine Linux with docker since you want a reproducible image with exact versions.

Is this a problem (either the version mismatch or the fact that your [specific Alpine version](https://github.com/docker-library/postgres/blob/0d0485cb02e526f5a240b7740b46c35404aaf13f/9.6/alpine/Dockerfile#L2) does not contain the "correct" package version)?

**Comment by wglambert** [comment]
The Alpine Dockerfile downloads the source from https://ftp.postgresql.org/pub/source/ and builds that
https://github.com/docker-library/postgres/blob/0d0485cb02e526f5a240b7740b46c35404aaf13f/9.6/alpine/Dockerfile#L35

It also does a `make -C contrib install`
https://github.com/docker-library/postgres/blob/0d0485cb02e526f5a240b7740b46c35404aaf13f/9.6/alpine/Dockerfile#L83-L114

**Comment by AnthonyMastrean** [comment]
Oh, neat. So you handled everything already, then?

**Comment by wglambert** [comment]
Yep, you should have everything on https://github.com/postgres/postgres/tree/REL9_6_16/contrib
```console
$ docker run -d --rm --name postgres postgres:9.6
925b8909dd2ccbf363ff33df751f5aff1dc3b3116001b5a252508b68b11f64c8

$ docker exec -it postgres psql -Upostgres
psql (9.6.16)
Type "help" for help.

postgres=# create extension cube;
CREATE EXTENSION
postgres=# create extension earthdistance;
CREATE EXTENSION
postgres=# SELECT * FROM earth();
  earth  
---------
 6378168
(1 row)
```
