### ISSUE TITLE
/var/run/postgresql no longer writable when run as arbitrary user

### ISSUE THREAD

**Issue by michitux** [docker-library/postgres#659]
Commit [48f2ad1b](https://github.com/docker-library/postgres/commit/48f2ad1b73abdfe08d0e4e3feb4934177929d9b5#diff-60713fb19f6c50a2473835df63ff17f9) changes `docker-entrypoint.sh` to execute some code for changing permissions regardless if the current user is root or not. In particular, the line `chmod 775 /var/run/postgresql || :` is now executed. While before this line `/var/run/postgresql` is world-writable, afterwards it is no longer world-writable and the lock file creation fails. I am surprised that `chmod` succeeds in this case, but I can reproduce this when manually starting a shell in the container:

```
# docker run -it --user 1000:1000 arm64v8/postgres:11 /bin/bash
I have no name!@fec45e7ef731:/$ ls -la /var/run/postgresql/
total 2
drwxrwsrwx 1 postgres postgres 1024 Dec 28 17:07 .
drwxr-xr-x 1 root     root     1024 Dec 28 17:07 ..
I have no name!@fec45e7ef731:/$ chmod 775 /var/run/postgresql/
I have no name!@fec45e7ef731:/$ touch /var/run/postgresql/foo
touch: cannot touch '/var/run/postgresql/foo': Permission denied
```

Before the `chmod` call, the `touch` succeeds, but when I first create a file in the directory, the `chmod` fails as expected. I cannot reproduce this outside of the container (there, the chmod fails) so I suspect that this is a bug of the docker overlay on this host system (LibreELEC on an arm box with linux 3.14). Nevertheless, it would be great if `docker-entrypoint.sh` could be changed to execute the `chmod` only if the owner can be fixed/is correct.

**Comment by yosifkit** [comment]
It sounds like something is wrong about that Docker or host setup. When I try to chmod `/var/run/postgresql` as a user that is not `postgres` (the owner, `999`) or `root`, it fails. As far as I understand it, that is the way that `chmod` is supposed to work: 

> Only a process whose effective user ID matches the user ID of the file, or a process with appropriate privileges, is permitted to change the file mode bits of a file.
> 
> \- [gnu.org](https://www.gnu.org/software/coreutils/manual/html_node/chmod-invocation.html#chmod-invocation)

```console
docker run -it --rm --user 1000:1000 postgres:11 bash
I have no name!@0d957fd8f99a:/$ ls -la /var/run/postgresql/
total 8
drwxrwsrwx 1 postgres postgres 4096 Nov 15 23:35 .
drwxr-xr-x 1 root     root     4096 Nov 15 23:35 ..
I have no name!@0d957fd8f99a:/$ chmod 775 /var/run/postgresql/
chmod: changing permissions of '/var/run/postgresql/': Operation not permitted
I have no name!@0d957fd8f99a:/$

$ docker run -it --rm --user 999:999 postgres:11 bash
postgres@2baf66005f42:/$ ls -lan /var/run/postgresql/
total 8
drwxrwsrwx 1 999 999 4096 Nov 15 23:35 .
drwxr-xr-x 1   0   0 4096 Nov 15 23:35 ..
postgres@2baf66005f42:/$ chmod 775 /var/run/postgresql/
postgres@2baf66005f42:/$ ls -lan /var/run/postgresql/
total 12
drwxrwsr-x 1 999 999 4096 Nov 15 23:35 .
drwxr-xr-x 1   0   0 4096 Nov 15 23:35 ..
postgres@2baf66005f42:/$ 

```

**Comment by wglambert** [comment]
Closing since this seems resolved
