### ISSUE TITLE
12.1-alpine - sh: locale: not found

### ISSUE THREAD

**Issue by mb-dbc-dk** [docker-library/postgres#660]
During startup of the 12.1-alpine it logs:

```
running bootstrap script ... ok
performing post-bootstrap initialization ... sh: locale: not found
$timestamp$ [29] WARNING:  no usable system locales were found
```

Not really sure of the consequences of this. But it does worry.

**Comment by wglambert** [comment]
https://github.com/docker-library/postgres/issues/501#issuecomment-423565105
>Alpine is based on musl which doesn't have locales.
