### ISSUE TITLE
Building image from Dockerfile behind proxy: fail on gpg --recv-keys

### ISSUE THREAD

**Issue by jjclavijo** [docker-library/postgres#671]
Hi

When trying to build the postgres image from Dockerfile, running behind http proxy and despite proper docker configuration, i will fail on receiving gpg keys with the following output:

```
+ gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
gpg: keybox '/tmp/tmp.JJpMHuFUjB/pubring.kbx' created
gpg: keyserver receive failed: Connection timed out
```

I am able to handle this by adding ```--keyserver-options http-proxy=$http_proxy``` on each required line from de Dockerfile (i can even manage its automation for mantaining a local modifyed Dockerfile). I am just wondering: if this change or some variant can be harmlessly added to the official Dockerfiles, it will reduce the ammount of "docker behind proxy" googling when triying to base an image on a slightly modified version of the official image (like those Volume-less versions discussed on other issues).

There are some related issues like #288 #262 etc. and #443, collapsing on somthing like: "you should pull the built image". I think that there are valid use cases for building slightly modified images, and reducing needed modifications leads to less bugs.

Javier Clavijo.

**Comment by tianon** [comment]
It doesn't discuss this *exact* issue (of downloading via proxy), but it's very similar, so I'd recommend you check out https://github.com/docker-library/faq#openpgp--gnupg-keys-and-verification (one of the solutions there could very likely work for your use case too).

**Comment by jjclavijo** [comment]
It's in fact very similar. i'll try it --next week-- and post some notes for future reference before closing the issue. Just for clarification: https://github.com/tianon/rawdns should do the trick, hijacking DNS and redirecting the GET request trough $http_proxy, no pgp-happy-eyeballs needed. Am i right?

I thought that running the build itself from inside a container with the docker socket bind-mounted, and redirecting the full http traffic for that container should be a feasible (perhaps not better nor easyer) solution.

**Comment by tianon** [comment]
No, `rawdns` itself will not solve the problem because you actually need something to proxy the traffic through your `http_proxy` (`rawdns` will just allow you to munge the DNS replies however you please, which would allow you to transparently redirect the keyserver requests to something that *does* respect your `http_proxy` environment variable, thus making your build process independent of your http proxy).

**Comment by wglambert** [comment]
Closing since this seems resolved
