### ISSUE TITLE
Default postgres user cannot login or run commands

### ISSUE THREAD

**Issue by KevinAtSesam** [docker-library/postgres#674]
Affects [Postgres 9.6 - alphine](https://hub.docker.com/layers/postgres/library/postgres/9.6-alpine/images/sha256-3a1d32d67fff9d004a8fb50cbb4c7854dca176a9624ea12ba1bb9a5321e8eac1?context=explore)

In a recent change, the default postgres user gets a home folder. Fine in theory, but it has the unfortuante side effect of defining the default shell as `/sbin/nologin`. This means that you can no longer login as a postgres user.

the easiest way to fix this, is by running a quick sed on /etc/passwd
```
su root -c "sed -i -e 's|postgresql:/sbin/nologin|postgresql:/bin/ash|g' /etc/passwd"
```

A more constructive solution would be to set the shell using --shell (-s)

**Comment by yosifkit** [comment]
Will be fixed by https://github.com/docker-library/postgres/pull/669
