### ISSUE TITLE
Version '9.6.16-1.pgdg90+1' for 'postgresql-9.6' was not found

### ISSUE THREAD

**Issue by beatak** [docker-library/postgres#676]
```
apt-get install -y postgresql-9.6=9.6.16-1.pgdg90+1 postgresql-contrib-9.6=9.6.16-1.pgdg90+1
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '9.6.16-1.pgdg90+1' for 'postgresql-9.6' was not found
```

related to https://www.postgresql.org/docs/9.6/release-9-6-17.html?

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

```console
$ docker run -it --rm postgres:9.6 bash

root@3610430d0fcd:/# echo postgresql-$PG_MAJOR=$PG_VERSION
postgresql-9.6=9.6.16-1.pgdg90+1

root@3610430d0fcd:/# apt-get install -y postgresql-9.6=9.6.16-1.pgdg90+1 postgresql-contrib-9.6=9.6.16-1.pgdg90+1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
postgresql-contrib-9.6 is already the newest version (9.6.16-1.pgdg90+1).
postgresql-9.6 is already the newest version (9.6.16-1.pgdg90+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
Our image includes upstream's repo which contains those packages
https://github.com/docker-library/postgres/blob/16dd8dbf87af47f280cf784aac8f2afb7a24c383/12/Dockerfile#L84-L86

**Comment by beatak** [comment]
I did the following command:

`9.6 % docker build --tag p:9.6 . > postgres.txt 2>&1`

and the result is https://gist.github.com/beatak/5e9fa5b99cf95876dc3227aaca5cf6bb

**Comment by yosifkit** [comment]
That looks like they updated their package today; the `Packages` was updated at "2020-Feb-13 12:48:31" (http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/9.6/binary-amd64/).  And indeed the Packages now has `9.6.17` in it instead of `9.6.16`.  The automated `update.sh` should pick this up soon and commit the changes to the repo.
