### ISSUE TITLE
Could I donate or be a sponsor?

### ISSUE THREAD

**Issue by eleijonmarck** [docker-library/postgres#688]
Hello,

Wanted to express my gratitude for making the postgres image available and maintained.
Is there a donate/sponsor button for postgres in general?

**Comment by yosifkit** [comment]
Thank you!

@tianon, @wglambert, and I appreciate the sentiment. This is currently part of our day job at InfoSiftr and the Official Images program is made possible by Docker, Inc.

Upstream PostgreSQL has a donate page (postgresql.org/about/donate/). Or I'd recommend donating to or helping your favorite tech charity (like womenwhocode.com). We are not affiliated with either.
