### ISSUE TITLE
ERROR:  function uuid_generate_v4() does not exist

### ISSUE THREAD

**Issue by AlexZeitler** [docker-library/postgres#69]
I ran this:
````
begin;
create extension "uuid-ossp";
create table products (product_id  uuid primary key default uuid_generate_v4());
create table orders   (order_id    uuid primary key default uuid_generate_v4(),
                      product_id   uuid references products not null);
````

But I get `ERROR:  function uuid_generate_v4() does not exist` 

Are the contrib modules and extensions installed with this image?

**Comment by yosifkit** [comment]
Is this in a `postgres --single`? `create extension` doesn't work in postgres single user mode (https://stackoverflow.com/questions/28147177/do-create-extension-work-in-single-user-mode-in-postgres).

**Comment by md5** [comment]
@yosifkit Only extensions that create custom types and expect to be able to use the implicit array types will fail. Other extensions that don't do that, including `uuid-ossp`, should work.

I just tried what @AlexZeitler tried to run with a Postgres 9.4 image and did not receive that error.

**Comment by md5** [comment]
Also, in this case there will not be an implicit `uuid[]` type for later use in table definitions and elsewhere.

**Comment by md5** [comment]
@AlexZeitler How did you run that? I ran it in a `psql` shell, not in `postgres --single` mode as @yosifkit mentioned.

**Comment by md5** [comment]
I just tested this with `postgres --single` and it worked fine. I'm wondering whether you're trying to run `uuid_generate_v4()` in a different database than the one that `CREATE EXTENSION` was run against.

**Comment by AlexZeitler** [comment]
@md5 I mapped the ports to my host and used pgAdminIII on the host.

**Comment by AlexZeitler** [comment]
Thanks @yosifkit, @md5 

Looks like I did something wrong.

I logged into the container and tried psql and it worked.
After that I tried it again using JetBrains 0xDBE and when selecting all statements and adding `end;` as well and then executing all selected statements everything works fine.

**Comment by AlexMesser** [comment]
I have this error on postgres docker running on windows. Same tests with exactly same codebase and docker postgres image works fine on osx.

**Comment by rivanbello** [comment]
This problem occurred to me when I tried to run migrations without being a super user.
I used the docker to create the container, I created a user with a custom name, thus losing the super user power.
Then I recreated the container without defining a name for the user (the default is "postgres"), I just defined the password, so everything worked fine to run the migrations.

**Comment by GitVijayDv** [comment]
sudo yum install postgres*contrib
sudo apt install postgres-contrib
