### ISSUE TITLE
issues seen using postgres 10 images published 2020-02-21

### ISSUE THREAD

**Issue by patrickattnt** [docker-library/postgres#690]
At some point Friday we began encountering issues using the postgres 10 images (postgres:10 and postgres:10.12). These issues could be fixed by reverting to the images published 21 days ago on docker hub (postgres:10.11)

On application startup, our postgres container began to error:
`
invalid value for parameter "lc_messages": "en_US.utf8"
invalid value for parameter "lc_monetary": "en_US.utf8"
invalid value for parameter "lc_numeric": "en_US.utf8"
invalid value for parameter "lc_time": "en_US.utf8"
configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
postgres exited with code 1
`

- we were able to work around these errors by adjusting our Dockerfile, regenerating the locales:
RUN apt-get update && \
apt-get install -y locales locales-all && \                                                                                                                                                        dpkg-reconfigure locales locales-all && \                                                                                                                                                                          locale-gen && \                                                                                                                                                                                                    locale-gen en_US.UTF-8 && \                                                                                                                                                                                        localedef -i en_US -f UTF-8 en_US.UTF-8 && \
...

At this point the postgres container would start with no errors. 

However, we noticed that other containers within the overlay network were then unable to connect to the container - while port 5432 was exposed, an nmap showed the port wasn't open from the dependent container. Connecting to the postgres container over localhost from the postgres container itself worked and was unaffected.

For the moment we reverted to the images published 2020-02-02.

**Comment by wglambert** [comment]
Seems similar to https://github.com/docker-library/postgres/issues/552
And another similar issue https://github.com/docker-library/postgres/issues/415, `localedef -i en_US -f UTF-8 en_US.UTF-8` fixed it

Is there a simple docker run line that demonstrates the issue easily so we can dig into it more?

**Comment by patrickattnt** [comment]
@wglambert I apologize - I need to close this as essentially user error. 

The cause ended up being a bad extension of the image within the Dockerfile - we extended the image, but also performed an 'apt-get upgrade -y' - this messed up locales, config. Caching of the build images, failing to rebuild also contributed to the problem. 

Thank you for linking.
