### ISSUE TITLE
Wrong message: 'The files belonging to this database system will be owned by user "postgres".'

### ISSUE THREAD

**Issue by desmap** [docker-library/postgres#698]
Set both user and db via env vars to 'root' which worked (checked within the running container) but still getting owned by user "postgres" on every initialization as message. I tested this with multiple refreshes (removed data dir and did a docker system prune -a). Also when in psql: db postgres is owned by root. No big issue , just confusing.

Is this intended?

**Comment by yosifkit** [comment]
> Set both user and db via env vars to 'root' which worked

Which variables/config are you talking about here?  Please share exact `docker run` or `docker-compose` file and any relevant commands ran.

---

Just guessing in the dark, you set `POSTGRES_USER=root` and `POSTGRES_DB=root`?  Then that is the user within the database.  The message you mention is from postgres (or maybe `initdb`?) and refers to the Linux system user (from `/etc/passwd` in the image) that the postgres daemon runs as and so all database files have to be owned by that user id.

**Comment by desmap** [comment]
> Which variables/config are you talking about here? Please share exact `docker run` or `docker-compose` file and any relevant commands ran.

I wrote *[I] set both user and db via env vars to 'root' * which is my exact compose-file:
```
...
    environment:
      POSTGRES_PASSWORD: somepassword
      POSTGRES_USER: root
      POSTGRES_DB: root
...

> Just guessing in the dark, you set `POSTGRES_USER=root` and `POSTGRES_DB=root`? Then that is the user within the database. The message you mention is from postgres (or maybe `initdb`?) and refers to the Linux system user (from `/etc/passwd` in the image) that the postgres daemon runs as and so all database files have to be owned by that user id.

Ok, think this makes sense, maybe a note in the Docker Image's README would create less confusion because the context of this message is not really clear.

@wglambert IDK if my issue was a real question or rather a rhetoric one about a confusing UI and/or docs.
