### ISSUE TITLE
In a where clause, the equals operator doesn't work well for basic queries.

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [docker-library/postgres#704]
11.7-alpine version exhibits this strange behaviour:

```
# select '[' || lis_lis || ']' from imalis where lis_lis like 'PME_USU_00'; 
   ?column?   
--------------
 [PME_USU_00]
(1 row)
```
whereas:
```
# select '[' || lis_lis || ']' from imalis where lis_lis = 'PME_USU_00'; 
 ?column? 
----------
(0 rows)
```
Non-Docker Postgres 11 shows consistent results with exactly the same data (rsync'ed), i.e., 1 row of results for both selects.

`lis_lis` is a `varying char(20)` column that is the primary key of the table.
Using:

- amd64
- Docker version 19.03.6-ce, build 369ce74
- Host is Amazon Linux.

**Comment by DavidPerezIngeniero** [comment]
Version `11.6-alpine` also has same bug.

**Comment by wglambert** [comment]
Do you know if it does this in the non-Alpine variant too?

**Comment by DavidPerezIngeniero** [comment]
I cannot test because the debian variant doesn't support the `es-ES.UTF-8` locale.

**Comment by DavidPerezIngeniero** [comment]
Confirmed that Debian variant works ok.

**Comment by wglambert** [comment]
Yeah it doesn't seem like something we can change at our level, probably have to file it upstream somewhere

https://github.com/docker-library/docs/tree/master/postgres#postgresversion-alpine
>The main caveat to note is that it does use [musl libc](http://www.musl-libc.org) instead of [glibc and friends](http://www.etalabs.net/compare_libcs.html), so certain software might run into issues depending on the depth of their libc requirements.

**Comment by yosifkit** [comment]
Seems related to https://github.com/docker-library/postgres/issues/327
