### ISSUE TITLE
Running under podman, anyone running locally can login without a password

### ISSUE THREAD

**Issue by GeoffWilliams** [docker-library/postgres#720]
**Overview**

I'm running under [podman](https://podman.io/) instead of docker and am able to login with no password despite setting `POSTGRES_PASSWORD` and `POSTGRES_HOST_AUTH_METHOD`. This works from the host as well as other containers running under docker.

**Steps to reproduce**

```
$ podman --version
podman version 1.9.0
$ podman run --rm -p 5432:5432 --name devdb \
		-e POSTGRES_PASSWORD=topsecret \
		-e POSTGRES_HOST_AUTH_METHOD=md5 \
		postgres:12.2
```

Allows access with no password from host/containers with:

```
$ psql -h localhost -p 5432 -U postgres
psql (12.2 (Ubuntu 12.2-2.pgdg19.10+1))
Type "help" for help.

postgres=#
```

**Expected result**

Expect to be asked for a password which is what happens when running under docker:

```
$ docker run --rm -p 5432:5432 --name devdb \
		-e POSTGRES_PASSWORD=topsecret \
		-e POSTGRES_HOST_AUTH_METHOD=md5 \
		postgres:12.2
```

...

```
$ psql -h localhost -p 5432 -U postgres
Password for user postgres: 
```

**Workarounds**

I suspect this is due to podman configuring the network differently to docker such that more connections then usual appear to be _local_ according to `pg_hba.conf`.

I was able to fix this by using `docker` command instead of `podman`. Another approach might be to re-work `pg_hba.conf`.

**Comment by tianon** [comment]
Yep, this is (unfortunately) by design -- `localhost` is a trusted interface by default and as you've noted, changing `pg_hba.conf` is the appropriate way to change that.

**Comment by GeoffWilliams** [comment]
That's what I was suspecting. Maybe this can be captured in the readme somewhere to avoid catching someone by surprise? Thanks for confirming.

**Comment by yosifkit** [comment]
Already there:

> Note 1: The PostgreSQL image sets up trust authentication locally so you may notice a password is not required when connecting from localhost (inside the same container). However, a password will be required if connecting from a different host/container.
>
> \- https://github.com/docker-library/docs/tree/167ed72c42d34fd2f48257aab238dea3b1867589/postgres#postgres_password
