### ISSUE TITLE
All linux AMD / ppc64 postgres images are hosed due to a file rename from postgresql.org

### ISSUE THREAD

**Issue by freelake** [docker-library/postgres#724]
When trying to start up my containers from your Postgres 11.6 docker image (which has worked for more than half a year) I am now seeing this due to a few file renames on posgresql.org.

Details below:

Cannot open: https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7.6-ppc64le/pgdg-centos11-11-2.noarch.rpm. Skipping.

Postgres changed that file as of May 3 2020 Sunday night:

https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7.6-ppc64le/pgdg-centos11-11-2.noarch.rpm

needs to be:

https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7.6-ppc64le/pgdg-redhat-repo-latest.noarch.rpm

**Comment by tianon** [comment]
None of our images pull or use any `.rpm` files in any way, so I think you'll have to be more specific about what it is you're doing that's failing? :confused:

**Comment by freelake** [comment]
Ahh ok. Perhaps I have the wrong group. What I'm trying to say is that
anyone whom tries to use an AMD based Linux postgres 10.x or 11.x docker
image
from here: https://hub.docker.com/_/postgres

Will simply not be able to actually bring that container up. This will be
due specifically to a change made just the other day by Postgresql as
listed in
the issue above. Sorry about that.

**Comment by freelake** [comment]
The full docker-compose .yml i'm using which has been working the last 6
months until i found that change mentioned.

version: '3.5'

services:
  postgres:
    image: postgres:11.6
    container_name: postgres
    volumes:
      - /tmp/dotomi/pgdata:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 3s
      retries: 3
    networks:
      - docker_default

**Comment by freelake** [comment]
Please resolve this. I found the issue. Thanks for the help.
