### ISSUE TITLE
POSTGRES_DB not functioning?

### ISSUE THREAD

**Issue by tomerpaz76** [docker-library/postgres#727]
when creating a pod using this image (version 11), 
with user other than postgres,
the container starts and creates the db with the other user name I defined, and ignores the environment variable POSTGRES_DB.
I exec into the container and saw the env variable is set properly. tried also running the docker-entrypoint.sh to try creating it manually. nothing.

I looked at the script and saw this in latest master version:
POSTGRES_DB= docker_process_sql --dbname postgres --set db="$POSTGRES_DB" <<-'EOSQL'

isn't the space after "DB= " a bug?
anyway, according to documentation, if POSTGRES_DB is defined, the database to be created shall be the name defined by this environment variable.

**Comment by wglambert** [comment]
>creates the db with the other user name I defined, and ignores the environment variable POSTGRES_DB.

How is the variable being ignored when the DB is created?

```console
$ docker run -d --rm -e POSTGRES_DB=test -e POSTGRES_USER=testuser -e POSTGRES_PASSWORD=pass postgres:11
9aab0e1bdaed9bedba747eea89b144643b1eeefc9a6535d5d2917684a4b4d13b

$ docker exec -it 9aa psql -U testuser -d test
psql (11.7 (Debian 11.7-2.pgdg90+1))
Type "help" for help.

test=# \l
 postgres  | testuser | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | testuser | UTF8     | en_US.utf8 | en_US.utf8 | =c/testuser          +
           |          |          |            |            | testuser=CTc/testuser
 template1 | testuser | UTF8     | en_US.utf8 | en_US.utf8 | =c/testuser          +
           |          |          |            |            | testuser=CTc/testuser
 test      | testuser | UTF8     | en_US.utf8 | en_US.utf8 |
```

**Comment by tomerpaz76** [comment]
I should have supplied more context: I have tested it on K8S, with a
timescaledb image over this image (but the script and base image are the
same)
strange how it works in docker cli but not in k8s.
