### ISSUE TITLE
Why is "postgres" db created when specifying POSTGRES_DB with a different name

### ISSUE THREAD

**Issue by srmo** [docker-library/postgres#730]
Using tag 12

Hi, I'm specifying POSTGRES_DB with a value different from the default value "postgres".
After initialisation, I see that my DB has been created (without schema) but there's also the "postgres" db with a public schema. How and why is this happening? I was expecting to see only *my* database after initialisation.
I'm new to postgres so I might be missing somthing here?

**Comment by wglambert** [comment]
https://www.postgresql.org/docs/9.1/app-initdb.html
>The postgres database is a default database meant for use by users, utilities and third party applications.

**Comment by srmo** [comment]
Oh, sorry for the delay. Thanks for the pointer. It still seems counter intuitive as this section also refers to the db created as the user under which it is running. Which is "postgres" in the image. This feels confusing when the param states that POSTGRES_DB will be the name of the database.
I'll think about that a little bit more to see if I just got the wrong mindset. Feel free to close this issue in the meantime.
