### ISSUE TITLE
Update to 12.3, 11.8, 10.13, 9.6.18, and 9.5.22

### ISSUE THREAD

**Issue by decaz** [docker-library/postgres#733]
https://www.postgresql.org/about/news/2038/

**Comment by yosifkit** [comment]
The bot got them now, thanks. Like https://github.com/docker-library/postgres/commit/f1e039c4ebd8e4691af65dfd6cf280df126039aa.

https://github.com/docker-library/postgres#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet
