### ISSUE TITLE
Public Key Failure for apt.postgresql.org on 9.1 Image

### ISSUE THREAD

**Issue by theory** [docker-library/postgres#737]
In `postgres:9.1` image:

```
apt-get -qq update && apt-get -qq install build-essential postgresql-server-dev-$PG_MAJOR
There is no public key available for the following key IDs:
AA8E81B4331F7F50
GPG error: http://apt.postgresql.org jessie-pgdg InRelease: The following signatures were invalid: KEYEXPIRED 1562078959
WARNING: The following packages cannot be authenticated!
  libpq5 libpq-dev postgresql-server-dev-9.1
here are problems and -y was used without --force-yes
```

Can the key be updated in older version images?

As seen in [this workflow](/theory/pg-hostname/runs/707237090)

**Comment by theory** [comment]
Also true of the 8.4 images (as seen in [this workflow](/theory/colnames/runs/707273319).

**Comment by wglambert** [comment]
Postgres 9.1 was deprecated October 2016 , which was also when we deprecated that version of the image. And Debian Jessie loses LTS in a month, so without something of extreme security importance there isn't a sufficiently good reason to try and resurrect/refresh that version
https://github.com/docker-library/faq#what-do-you-mean-by-supported

https://www.debian.org/releases/jessie/
>Jessie also benefits from Long Term Support (LTS) until the end of June 2020.

**Comment by theory** [comment]
Still useful for testing extensions that continue to support older versions, though. Note that this isn't an issue for 9.0, just 8.4 and 9.1 (at the moment anyway).

**Comment by yosifkit** [comment]
Unfortunately there isn't anything we can do for these old unsupported images.  You can just tell apt to ignore gpg signatures (https://askubuntu.com/a/74389). Alternatively, you can see if upstream postgres would push an update to the key, but that seems unlikely since they are no longer supported by them (and you'd be responsible for getting the updated key into your own image).

**Comment by theory** [comment]
Thanks.

**Comment by df7cb** [comment]
Hi,
I've recently published updated PostgreSQL packages for all older major versions down to 8.4, so you can install these on any modern distribution release like buster.
No need to stick with wheezy (8.4) or jessie (9.1). Perhaps the Docker images can just switch to that.

Regarding the actual issue, the expired key has been updated in pgdg-keyring I believe. Is that image perhaps using an outdated version of that package?

Christoph

**Comment by yosifkit** [comment]
Thanks for commenting @df7cb. Yeah the images in question were dropped a while back, so they definitely have old keys in them.

**Comment by theory** [comment]
Should those docker images be deleted, then?

**Comment by yosifkit** [comment]
We don't delete old images from the Docker Hub; they are left for historical purposes.  The Hub readme always lists the currently supported set (i.e. tags that get updates or rebuilt on new base images to incorporate security updates).

**Comment by theory** [comment]
Yeah, it's just a shame that it means that there are outdated images available and no one can tell at a glance that they won't work. Thinking I'll update my GitHub Workflow to use a plain old Linux docker container and `apt-get` (or `yum install`) the versions of Postgres I need.
