### ISSUE TITLE
password issue

### ISSUE THREAD

**Issue by luboi75** [docker-library/postgres#739]
latest image exits immediately after starting unless you explicitly define -e POSTGRES_PASSOWRD=password 
logs states, you must define password, however (according to all of my attempts) unless the value equals to password, your container exists. **effectively there is no way to choose password at all** which BTW equals to no password

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

`-e POSTGRES_PASSOWRD=password` has a typo, so if you copied that from terminal that'd be the issue

>unless the value equals to password, your container exists.

If you mean 'exits' then I can't reproduce

```console
$ docker run -d --rm --name postgres -e POSTGRES_PASSWORD=testpass postgres
8d857fff8dc0d20772746e3a1d8cbc04c1f7c519c235751c066939a410351920

$ docker exec -it postgres psql -U postgres
psql (12.3 (Debian 12.3-1.pgdg100+1))
Type "help" for help.

postgres=#
```

**Comment by yosifkit** [comment]
> This optional variable can be used to control the `auth-method` for `host` connections for `all` databases, `all` users, and `all` addresses. If unspecified then [`md5` password authentication](https://www.postgresql.org/docs/current/auth-password.html) is used. On an uninitialized database, this will populate `pg_hba.conf` via this approximate line:
> 
> ```console
> echo "host all all all $POSTGRES_HOST_AUTH_METHOD" >> pg_hba.conf
> ```
> 
> See the PostgreSQL documentation on [`pg_hba.conf`](https://www.postgresql.org/docs/current/auth-pg-hba-conf.html) for more information about possible values and their meanings.
> 
> **Note 1:** It is not recommended to use [`trust`](https://www.postgresql.org/docs/current/auth-trust.html) since it allows anyone to connect without a password, even if one is set (like via `POSTGRES_PASSWORD`). For more information see the PostgreSQL documentation on [*Trust Authentication*](https://www.postgresql.org/docs/current/auth-trust.html).
> 
> **Note 2:** If you set `POSTGRES_HOST_AUTH_METHOD` to `trust`, then `POSTGRES_PASSWORD` is not required.

https://github.com/docker-library/docs/tree/5e2c9cad0ded3ca38fbe9687b6e4ca6e7a149e01/postgres#postgres_host_auth_method
