### ISSUE TITLE
Database initialization scripts exec order

### ISSUE THREAD

**Issue by win32nipuh** [docker-library/postgres#744]
I have copied a test mydb.sql to the directory
`/docker-entrypoint-initdb.d`

and it works fine.

Now I'd like to create my demo db and insert data. I have
```
mydb_1_struct.sql -- there is db tructure
mydb_2_data.sql -- there is db data

```
I need to execute these scripts in strong order: structure and then data.
What is the order of the scripts execution ?

**Comment by wglambert** [comment]
The files are located by [globbing](http://tldp.org/LDP/abs/html/globbingref.html) which will be alpha-numerically sorted

https://github.com/docker-library/postgres/blob/9586595a9bded3c7cde8682d95db9d79dc0d9ca3/13/docker-entrypoint.sh#L152-L171

As a test you can do something like:
```console
$ for i in *; do echo $i; done
mydb_1_struct.sql
mydb_2_data.sql
```

But it can be unexpected at times such as:
```console
$ mv mydb_1_struct.sql mydb_10_struct.sql

$ for i in *; do echo $i; done
mydb_10_struct.sql
mydb_2_data.sql
```

**Comment by Oleg26Dev** [comment]
Finally it is even  simpler:
The multiple scripts executed by alphabetical order, i.e. 
```
01_structure.sql
02_data.sql
03_transform.sql

```
