### ISSUE TITLE
Setting up Replicas

### ISSUE THREAD

**Issue by allcentury** [docker-library/postgres#754]
Feature Request:

It be great if there was an out-of-the-box solution to use replicas with this image.  As it stands there are [a few blog posts](https://www.optimadata.nl/blogs/3/nlm8ci-how-to-run-postgres-on-docker-part-3) on this but offering a docker-compose set up would reduce reinventing the wheel and struggling with out of date blog posts.

**Comment by tianon** [comment]
I agree it would be really nice if we could come up with a good out-of-the-box solution, but I don't think there's a clear "simple" solution, and even upstream's documentation on the subject (https://www.postgresql.org/docs/12/high-availability.html) admits that this topic is a fairly complex one with *many* solutions that have differing tradeoffs, so I think it would unfortunately be very presumptuous for us to pick one and implement it here.  On top of that, most solutions require some kind of outside coordinator, and are difficult to implement in a generic way reliably. :disappointed:
