### ISSUE TITLE
library/postgres:12.4 image non functional

### ISSUE THREAD

**Issue by rjbrown57** [docker-library/postgres#755]
Unable to pull library/postgres:12.4

Attempted with Docker version 19.03.8, build afacb8b7f0 and Docker version 19.03.12, build 48a66213fe

```
docker pull library/postgres:12.4
12.4: Pulling from library/postgres
no matching manifest for linux/amd64 in the manifest list entries
```

On the docker hub page the OS/ARCH field is empty for 12.4 while being populated for 12.3 / 12.3 etc

**Comment by yosifkit** [comment]
https://github.com/docker-library/postgres#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

TLDR: they were still building (some architectures are now pushed up)
