### ISSUE TITLE
`psql` command could not resolve host IP based on the service name provided from docker compose

### ISSUE THREAD

**Issue by MayurDhande-GSLab** [docker-library/postgres#769]
Hello, 
From a different container I am trying to connect to a docker container that is running the `postgres` container.
My command looks like this,
`psql -h db-service -U postgres`
whereas `db-service` is the name my service from docker-compose.

On running this command I am getting this. It seems, psql relies on the `/etc/hosts` entry, but I don't want to do that.
```
psql: could not connect to server: Connection refused
        Is the server running on host "db-service" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
```

Although I could connect to the postgres container using the actual IP. 
But is there any way for psql to resolve the dbhost based on the service name ?

**Comment by wglambert** [comment]
I'm not able to reproduce, psql hostname resolution works with Docker container hostnames

```console
$ docker run -d --rm --name postgres --network pg -e POSTGRES_PASSWORD=pass postgres
d469cfbb5394e5b5f9d6db843ce6be121494a3bcfe7499391d0ca9834e9fe3ea

$ docker run -it --rm --network pg postgres bash

root@359da7539040:/# psql -h postgres -U postgres
Password for user postgres: 
psql (13.0 (Debian 13.0-1.pgdg100+1))
Type "help" for help.

postgres=#
```

**Comment by MayurDhande-GSLab** [comment]
My bad @wglambert , I had an existing entry `db-service 127.0.0.1` in /etc/hosts file (without any db server running on local), 
Hence it was trying to connect to localhost.
Thanks anyways 👍
