### ISSUE TITLE
Unable to run postgres container on Ubuntu 15.04

### ISSUE THREAD

**Issue by Lev09** [docker-library/postgres#77]
I tried to run postgres container on Ubuntu 14.04 and it worked fine, but when i tried to run on Ubuntu 15.04 server i got error:

/docker-entrypoint.sh: line 94: kill: (59) - No such process
PostgreSQL init process failed

**Comment by russellhaering** [comment]
What was the solution to this?

**Comment by Lev09** [comment]
Solution for me was to use *.sql file instead of *.sh to init my database.
