### ISSUE TITLE
Missing --with-systemd flag on alpine builds

### ISSUE THREAD

**Issue by yangm97** [docker-library/postgres#774]
This prevents using `Type=notify` on systemd units when the container is managed by some tool which allow passing through the `$NOTIFY_SOCKET` (such as podman).

**Comment by tianon** [comment]
That's really interesting, I didn't know there were runtimes which support this!  I'm +1 to adding it to our build flags. :+1:

**Comment by genevieve-me** [comment]
I'd be interested in this, even though https://github.com/Artox/alpine-systemd is still experimental. I'm just going to switch to a debian build for my use case (passing through the notification to podman, same as the grandparent) but I wonder if it would be possible to reopen this?
