### ISSUE TITLE
Question: how to upgrade? because pg_dumpall seems to be missing

### ISSUE THREAD

**Issue by romu70** [docker-library/postgres#775]
Hi,
It's more a question than an issue.

I've been running the 11.1-alpine image for a few years now, and it works like a charm. But I'm thinking about upgrading my container to the new 13.0.

I've found some tutos online about such an upgrade process of a PG container which advice to run ```pg_dumpall``` from the old container, and then import this dump file into the new one.

Problem is the 11.1-alpine doesn't contain the ```pg_dumpall```, AFAIK, so how to proceed?

Thanks.

**Comment by wglambert** [comment]
There's a long discussion on this over at https://github.com/docker-library/postgres/issues/37

Tianon has a repo with upgrade-containers that invoke [pg_upgrade](https://www.postgresql.org/docs/11/upgrading.html#UPGRADING-VIA-PG-UPGRADE) 
https://github.com/tianon/docker-postgres-upgrade
Postgres [documentation](https://www.postgresql.org/docs/11/upgrading.html#UPGRADING-VIA-PG-UPGRADE) on `pg_upgrade`

https://github.com/docker-library/postgres/issues/37#issuecomment-404598989
>There actually is support for migrating data files in PostgreSQL, it's called [pg_upgrade](https://www.postgresql.org/docs/current/static/pgupgrade.html). The Docker container is special in that it's difficult to use this support because it needs both the older and the newer versions installed on the same system. The Docker container isn't set up to work this way. Alternately, you can also look into replication if you have large data sets or absolutely can't have any downtime. Options are actually discussed on this [official documentation page](https://www.postgresql.org/docs/current/static/upgrading.html).

**Comment by romu70** [comment]
Thanks a lot for such a quick answer.
