### ISSUE TITLE
Runnin with --user 10000:10000 and mounted /etc/passwd:/etc/passwd:ro does not work:  chmod: /var/lib/postgresql/data: Operation not permitted

### ISSUE THREAD

**Issue by kopax** [docker-library/postgres#780]
Hi all, I am trying to start the container with `--user` as explained in the [readme](https://hub.docker.com/_/postgres).

I have mounted the volume with `/etc/passwd:/etc/passwd:ro`.

When I create a new container, I have the following error :  

    chmod: /var/lib/postgresql/data: Operation not permitted

How can I start a container with `--user` without perms issues ?

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/postgres#arbitrary---user-notes

I think you may have missed a few steps in that section:
```console
$ docker run -it --rm -v pgdata:/var/lib/postgresql/data -e POSTGRES_PASSWORD=mysecretpassword postgres
. . .
2020-10-28 17:13:27.459 UTC [1] LOG:  database system is ready to accept connections
^C
2020-10-28 17:13:31.368 UTC [1] LOG:  received fast shutdown request
2020-10-28 17:13:31.369 UTC [1] LOG:  aborting any active transactions
2020-10-28 17:13:31.376 UTC [1] LOG:  background worker "logical replication launcher" (PID 61) exited with exit code 1
2020-10-28 17:13:31.376 UTC [56] LOG:  shutting down
2020-10-28 17:13:31.399 UTC [1] LOG:  database system is shut down

$ docker run -it --rm -v pgdata:/var/lib/postgresql/data bash chown -R 10000:10000 /var/lib/postgresql/data

$ docker run -d --rm --name postgres --user 10000:10000 -v pgdata:/var/lib/postgresql/data postgres
df5de0883104528a431a2e3c750983a632213a2fb75ba0591c18d05e0aa02909

$ docker run -it --rm --pid container:postgres tianon/network-toolbox bashroot@aa1b3b4343a8:/# ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
10000         1  0.8  0.0 213880 26644 ?        Ss   17:20   0:00 postgres
10000        13  0.0  0.0 213880  4064 ?        Ss   17:20   0:00 postgres: checkpointer
10000        14  0.0  0.0 213880  5756 ?        Ss   17:20   0:00 postgres: background writer
10000        15  0.0  0.0 213880  5808 ?        Ss   17:20   0:00 postgres: walwriter
10000        16  0.0  0.0 214432  6828 ?        Ss   17:20   0:00 postgres: autovacuum launcher
10000        17  0.0  0.0  68244  4796 ?        Ss   17:20   0:00 postgres: stats collector
10000        18  0.0  0.0 214312  6764 ?        Ss   17:20   0:00 postgres: logical replication launcher
root         19  2.5  0.0   3864  3272 pts/0    Ss   17:20   0:00 bash
root         25  0.0  0.0   7636  2740 pts/0    R+   17:20   0:00 ps aux
```

**Comment by kopax** [comment]
You must manually fix the permissions once ? Is it completely impossible to create it with the right permissions in one `docker run` step ?

**Comment by tianon** [comment]
Unfortunately, if you run the container with an unprivileged user, it cannot fix the permissions of the (root-owned) data volume automatically.

**Comment by yosifkit** [comment]
Unfortunately, yes. Or you need to provide a bind mount folder (e.g. `-v /local/path/:/var/lib/postgresql/data`) that already exists with the correct ownership/permissions.

**Comment by kopax** [comment]
Got it, it's probably the original design, too bad it cannot be fixed properly for such a powerful service. Thanks !

**Comment by tianon** [comment]
Yeah, this is a Linux kernel limitation; there's really nothing we can do. :disappointed:

**Comment by pnelson** [comment]
I believe I read the documentation the same way. To me, it reads as if option 2 is one of three valid options to work around the `initdb` caveat and it isn't because it cannot fix the permissions `/var/lib/postgresql/data`.

**Comment by rnantes** [comment]
@wglambert are you saying in the docs: https://github.com/docker-library/docs/tree/master/postgres#arbitrary---user-notes that these are 3 steps in one solution and NOT 3 approaches.

**Comment by tianon** [comment]
If you want to run the container as a non-root user, you *must* fix the permissions of the volume you supply beforehand -- if we aren't running as root, we **cannot** fix the permissions for you (that's kind of the whole point of running as a non-root user to begin with).

Other than that, the three points documented there are three separate approaches to working around *the `initdb` bug* specifically (not generally every issue you might encounter while trying to run as an arbitrary user). :+1:
