### ISSUE TITLE
kdevtmpfsi process consuming cpu on postgres:13 image

### ISSUE THREAD

**Issue by DmitriyStoyanov** [docker-library/postgres#798]
From some time, we faced with 100% cpu usage on server with posgres:13 image used, it goes from this process
in top we have:
29153 999       20   0  515548 264328      0 S 92.4 52.9   3:25.10 kdevtmpfsi

it comes from postgres process:
ps -ef|grep 29153
999      29153 28324 97 10:20 ?        00:08:15 /tmp/kdevtmpfsi

ps -ef|grep 28324
999      28324 28307  0 10:09 ?        00:00:00 postgres

Looks like the same issue as redis https://github.com/docker-library/redis/issues/217
also described here https://stackoverflow.com/questions/60151640/kdevtmpfsi-using-the-entire-cpu

**Comment by DmitriyStoyanov** [comment]
Faced with such attack with default password on db

**Comment by tianon** [comment]
Indeed - as you've noted, this is an unfortunate consequence of having a public-facing instance with a compromised (or simple) password. :disappointed:

However, our image doesn't actually have a default password, and in #658 we changed to explicitly require users of the image to set a password:

https://github.com/docker-library/postgres/blob/38841304ddd06dd3b39cc080b2c8fce5a5be8e52/docker-entrypoint.sh#L112-L120

The most effective mitigations I would recommend are choosing a strong (random!) password and not exposing the database publicly -- with containers, you should be able to have containers that need access to the database connect to it directly via container networking without exposing the ports, which increases the security dramatically.

**Comment by DmitriyStoyanov** [comment]
Thank you, our instance fixed by changing default password

**Comment by Vlad-Shevliakov** [comment]
Thanks! It saved my time 👍
