### ISSUE TITLE
Pulling postgres:12 gets me postgres13.1 version

### ISSUE THREAD

**Issue by mmojzis** [docker-library/postgres#799]
Hello,
I spent whole day debugging my Dockerfiles and docker-composes with issue that I needed postgres:12, but I was getting postgres13.1.
At the end I switched to postgres:12.5 and I got correct version.

**Comment by wglambert** [comment]
I'm not able to reproduce
```console
$ docker pull postgres:12
12: Pulling from library/postgres
6ec7b7d162b2: Pull complete 
a7d6065bfd90: Pull complete 
1b99004acb42: Pull complete 
e11ab41f0489: Pull complete 
eaa59f6a7cf0: Pull complete 
e27743da9368: Pull complete 
10ffdd8ade29: Pull complete 
bdaa066489bc: Pull complete 
889684a529fa: Pull complete 
a89eb4df2d61: Pull complete 
053ae58e1489: Pull complete 
d2c54ffd195a: Pull complete 
9af5769854f9: Pull complete 
e4d297047587: Pull complete 
Digest: sha256:87eb6772b300b260f080eceb7658c39a37a6bd1e302f459305d2d4b5df3523b0
Status: Downloaded newer image for postgres:12

$ docker run -d --rm --name pg -e POSTGRES_PASSWORD=test postgres:12
06e016e5f573708fbb7ced25629ed5d08502e00145269309f300c3f404ffc1f5

$ docker exec -it pg psql -U postgres
psql (12.5 (Debian 12.5-1.pgdg100+1))
Type "help" for help.

postgres=# select version();
                                                     version                                                      
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.5 (Debian 12.5-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)
```

The `12` and `12.5` digests match exactly
https://hub.docker.com/_/postgres/?tab=tags&page=1&ordering=last_updated&name=12
![image](https://user-images.githubusercontent.com/26428991/102632386-e0f82c00-4103-11eb-84fb-52ad4c9b8c33.png)

**Comment by mmojzis** [comment]
Okay, well...I tried it on different server now and it works correctly...
But before on server I did docker system prune and had zero containers running so it was like fresh docker and then `docker run -e POSTGRES_PASSWORD=password -it postgres:12` and `postgres -V` and I had PostgreSQL 13.1 Version there...So closing...Probably some kind of fu*kup on docker side...
