### ISSUE TITLE
Database configuration via command line is not working

### ISSUE THREAD

**Issue by nmiculinic** [docker-library/postgres#805]
I've repeated what it says on the docs:
```
docker run --rm -it --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword postgres -c shared_buffers=256MB -c max_connections=200
```

And I expected `shared_buffers` and `max_connections` parameters to be setup properly, but in the logs it doesn't say so:

```
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
```

**Comment by tianon** [comment]
I think that output is probably from `initdb` (which might have arguments that could be specified via `POSTGRES_INITDB_ARGS` to control those settings); if you connect to the instance, I think the actual runtime settings will be correct.

**Comment by nmiculinic** [comment]
Ok, I've queried the DB via `SELECT name, setting from pg_settings;` and you're right, it's fine!
