### ISSUE TITLE
Segmentation fault on RPi

### ISSUE THREAD

**Issue by MarcelCoding** [docker-library/postgres#812]
If i start any version (debian, alpine, 13, 12, 9) of postgres on my Rasberry PI i get a `Segmentation fault`:

```
postgres_1      | The files belonging to this database system will be owned by user "postgres".
postgres_1      | This user must also own the server process.
postgres_1      | 
postgres_1      | The database cluster will be initialized with locale "en_US.utf8".
postgres_1      | The default database encoding has accordingly been set to "UTF8".
postgres_1      | The default text search configuration will be set to "english".
postgres_1      | 
postgres_1      | Data page checksums are disabled.
postgres_1      | 
postgres_1      | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1      | creating subdirectories ... ok
postgres_1      | selecting dynamic shared memory implementation ... posix
postgres_1      | selecting default max_connections ... 100
postgres_1      | selecting default shared_buffers ... 128MB
postgres_1      | selecting default time zone ... GMT
postgres_1      | creating configuration files ... ok
postgres_1      | running bootstrap script ... ok
postgres_1      | sh: locale: not found
postgres_1      | 1970-04-25 09:07:44.009 GMT [30] WARNING:  no usable system locales were found
postgres_1      | performing post-bootstrap initialization ... ok
postgres_1      | syncing data to disk ... ok
postgres_1      | 
postgres_1      | initdb: warning: enabling "trust" authentication for local connections
postgres_1      | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1      | --auth-local and --auth-host, the next time you run initdb.
postgres_1      | 
postgres_1      | Success. You can now start the database server using:
postgres_1      | 
postgres_1      |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1      | 
postgres_1      | waiting for server to start....1970-04-24 12:38:56.009 GMT [35] LOG:  starting PostgreSQL 13.1 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
postgres_1      | 1970-04-24 12:38:56.009 GMT [35] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1      | .................1970-04-24 12:38:56.009 GMT [35] LOG:  startup process (PID 36) was terminated by signal 11: Segmentation fault
postgres_1      | 1970-04-24 12:38:56.009 GMT [35] LOG:  aborting startup due to startup process failure
postgres_1      | 1970-04-24 12:38:56.009 GMT [35] LOG:  database system is shut down
postgres_1      | .. stopped waiting
postgres_1      | pg_ctl: could not start server
postgres_1      | Examine the log output.
```

**Comment by GrimKriegor** [comment]
Unfortunately, I seem to be having the same issue on multiple Banana Pi running Armbian (armv7l).
I have also tested on a Lafrite running Armbian (aarch64) and on a desktop running Parabola (x86_64), but was unable to reproduce it there, everything worked fine.
Maybe there is a problem with the latest ARM 32 bit builds.

**Comment by tianon** [comment]
Hmm, "any version" is the part of this that seems suspicious to me -- I tested `arm32v7/postgres:latest` and was unable to reproduce a failure.  Is it possible you're too resource constrained?  (For example, do your systems have some amount of swap enabled?)

**Comment by GrimKriegor** [comment]
Good point.
Just redid the tests on a free Banana Pi (armv7l) and a free Lafrite (aarch64) both running Armbian.
Both of these machines have 1GiB of RAM and 500MiB of swap space.
Results remain consistent, SEGFAULT on the Banana Pi, normal operation on the Lafrite.
Unfortunately I don't have a beefier ARMv7 machine to test this on.

**Comment by MarcelCoding** [comment]
Ok, i found a hint for the problem: The problem occurs only if i connect to the database while it is just started or currently starting.
More testing: I restarted the database wait 10 seconds and started my backend and the db crashed again.

**Comment by MarcelCoding** [comment]
![image](https://user-images.githubusercontent.com/34819524/105769335-f744a380-5f5d-11eb-9294-6d3c762b27a5.png)
There is only about the half of the memory and the swap used.

**Comment by tianon** [comment]
Half the swap in use is definitely a pretty huge red flag IMO -- in a healthy system, I'd expect that to be a lot closer to zero.  If you increase the size of the available swap (adding another larger swapfile temporarily, for example), does the problem still persist?

**Comment by MarcelCoding** [comment]
I disabled the service for docker and containerd and restarted my RPi. Now the swap usage was at zero. Then I enabled and started containerd, the swap usage was at zero. After some time waiting I started and enabled docker. Now it took about 4 min that the RPi is in idle again. After about a minute the memory was at about 350MB and the first MB's were written to the swap. After more waiting, in the swap is always written as soon as the memory is at about 350MB. 
Another interesting thing i noticed is, that when I am running `sudo docker-compose logs -f postgres` it takes about one minute to display the logs. (the container is only restated about 10 times. So not much logs are existing)

**Comment by tianon** [comment]
Ah, that's probably `vm.swappiness` kicking in (https://linuxhint.com/understanding_vm_swappiness/) - if you set that down to something like 1 (because you don't want to disable swap altogether) it should use swap a lot less aggressively (and since your swap is likely on an SD card and thus sensitive to write wear, probably a good idea generally).

**Comment by georgescumihai** [comment]
I have the same issue.
I do not have any issue with the swap, my swap usage is 0.
I try to start only postgres container.
I tried deleting the container, the image and changing the volume so it starts from scratch.
I updated docker to `Docker version 20.10.2, build 2291f61`
I tried with the following images `postgres:13-alpine` and `postgres:11-alpine`.
I am running only `docker` and `postgres` container on this raspberry pi.

```bash
cat /proc/meminfo
MemTotal:        8064940 kB
MemFree:         4728052 kB
MemAvailable:    7511664 kB
Buffers:          139928 kB
Cached:          2778900 kB
SwapCached:            0 kB
Active:          1076836 kB
Inactive:        2088780 kB
Active(anon):     193060 kB
Inactive(anon):    22620 kB
Active(file):     883776 kB
Inactive(file):  2066160 kB
Unevictable:          16 kB
Mlocked:              16 kB
HighTotal:       7458816 kB
HighFree:        4419640 kB
LowTotal:         606124 kB
LowFree:          308412 kB
SwapTotal:        102396 kB
SwapFree:         102396 kB
Dirty:               100 kB
Writeback:             0 kB
AnonPages:        246916 kB
Mapped:           126648 kB
Shmem:             25176 kB
KReclaimable:     120464 kB
Slab:             143324 kB
SReclaimable:     120464 kB
SUnreclaim:        22860 kB
KernelStack:        2160 kB
PageTables:         4264 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     4134864 kB
Committed_AS:     904776 kB
VmallocTotal:     245760 kB
VmallocUsed:        5688 kB
VmallocChunk:          0 kB
Percpu:              608 kB
CmaTotal:         262144 kB
CmaFree:          256032 kB
```

**Comment by tianon** [comment]
Interesting!  Since it's a segfault, perhaps you can run the container with an interactive shell, install `strace`, then run the server and see if we can get a clue about which specific thing is failing?

**Comment by georgescumihai** [comment]
When I try to add strace or any package I get 
```
apk add strace
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
ERROR: unable to select packages:
  strace (no such package):
    required by: world[strace]
```

**Comment by georgescumihai** [comment]
I can confirm that I have the same issue with debian image.

**Comment by chylek** [comment]
I am having the same issue on Raspberry Pi 4 with 4 GB of RAM (and 4 GB of swap, but that is almost unused). 

@tianon Is this the `strace` output you wanted [outp.txt](https://github.com/docker-library/postgres/files/5880396/outp.txt)?

**Comment by MarcelCoding** [comment]
@tianon Thank you, the problem with the swap is solved (https://github.com/docker-library/postgres/issues/812#issuecomment-767857144). But the Segmentation fault still persists.

**Comment by georgescumihai** [comment]
Using an older image like `11.9-alpine` works if you start it without data.
But If you use the volume that you had with `11-alpine`, even with older images it throws `startup process (PID 36) was terminated by signal 11: Segmentation fault`, so if you do not have a backup from before the update, you lost all the data.

**Comment by MarcelCoding** [comment]
I testet version 9 to 13 on alpine with no volumes

**Comment by tianon** [comment]
Ok, finally got my own RPi1 up to test this out directly, and I can't actually reproduce the problem, so this is looking interesting/strange:

```console
$ docker pull --platform linux/arm/v6 postgres:11-alpine
11-alpine: Pulling from library/postgres
b550170d5d44: Pull complete 
9d448e33e6bb: Pull complete 
f7df0858d3f1: Pull complete 
610f675f4508: Pull complete 
89f0fdff679b: Pull complete 
9636a6b682e7: Pull complete 
498edef3996b: Pull complete 
cb2db3eaeeb7: Pull complete 
933d59052948: Pull complete 
Digest: sha256:7d1dd4a6e307e42f108e81a39f55a5edc4aa185d4e6b301be66e035269de501b
Status: Downloaded newer image for postgres:11-alpine
docker.io/library/postgres:11-alpine

$ docker run -it --rm --platform linux/arm/v6 --name test --env POSTGRES_PASSWORD=foobar postgres:11-alpine
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... sh: locale: not found
2021-01-28 22:06:53.139 UTC [30] WARNING:  no usable system locales were found
ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2021-01-28 22:07:27.074 UTC [35] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-01-28 22:07:27.321 UTC [36] LOG:  database system was shut down at 2021-01-28 22:07:22 UTC
2021-01-28 22:07:27.475 UTC [35] LOG:  database system is ready to accept connections
 done
server started

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2021-01-28 22:07:28.073 UTC [35] LOG:  received fast shutdown request
waiting for server to shut down....2021-01-28 22:07:28.128 UTC [35] LOG:  aborting any active transactions
2021-01-28 22:07:28.154 UTC [35] LOG:  background worker "logical replication launcher" (PID 42) exited with exit code 1
2021-01-28 22:07:28.162 UTC [37] LOG:  shutting down
2021-01-28 22:07:28.377 UTC [35] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2021-01-28 22:07:28.568 UTC [6] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-01-28 22:07:28.568 UTC [6] LOG:  listening on IPv6 address "::", port 5432
2021-01-28 22:07:28.632 UTC [6] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-01-28 22:07:28.902 UTC [47] LOG:  database system was shut down at 2021-01-28 22:07:28 UTC
2021-01-28 22:07:28.959 UTC [6] LOG:  database system is ready to accept connections

$ # in a separate terminal:
$ docker exec -it test sh
/ # psql -U postgres
psql (11.10)
Type "help" for help.

postgres=# SELECT 1;
 ?column? 
----------
        1
(1 row)

```

**Comment by chylek** [comment]
If I remember correctly - for me it also worked ok without volume, but mounting volume (usb hard drive) like
`/home/pi/hdd/psql:/var/lib/postgresql/data`
 was the problem even when hdd/psql was empty. 
I had restored from a backup all files in postgresql/data and I had to drop some corrupted tables. Since then it works fine.

**Comment by georgescumihai** [comment]
```
docker run -it --rm --platform linux/arm/v7 --name test --env POSTGRES_PASSWORD=foobar postgres:11-alpine
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... GMT
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... sh: locale: not found
1970-05-14 20:59:12.011 GMT [30] WARNING:  no usable system locales were found
ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....1970-05-20 22:37:20.011 GMT [35] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
.....1970-05-20 22:37:20.011 GMT [35] LOG:  startup process (PID 36) was terminated by signal 11: Segmentation fault
1970-05-20 22:37:20.011 GMT [35] LOG:  aborting startup due to startup process failure
.1970-05-20 22:37:20.011 GMT [35] LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.
```

**Comment by tianon** [comment]
Probably not related, but it is interesting that your system time is set to `1970-05-14 20:59:12.011 GMT` :grimacing:

**Comment by tianon** [comment]
Ahhhhh crap, that gives me an interesting sense of deja-vu.

If you run the container with `--security-opt seccomp:unconfined`, does it work?

(https://github.com/moby/moby/issues/40734)

**Comment by ImreSamu** [comment]
@tianon :

> Probably not related, but it is interesting that your system time is set to  ..

maybe **musl time64** related ?
 
Alpine 3.13 has a musl time64 
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements
* _"The following important information applies for users of x86, armv7, and armhf (currently supported 32-bit architectures), including 32-bit Docker containers on 64-bit hosts."_ 
*  _"Therefore, Alpine Linux 3.13.0 requires the host **Docker to be version 19.03.9**"_ 
* _"In order to run under old Docker or libseccomp versions" ...._
* _"Alternatively, --security-opt=seccomp=unconfined ... "_

**Comment by chylek** [comment]
I was running the 12-alpine version and I was also seeing weird dates. With the non-alpine version I was seeing the issue only if I mounted a volume that was previously used by the 12-alpine version. No issue with non-alpine version when using a clean new volume (or backup from a rather old 12-alpine version)

My Docker is version 20.10.2

Running with `--security-opt seccomp:unconfined` did not help if I was mounting a volume that was already created.
But running with new volume helped and the docker runs without issue. Thank you @tianon and @ImreSamu

**Comment by georgescumihai** [comment]
Running with security-opt seccomp:unconfirmed make it not to crash. I will try it with a volume mounted.
Also the time is correct now.
```
docker run -it --rm --platform linux/arm/v7 --name test --env POSTGRES_PASSWORD=foobar --security-opt seccomp:unconfined postgres:11-alpine
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... sh: locale: not found
2021-01-29 08:09:21.264 UTC [32] WARNING:  no usable system locales were found
ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2021-01-29 08:09:24.536 UTC [37] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-01-29 08:09:24.598 UTC [38] LOG:  database system was shut down at 2021-01-29 08:09:22 UTC
2021-01-29 08:09:24.610 UTC [37] LOG:  database system is ready to accept connections
 done
server started

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....2021-01-29 08:09:24.739 UTC [37] LOG:  received fast shutdown request
2021-01-29 08:09:24.744 UTC [37] LOG:  aborting any active transactions
2021-01-29 08:09:24.746 UTC [37] LOG:  background worker "logical replication launcher" (PID 44) exited with exit code 1
2021-01-29 08:09:24.747 UTC [39] LOG:  shutting down
2021-01-29 08:09:24.799 UTC [37] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2021-01-29 08:09:24.869 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-01-29 08:09:24.869 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-01-29 08:09:24.887 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-01-29 08:09:24.946 UTC [49] LOG:  database system was shut down at 2021-01-29 08:09:24 UTC
2021-01-29 08:09:24.958 UTC [1] LOG:  database system is ready to accept connections

```

**Comment by MarcelCoding** [comment]
https://github.com/docker-library/postgres/issues/812#issuecomment-769651015 -> The same for me, and I did not see https://github.com/docker-library/postgres/issues/812#issue-793423729 that the time here was also already wrong. But I think that this is not a permanent solution.

**Comment by tianon** [comment]
> But I think that this is not a permanent solution.

It's not something we can/will fix in the images, from what I can see.

You need to update Docker to 19.03.9 or newer and libseccomp (on your host) to 2.4.2 or newer.

**Comment by MarcelCoding** [comment]
That means the same as them? https://github.com/tianon/docker-brew-ubuntu-core/issues/195
Only the raspberry package sources still do not have a new version of libseccomp.

For the Issue with ubuntu, I use currently bionic, because it needs a older version of libseccomp.
I hope they will be update this soon.

**Comment by MarcelCoding** [comment]
https://github.com/docker-library/postgres/issues/812#issuecomment-770148482
> It's not something we can/will fix in the images, from what I can see.
> You need to update Docker to 19.03.9 or newer and libseccomp (on your host) to 2.4.2 or newer.

**Comment by sangeethnandakumar** [comment]
### For anyone still experiencing this on Raspberry Pi 4. I got it to work this way:

> The problem is with the volume mapping.

Since removing the volume mapping makes PostgreSQL work immediately, this indicates there's an issue with either:
- The permissions on the /home/pi/postgres_data directory
- File system compatibility issues with the mounted volume
- Corrupted data in that directory that's causing PostgreSQL to crash

#### So I, stopped and remove the current container:
```bash
docker stop postgres
docker rm postgres
```

#### Then created a fresh directory with the right permissions:
```bash
sudo rm -rf /home/pi/postgres_data
mkdir -p /home/pi/postgres_data
sudo chown -R 999:999 /home/pi/postgres_data     (Because 999 is typically the postgres user ID in the container)
```

#### Then ran PostgreSQL with both the seccomp flag and properly prepared volume:
```bash
docker run -d \
  --name postgres \
  --restart unless-stopped \
  -e POSTGRES_USER=pi \
  -e POSTGRES_PASSWORD=MySecurePwd#123 \
  -e POSTGRES_DB=mydatabase \
  -v /home/pi/postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
  --security-opt seccomp=unconfined \
  arm32v7/postgres:16-alpine
```
