### ISSUE TITLE
Why can't I add arbitrary files?

### ISSUE THREAD

**Issue by Osipion** [docker-library/postgres#815]
Thanks for all the effort you've put into making this image - it's much appreciated.

## I can't add arbitrary files

I need to add some `.so` files I've compiled in an earlier build step, as my application depends on them being present. I have the following Dockerfile:

```Dockerfile
FROM my-libs:latest as builder

FROM postgres:10

COPY --from=builder /usr/lib/libprefix* /usr/lib/

COPY init.sh /docker-entrypoint-initdb.d/init.sh
RUN chmod +x /docker-entrypoint-initdb.d/init.sh

RUN ls -lat /usr/lib/ | grep -i libprefix
```

In the final build step where I list the libraries added to /usr/lib I see the libraries as I expect. However, if I run a container:

```
docker run --rm -it -e POSTGRES_PASSWORD=password -p 5432:5432 --name my-postgres my-postgres
```

And then exec into it:

```
docker exec -it my-postgres ls -lat /usr/lib
```

All of my libraries have disappeared.

I notice this happens almost wherever I try to add them (/tmp, even /docker-entrypoint-initdb.d), yet the init.sh script in /docker-entrypoint-initdb.d/ magically stays put. What's going on here?

**Comment by tianon** [comment]
I can't reproduce, and I can't see a way this could be related to the image?

```dockerfile
FROM bash AS builder

RUN echo foo > /bar

FROM postgres:10

COPY --from=builder /bar /tmp/

RUN ls -l /tmp/bar
```

```console
$ docker build .
Sending build context to Docker daemon  34.82kB
Step 1/5 : FROM bash AS builder
 ---> a3cae8598d52
Step 2/5 : RUN echo foo > /bar
 ---> Running in 6b5570d740cb
Removing intermediate container 6b5570d740cb
 ---> b32c73c54fc6
Step 3/5 : FROM postgres:10
 ---> 25ebc94bdcba
Step 4/5 : COPY --from=builder /bar /tmp/
 ---> f4c953a77aa2
Step 5/5 : RUN ls -l /tmp/bar
 ---> Running in 9f7c23b4aa1b
-rw-r--r-- 1 root root 4 Feb  9 20:36 /tmp/bar
Removing intermediate container 9f7c23b4aa1b
 ---> e10503ba999a
Successfully built e10503ba999a

$ docker run --rm e10503ba999a cat /tmp/bar
foo
```

**Comment by Osipion** [comment]
I got my container names mixed up and was running an old container 🤦.
