### ISSUE TITLE
Feature request - add env var to enable extensions by default

### ISSUE THREAD

**Issue by WHK102** [docker-library/postgres#826]
By example, when need enable by default the uuid extension need execute additional scripts in startup:

```sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
```

But, is a great idea send the extensions by arguments, by example:

```bash
$ sudo docker run postgres -e "EXTENSION=uuid-ossp" -e "EXTENSION=other-extension" ...
```

**Comment by yosifkit** [comment]
Basically the same response as, https://github.com/docker-library/mongo/issues/460#issuecomment-797795751; tldr: "We are always very hesitant to add new environment variables."

And I'll add, especially for something that amounts to a two line dockerfile (or an extra line in a `docker-compose.yml` file to mount an `initdb.d` directory):

```Dockerfile
FROM postgres:13
RUN echo 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' > /docker-entrypoint-initdb.d/uuid-ossp.sql
```

**Comment by WHK102** [comment]
But can not use docker compose, why not use enviroment variable for easy enabling extension?, is same question: why pass the password on enviroment variable and not in docker compose using `RUN` and `create user` statement?, in a productive enviroment need enable very specific extensions and dynamics passwords.
