### ISSUE TITLE
Add autopostgresqlbackup package

### ISSUE THREAD

**Issue by ypid** [docker-library/postgres#83]
Hi

What are your thoughts about including the autopostgresqlbackup package into the image? I just tried to run it (`docker exec -ti db autopostgresqlbackup`) and it works nicely.
Nothing should change by including it as autopostgresqlbackup is executed by cron which is not running in the postgres container.

```
root@48e4deef5553:/# dpkg -L autopostgresqlbackup
/.
/etc
/etc/default
/etc/default/autopostgresqlbackup
/etc/cron.daily
/etc/cron.daily/autopostgresqlbackup
/usr
/usr/sbin
/usr/sbin/autopostgresqlbackup
/usr/share
/usr/share/doc
/usr/share/doc/autopostgresqlbackup
/usr/share/doc/autopostgresqlbackup/copyright
/usr/share/doc/autopostgresqlbackup/changelog.Debian.gz
/usr/share/man
/usr/share/man/man8
/usr/share/man/man8/autopostgresqlbackup.8.gz
/var
/var/lib
/var/lib/autopostgresqlbackup
```

Or are there other best practices for creating SQL dumps as backup?

**Comment by yosifkit** [comment]
That seems ok to me. Though we definitely would want to document the recommended way to use it.

@tianon, I think we should recommend that they start a new container rather than `docker exec`.  Maybe give them a one-liner to run and get a full/daily/monthly snapshot?  Would it also be useful to have `automysqlbackup` in the mysql images?

**Comment by tianon** [comment]
Is there a way to run it in a second container instead?

**Comment by md5** [comment]
Looks like the source of the script is here: https://gist.github.com/matthewlehner/3091458

It appears to just use [`pg_dump`](http://www.postgresql.org/docs/9.4/static/app-pgdump.html) to connect to the server after doing a bunch of stuff to manage the backup directories themselves. I don't see why it couldn't be run in a linked container.

**Comment by yosifkit** [comment]
Yeah, but it won't be a simple one-liner since the scipt needs to be edited to change the user and host, https://gist.github.com/matthewlehner/3091458#file-autopgsqlbackup-L33-L42, and password has to go in a file.

**Comment by md5** [comment]
The password can come from the linked environment variable, assuming it's set. But it seems you're right about `DBHOST` not being settable other than editing the file :confused: 

The whole thing seems a bit... unofficial

**Comment by yosifkit** [comment]
I think since it is not a tool from upstream postgres, we should probably skip on including it in the image, but we should add a section on making a backup with `pg_dump` to the documentation.  That way users who know `autopostgresqlbackup` can apply the principles we show.

**Comment by tianon** [comment]
Closing, since there's nothing actionable for changing the image here.  Adding a small blurb to the documentation would be acceptable if someone wanted to take that on, but given that `pg_dump` is just a standard PostgreSQL client, I don't personally think it should be especially necessary.
