### ISSUE TITLE
pgaudit - is it in version alpine-11?

### ISSUE THREAD

**Issue by WhatsOnSecond** [docker-library/postgres#839]
It seems that it functions that it is there, but it is not shown as in the list of shared_preload_libraries in the postgresql.conf.

Is pgaudit included with alpine-11?

Thanks,

Scott

**Comment by wglambert** [comment]
It's not included in the image but for the Debian variant it's a simple install, see https://github.com/pgaudit/pgaudit/issues/44#issuecomment-455090262

https://github.com/docker-library/docs/tree/master/postgres#additional-extensions

**Comment by wilx** [comment]
Could you document how to build pgaudit for PostgreSQL on Alpine container? I will probbly be forced by the company to migrate to it.

**Comment by yosifkit** [comment]
It'll be basically the same as [postgis](https://github.com/postgis/docker-postgis/blob/4eb614133d6aa87bfc5c952d24b7eb1f499e5c7c/12-3.0/alpine/Dockerfile):
 - download source for the extension
 - install build dependencies
 - compile
 - install
 - keep run dependencies
 - remove source
 - remove build dependencies
 - enable it at runtime
