### ISSUE TITLE
Option to not set external auth methods

### ISSUE THREAD

**Issue by TLATER** [docker-library/postgres#858]
Hi, I'm setting up a postgres container in a podman pod, using a network namespace so that nothing except the port of the service connecting to postgres is exposed.

This means that the service can connect to postgres using trust authentication by default (because it's on `localhost` as far as postgres is concerned), and it's impossible for anything else to connect (assuming no bugs in network namespaces).

However, because of how `POSTGRES_HOST_AUTH_METHOD` is currently implemented, I'm forced to either manually remove what the container setup does, set a password that will never be used, or permit global `trust` auth. Neither of these options is ideal - the first requires additional scripting or mounting a custom config, the second raises red flags and is just global `trust` auth if the secret isn't managed (which in turn can be even more effort than the former), and the last isn't great in case the container networking does somehow end up exposed.

Ideally I'd like [this function](https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh#L225) just to do nothing if `POSTGRES_HOST_AUTH_METHOD=none` or something along those lines.

I realize that this adds complexity, but is there space for such a setting?

**Comment by tianon** [comment]
I think `POSTGRES_HOST_AUTH_METHOD=reject` might accomplish what you're looking for.

**Comment by TLATER** [comment]
Ah! I missed that in the documentation, I'll give that a try (assuming ordering doesn't break it).

It doesn't quite fix this issue though, since you still need to set a password even with `reject`: https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh#L110.

**Comment by TLATER** [comment]
I've pushed up a PR to cover that case, would very much appreciate a review :)

**Comment by TLATER** [comment]
Alas, #859 was closed because it's a potential anti-pattern.
