### ISSUE TITLE
Docker compose example

### ISSUE THREAD

**Issue by Jogai** [docker-library/postgres#860]
The readme has a compose example, but it doesnt explain much and just adds adminer to it. Maybe it would be better to state that a web-ui is coming along. 

Also the choice for adminer is not motivated. I'd say use pgWeb, its a smaller container and has a more modern look. My example:

```
version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: my_pg_db
    ports:
      - "5432:5432"
  
  pgweb:
    container_name: pg-ui-web
    restart: unless-stopped
    image: sosedoff/pgweb
    ports: 
      - "8081:8081"     
    environment:
      - DATABASE_URL=postgres://postgres:my_pass@postgres:5432/my_pg_db?sslmode=disable
    depends_on:
      - postgres

**Comment by tianon** [comment]
The choice of `adminer` _was_ motivated -- it's an existing image within the program, unlike pgWeb. :confused:

It's also just an example, and users are not intended to use it as-is.

**Comment by Jogai** [comment]
Ah I see. I should have said, the motivation is not expressed. Anyway, in that case, no need for a change.
