### ISSUE TITLE
postgres:11-alpine is still 3.13

### ISSUE THREAD

**Issue by perelman92** [docker-library/postgres#862]
I see that alpine has been updated to 3.14
https://github.com/docker-library/postgres/blob/718c12a2ad571c564f3425fb6cc6d0986d6a210f/11/alpine/Dockerfile#L2

However it seems like the official docker image has yet to be updated:

`docker pull postgres:11-alpine && docker run -it postgres:11-alpine cat /etc/alpine-release`
Shows 3.13.5

When will the docker image 'postgres:11-alpine' be updated to alpine 3.14? 

Thanks

@yosifkit

**Comment by ImreSamu** [comment]
IMHO: expected in the next working days.   (  ~ Tuesday? ) 

see:  ["README:See a change merged here that doesn't show up on Docker Hub yet?"](https://github.com/docker-library/postgres#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet)

**Comment by wglambert** [comment]
The PR to update the Postgres variants was merged a few days ago https://github.com/docker-library/official-images/pull/10376

But there's an issue with the Alpine 3.14 builds https://github.com/docker-library/official-images/pull/10379#issuecomment-863396878

**Comment by tianon** [comment]
Builders are updated and builds are either queued or in progress -- sorry for the delay!
