### ISSUE TITLE
'No response' from postgres database server, inside postgres docker container

### ISSUE THREAD

**Issue by abcd-ABCD-1234** [docker-library/postgres#868]
I am creating a docker container on ubuntu platform, with image "postgres:12.1" on port 5432 using the command: "`docker run -it -p 5432:5432 --name DB postgres:12.1 bash`". 
The container got created successfully. But when I execute `pg_isready` inside the container, it returns no response as below:
~~~
/var/run/postgresql:5432 - no response
~~~
I ran `netstat -ln` inside the container, and it seems that the service is not connected to port 5432. below is the output of `netstat -ln`:
~~~
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
~~~

However, things are different when I use docker-compose to create postgres container. Below is my docker-compose.yaml file:
~~~
version: "3.7"
services:
  DB:
    container_name: DB
    image: postgres:12.1
~~~
I executed "`docker-compose up -d DB`", which created a container named DB on port 5432. I am able to connect to the database server inside this container using `pg_isready` on port 5432 (command returns accepting connections). `Netstat -ln` also shows that the service is connected to port 5432.

I am really confused about what happens when I run a container without docker-compose. Can you please put some light on this issue? Please ping me if more information is required.
Hoping for a positive response. :)

**Comment by wglambert** [comment]
The `bash` at the end of `docker run -it -p 5432:5432 --name DB postgres:12.1 bash` means the entrypoint will be skipped (and database initialization/startup) and go straight to bash. If you wanted to get a shell in a container then you'd probably want to use `-d` instead of `-it` and drop the `bash`:
```console
$ docker run -d --name DB postgres:12.1
0e105343780bd3094221031ba548ef308ea602294bb30f34b06aeabe9c4b34fd

$ docker exec -it DB bash

root@0e105343780b:/# apt update &>/dev/null && apt install -y net-tools procps &>/dev/null

root@0e105343780b:/# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::5432                 :::*                    LISTEN      -                   

root@0e105343780b:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
postgres     1  0.2  0.0 215744 15020 ?        Ss   15:35   0:00 postgres
postgres    58  0.0  0.0 215744  4104 ?        Ss   15:35   0:00 postgres: checkpointer  
postgres    59  0.0  0.0 215744  4104 ?        Ss   15:35   0:00 postgres: background writer  
postgres    60  0.0  0.0 215744  4104 ?        Ss   15:35   0:00 postgres: walwriter  
postgres    61  0.0  0.0 216284  6788 ?        Ss   15:35   0:00 postgres: autovacuum launcher  
postgres    62  0.0  0.0  68276  4672 ?        Ss   15:35   0:00 postgres: stats collector  
postgres    63  0.0  0.0 216168  6784 ?        Ss   15:35   0:00 postgres: logical replication launcher  
root        64  0.0  0.0   6856  3608 pts/0    Ss   15:35   0:00 bash
root      1196  0.0  0.0  10628  3080 pts/0    R+   15:37   0:00 ps aux
```

**Comment by abcd-ABCD-1234** [comment]
Thank you @wglambert. Now I am able to access postgres service on port 5432. I will close this issue now.
