### ISSUE TITLE
Environment variables: Follow more psql conventions

### ISSUE THREAD

**Issue by mcandre** [docker-library/postgres#871]
Could more of the environment variables for PostgreSQL connectivity transition to follow psql naming convention?

https://www.postgresql.org/docs/9.3/libpq-envars.html

For example, deprecate deviant environment variable names, with psql names using higher precedence.

**Comment by tianon** [comment]
Those variables are explicitly for _connection_ though, and change the default behavior of `psql` accordingly, whereas our variables are for _creating_ objects, and only apply during initial startup, so IMO it's not terribly appropriate for us to reuse these. :confused:

**Comment by yosifkit** [comment]
Agree with @tianon; we don't want to overload the upstream connection variables. Also, our variable names were created specifically to not conflict or be confused with any possible upstream variables.
