### ISSUE TITLE
If I map an SQL file from docker compose it only runs it the first time 

### ISSUE THREAD

**Issue by timuckun** [docker-library/postgres#875]
- ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

It says the volume already exists and doesn't run the script. I do not have a persistent volume mapped.

**Comment by wglambert** [comment]
Any scripts in `docker-entrypoint-initdb.d/` will only run on database initialization, if it's detecting files and not initializing the database, and you don't have any volumes mapped then it could be the container never fully exited and is still using its ephemeral storage? (like a `docker stop/start`)

Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by yosifkit** [comment]
> If you do not declare a volume mount point, then the `VOLUME` declared in the postgres image will apply and docker will create and manage the directory independent of the life-cycle of the container.  This gets more complicated when using compose, since it will keep the volume to re-use later even when you `docker-compose rm -f` all of your running containers.

See also https://github.com/docker-library/postgres/issues/203#issuecomment-255200501
