### ISSUE TITLE
pg_partman, PLV8 and other popular extensions?

### ISSUE THREAD

**Issue by timuckun** [docker-library/postgres#876]
Would it be possible to get "official" images which include the popular extensions that come pre-installed on cloud providers such as AWS  RDS?

**Comment by wglambert** [comment]
Adding extensions is fairly trivial https://github.com/docker-library/docs/tree/master/postgres#additional-extensions, and with being somewhat unique to each user's needs - it's easiest for users to just make a derivative Dockerfile with the added customizations
