### ISSUE TITLE
-e POSTGRES_PASSWORD not setting password

### ISSUE THREAD

**Issue by thedug** [docker-library/postgres#89]
I started a container using -e POSTGRES_PASSWORD and I am able to log in without a password

Running this logs be directly into the DB.

          docker run --net=host -it --rm postgres sh -c 'exec psql -h "localhost" -U postgres'

**Comment by md5** [comment]
The `pg_hba.conf` file has these lines in it:

```
# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
```

Since you're using `--net=host`, your connection is local, so it's trusted.

**Comment by thedug** [comment]
That makes sense. Thanks!

**Comment by md5** [comment]
Sure thing! :+1: 

Do you mind closing this issue?

**Comment by thedug** [comment]
Done.
