### ISSUE TITLE
Incorrect sort on `bullseye` and `buster`

### ISSUE THREAD

**Issue by NicholasNoise** [docker-library/postgres#905]
This issue occurs on any version of `postgres` based on `bullseye` and `buster`.
Test case:
```
with person(lastname,firstname,middlename,birthdate) as (
  VALUES 
  ('Семенова','Алена','Сергеевна',TO_DATE('11.01.2008','DD.MM.YYYY')),
  ('Семенова','Алёна','Константиновна',TO_DATE('06.01.2020','DD.MM.YYYY')),
  ('Семенова','Альбина','Георгиевна',TO_DATE('07.09.1940','DD.MM.YYYY')),
  ('Семёнова','Алёна','Витальевна',TO_DATE('12.03.2021','DD.MM.YYYY')))
select (p.lastname || ' ' ||  p.firstname || coalesce(' ' || p.middlename, '') || ', ' || to_char(p.birthdate,'DD.MM.YYYY')) FullName
from person p
order by FullName;
```
Valid order is 1-2-3-4 (as presented in person table), on `bullseye` and `buster` - 4-2-1-3.
Also `order by p.lastname, p.firstname, p.middlename` works identically (and correct) on any image.
It seems that symbols `е` and `ё` are considered the same for concatenated strings ONLY.

It appears that system library `libc-bin` has a breaking change between 2.24 and 2.28.
I have locally builded 12.8-stretch and it works as expected.

I actually dont know what to do with this information, but to log it here.

**Comment by ImreSamu** [comment]
@NicholasNoise :  related thread in the PostgreSQL mail list   ["Wrong sorting on docker image" + Russian collation](https://www.postgresql.org/message-id/flat/F29709C9-A061-4034-A77D-7E237CF36391%40gmail.com) (  Date: 2021-10-16 )

**Comment by tianon** [comment]
I think #582 is probably also useful :grimacing:

**Comment by tianon** [comment]
Going to close as I don't think there's anything we can do here to fix this in the image (but if more debugging is done and it turns out there's a straightforward fix, a PR would be interesting! :heart:) :+1:
