### ISSUE TITLE
arm64 builds?

### ISSUE THREAD

**Issue by mandrean** [docker-library/postgres#909]
Hi,

Any plans on adding `arm64` builds for M1 Macs and arm64 servers?
https://docs.docker.com/desktop/multi-arch/

Lots of other projects started adding multi-arch builds already:
![image](https://user-images.githubusercontent.com/4631744/143004130-b681c88d-1966-472c-a474-fb8a211d5c88.png)

![image](https://user-images.githubusercontent.com/4631744/143004546-37744aa1-38a2-4155-96a8-db551113bf57.png)

**Comment by wglambert** [comment]
This image supports amd64, arm32v5, arm32v6, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
https://hub.docker.com/_/postgres/

![image](https://user-images.githubusercontent.com/26428991/143071114-849fc09f-1a1e-49be-97ff-07caa3e7c7dc.png)

See also https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by mandrean** [comment]
Ah it's hidden by the truncation on Docker Hub

"+5 more..."

Thanks @wglambert!

![image](https://user-images.githubusercontent.com/4631744/144070877-e6f04432-b73e-4546-ac17-1e270830e9ff.png)
