### ISSUE TITLE
Host Auth Method changed with postgres:14

### ISSUE THREAD

**Issue by callalilyz** [docker-library/postgres#911]
I found pg_hba.conf is populated with `host all all all scram-sha-256` by default (Host Auth Method is NOT specified) with my docker run. This issue only occurs with the latest postgres:14 docker image. Previous version is showing md5 as it is supposed to.

**Comment by yosifkit** [comment]
I'm not sure where I see the problem. PostgreSQL 14 has moved the default that users are created with anyway and so we improved the `pg_hba.conf` to match in https://github.com/docker-library/postgres/pull/897.

**Comment by tianon** [comment]
Indeed, this is on purpose to match the upstream defaults.
