### ISSUE TITLE
Are there any plans to support custom pg_dumbs as init scripts ?

### ISSUE THREAD

**Issue by MaltePetersen** [docker-library/postgres#915]

**Comment by wglambert** [comment]
You can put your `dump.sql` in `/docker-entrypoint-initdb.d/` https://github.com/docker-library/docs/tree/master/postgres#initialization-scripts

**Comment by MaltePetersen** [comment]
Yes I know but you can not put custom pg_dumps (pg_dump -F c ${db}). Custom pg_dumps are binary files and as it seems currently not supported eventough they can be a lot smaller than a normal sql dump.

**Comment by yosifkit** [comment]
There is no current plan to add this functionality. You can likely drop it there next a `.sh` script that restores the dump.
