### ISSUE TITLE
container stuck at "find /var/lib/postgresql/data ! -user postgres -exec chown postgres {} +" on startup

### ISSUE THREAD

**Issue by sify21** [docker-library/postgres#916]
I'm using postgres:13 with podman 3.4.2 on fedora 35, the data directory is very large, and every time I start the container it get stuck at `find chown`
```
> podman top postgres
USER        PID         PPID        %CPU        ELAPSED           TTY         TIME        COMMAND
root        1           0           0.000       57m49.389714415s  ?           0s          bash /usr/local/bin/docker-entrypoint.sh postgres 
root        7           1           98.346      57m49.389884734s  ?           56m52s      find /var/lib/postgresql/data ! -user postgres -exec chown postgres {} + 
```
Is there a way to avoid this operation? this directory is already owned by postgres,  `chown` doesn't need to run every time

**Comment by tianon** [comment]
If you include `--user postgres` in your `docker run` line, then it won't try to fix permissions (because if it isn't started as root, it can't).

**Comment by sify21** [comment]
@tianon I'm not using docker, I'm using rootless podman with this command:
```
podman run -d \
    --name postgres \
    -e POSTGRES_USER=user \
    -e POSTGRES_PASSWORD=pwd \
    -v ./data:/var/lib/postgresql/data \
    -p 5432:5432 \
    --privileged \
    postgres:13
```

**Comment by tianon** [comment]
Fair enough, but `podman run` should support the same `--user` flag.  You also definitely don't want to run PostgreSQL with `--privileged`. :see_no_evil:
