### ISSUE TITLE
Can't stop the postgresql service / Empty cluster name

### ISSUE THREAD

**Issue by jorgeolive** [docker-library/postgres#922]
Hello,

When running the docker image by the default configuration, that is , 

`docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres`

No cluster information is associated to the database. When I try to stop the database service from within the container, I get the following error:

`No PostgreSQL clusters exist; see "man pg_createcluster" ... (warning).` 

The postgresql services seems to be up afterwards:

```
root@ee8f239c3731:/etc/postgresql# sudo ps aux | grep postgres
postgres       1  0.0  0.1 213276 26636 ?        Ss   21:55   0:00 postgres
postgres      61  0.0  0.0 213396  7936 ?        Ss   21:55   0:00 postgres: checkpointer
postgres      62  0.0  0.0 213276  5876 ?        Ss   21:55   0:00 postgres: background writer
postgres      63  0.0  0.0 213276  9900 ?        Ss   21:55   0:00 postgres: walwriter
postgres      64  0.0  0.0 213812  8528 ?        Ss   21:55   0:00 postgres: autovacuum launcher
postgres      65  0.0  0.0  67868  4852 ?        Ss   21:55   0:00 postgres: stats collector
postgres      66  0.0  0.0 213712  6672 ?        Ss   21:55   0:00 postgres: logical replication launcher
root         600  0.0  0.0   6176   652 pts/0    S+   22:19   0:00 grep postgres
```

Seems there's no trace of the cluster name or whatsever. Indeed, running the following command returns no results:

```
root@ee8f239c3731:/# pg_lsclusters
Ver Cluster Port Status Owner Data directory Log file
root@ee8f239c3731:/#
```
or

```
postgres=# SELECT name, setting FROM pg_settings WHERE name in ('cluster_name','server_version','port');
      name      |            setting
----------------+--------------------------------
 cluster_name   |
 port           | 5432
 server_version | 14.1 (Debian 14.1-1.pgdg110+1)
(3 rows)
```

Is there anyway to start a containerized database with a given cluster name ?
Regards,
Jorge.

**Comment by tianon** [comment]
Can you elaborate on "I try to stop the database service from within the container" ?  If you stop the database service, it's running as PID 1, so the container will exit. :grimacing:

**Comment by jorgeolive** [comment]
Yep, I didn't consider that one :( 

I am trying to do some configurations in order to configure replication, and service stop/restarts are requested in the configuration. So.... what are my options here? All these operations have to be managed through container stops and restarts right?

**Comment by tianon** [comment]
Yep, unfortunately that is correct.
