### ISSUE TITLE
MacOS M1 docker image

### ISSUE THREAD

**Issue by NikolayMetchev** [docker-library/postgres#923]
I was wondering what is the likelihood of creating an M1 Mac docker image for postgres?

It would be helpful to have postgres running natively on M1 Macs instead of through emulation.

**Comment by yosifkit** [comment]
Every version we publish comes with Linux `arm64v8` images already. So, unless you specify `--platform linux/amd64` to get an image that needs emulation, it should already be using images that are compiled for arm64v8.

**Comment by NikolayMetchev** [comment]
apologies, I was only looking at the OS and didn't see macos.
