### ISSUE TITLE
Minor version upgrades on PG13

### ISSUE THREAD

**Issue by mattyw** [docker-library/postgres#924]
In d50c412c4e1da9b37966a19a1141d167eeaf056f the base image for postgres 13 was changed from Debian:buster -> debian:bullseye. That means that if I had been using pg 13.4 and I wanted to upgrade to 13.5 then I would also be upgrading debian. OS upgrades can involve other headaches (e.g. #582)

My understanding from the thread in #582 is that I would have expected a 13-buster tag to be available. But this isn’t the case. Have I misunderstood the policy of minor version upgrades with respect to the OS base image or is this a bug?

**Comment by yosifkit** [comment]
The `postgres:13-buster` tag is still [available](https://hub.docker.com/_/postgres?tab=tags&page=1&name=13-buster), but is no longer rebuilt. The update to Bullseye did not have a known problem like the Stretch to Buster update had. We haven't seen another need for maintaining multiple Debian OS variants.
