### ISSUE TITLE
PostgreSQL Database directory appears to contain a database; Skipping initialization

### ISSUE THREAD

**Issue by pra-richardg2-sportsbet** [docker-library/postgres#927]
I get this in the docker logs when doing docker up.

```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01-init.sh

PostgreSQL Database directory appears to contain a database; Skipping initialization
```

Looking at `docker-entrypoint.sh` it looks like it's because `PG_VERSION` exists in the postgres data dir.

https://github.com/docker-library/postgres/blob/master/13/alpine/docker-entrypoint.sh#L227

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue
