### ISSUE TITLE
Question: Is there a mechanism to notify the host of errors in the files executed by docker-entrypoint-initdb.d?

### ISSUE THREAD

**Issue by tokizuoh** [docker-library/postgres#928]
Hi there. Thank you always.

If the file in docker-entrypoint-initdb.d fails at runtime, the host is not currently notified of the error and you need to look at the logs.

For example, if it ends with an error as shown below, the host will not be notified of the error, which is inconvenient.
```bash
# docker-compose logs -f db     
db | 2022-02-04 14:16:27.802 UTC [63] ERROR:  extra data after last expected column
db | 2022-02-04 14:16:27.802 UTC [63] CONTEXT:  COPY unit, line 2: "1,hoge"
db | 2022-02-04 14:16:27.802 UTC [63] STATEMENT:  copy unit(id)
db exited with code 3
```

If there is a mechanism to notify the host side of a runtime error when a runtime error occurs in the docker-entrypoint-initdb.d file, please let me know.

---

I'm sorry if the above question off point.
Is it better to put the files under docker-entrypoint-initdb.d that are surely executed?

**Comment by tianon** [comment]
Unfortunately, we're not sure what you mean by "notify the host" -- inside a container, the only mechanisms we have for sending any kind of "message" to the host are the container logs/output and the container exit code. :confused: :see_no_evil:

**Comment by tokizuoh** [comment]
Thank you for your reply!

I think the files in docker-entrypoint-initdb.d will be executed after docker-compose up --build -d completes.
When the file in that docker-entrypoint-initdb.d causes a run-time error, the host side (that is, myself) has no choice but to check the log that the run-time error occurred.

I want this to be printed to standard error (= stderr) instead of logs.

> the only mechanisms we have for sending any kind of "message" to the host are the container logs/output and the container exit code. 😕 🙈

OK, understand. I'll try to devise it here. The issue is closed, thank you.
