### ISSUE TITLE
It's possible to unexpectedly allow passwordless login from IPv4 local connections

### ISSUE THREAD

**Issue by tryauuum** [docker-library/postgres#938]
I don't like using docker network isolation feature because it used to break my iptables rules. So I mostly run containers with `--network=host`.

If I run container like this, setting `POSTGRES_PASSWORD` to non-empty value:
```
docker run -d --rm --name postgres --network=host \
    -e POSTGRES_USER=rstudio-connect \
    -e POSTGRES_PASSWORD=my_super_secret_password_here \
    -e POSTGRES_DB=rstudio-connect \
    --privileged postgres:13.5
```
then it's possible to login to postgres without password from host OS:
```
[root@hostname ~]# psql -h localhost -U rstudio-connect rstudio-connect -c 'SELECT user'
      user
-----------------
 rstudio-connect
(1 row)

[root@hostname ~]#
```

This feels wrong to me, setting  `POSTGRES_PASSWORD` shouldn't allow passwordless login.

While the impact is minimal (passwordless login is from localhost only) it still is an issue. There are many setups where users have unprivileged SSH access to machines, e.g. shared hosting or HPC environment.

**Comment by yosifkit** [comment]
Whether or not to use the password is controlled by `pg_hba.conf` (ends up in the data directory). The default for `local` (unix socket) and when connecting from `127.0.0.1/32` (and `::1/128`) is `trust`. You can control the file auth method, the initial postgres user's password encryption, and how other users' passwords are encrypted with a few different flags when setting up a new database: https://github.com/docker-library/postgres/pull/897#issuecomment-944669713.

---

Note, do not use `--privileged` on any normal container (like `postgres`); it doesn't need that level of access. The flag removes most of the protections of the containerization, so an attacker could likely escape from container to host.
