### ISSUE TITLE
Readme trails off when explaining where to store data

### ISSUE THREAD

**Issue by SpangleLabs** [docker-library/postgres#948]
The readme on dockerhub seems to cut off halfway through a sentence in the "Where to store data" section.

> Create a data directory on the host system (outside the container) and

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/2192223/162186565-b973c63c-3b04-4ad4-ab13-eb15770c9e07.png">

I'm on the edge of my seat! And what?
Jokes aside, this is the exact part of the documentation I was looking for, so it's a bit frustrating for it to cut out like this. I can't find the rest of the text in this repo either. Any idea where it might be?

**Comment by wglambert** [comment]
Yeah Dockerhub has a 25k character limit (it used to be 5k) https://github.com/docker/hub-feedback/issues/238#issuecomment-398812981 and Postgres is one of the images where there's a lot to mention. The full image docs are shown here https://github.com/docker-library/docs/tree/master/postgres#where-to-store-data

There is a note at the beginning about it 
![image](https://user-images.githubusercontent.com/26428991/162249235-dffda19a-c741-4fbe-8421-ad491631d01c.png)

**Comment by tianon** [comment]
Thanks for the poke - I've opened https://github.com/docker-library/docs/pull/2129 with a first pass now :smile:
