### ISSUE TITLE
Request: Option to always rerun init scripts

### ISSUE THREAD

**Issue by nmguse-bighealth** [docker-library/postgres#955]
Requesting an option/ENV var flag that could be used to have the startup script always run `docker_process_init_files /docker-entrypoint-initdb.d/*`.

We've written our init scripts to be idempotent. We also sometimes we need to add things to them. To make this work across a team of engineers we wrote a script that we inject into the container that reruns the init scripts, and then have to have everyone run an arbitrary docker run command on their machine any time the init scripts change, so they get the necessary changes.

Getting many people across many teams to run a one-off command to resync their setup is quite a bit of cat herding, so it'd be great if we could just set this up to auto-re-init.

Maybe something like:
https://github.com/docker-library/postgres/blob/e483778176ca34bcbe83ee17000820d4f6e64c28/10/alpine/docker-entrypoint.sh#L334
```
elif [ -n "$RERUN_INIT_SCRIPTS" ]; then
    docker_process_init_files /docker-entrypoint-initdb.d/*
```

**Comment by tianon** [comment]
See also https://github.com/docker-library/postgres/issues/173, https://github.com/docker-library/postgres/issues/821, https://github.com/docker-library/postgres/issues/191, https://github.com/docker-library/postgres/issues/929 (one of which I think this is really a duplicate).
