### ISSUE TITLE
Add docker images for beta releases

### ISSUE THREAD

**Issue by lesovsky** [docker-library/postgres#960]
Add docker images for beta releases, for example with PostgreSQL 15 beta 1 which was released on 19 May.

Main usecase is providing early access to newer versions dockerized Postgres for developers who maintain various tools for Postgres and could add support of new Postgres version into their tools. For example i am author of tools such as pgcenter, noisia, pgstats.dev and I'd like to add compatibility or new features accordingly to Postgres 15 and would not like to wait main release in autumn.

Also i could try to make a PR, if you describe how to add support of new (beta) version.

**Comment by tianon** [comment]
Oops, we usually do; thanks for the reminder!  PR up at #961 :+1:

**Comment by lesovsky** [comment]
just to clarify, when new images will appear on docker hub?

**Comment by tianon** [comment]
See https://github.com/docker-library/postgres#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet and https://github.com/docker-library/official-images/pull/12494 :+1:
