### ISSUE TITLE
Add OCI Label Annotations to Images

### ISSUE THREAD

**Issue by busches** [docker-library/postgres#963]
It would be nice if we could add some of the OCI Label Annotations, https://github.com/opencontainers/image-spec/blob/main/annotations.md, to the Docker Images. Labels like `org.opencontainers.image.source` are used by tools like [Renovate](https://github.com/renovatebot/renovate/pull/15726/files) to pull change logs, etc.

If this is something we want to move forward with, I'd be happy to tackle an initial PR.

**Comment by tianon** [comment]
I wish we had a way to set actual OCI annotations -- labels are part of the image layers / history, so they have a negative effect on cache (whereas proper OCI annotations do not :disappointed:).

**Comment by tianon** [comment]
Closing for now as we don't have a way to set _annotations_ -- if that ever changes, we'd be willing to reconsider. :bow:
