### ISSUE TITLE
Postgres Docker `13.7-alpine` no longer includes language collations

### ISSUE THREAD

**Issue by christopher-nash** [docker-library/postgres#965]
The `13.X-alpine` docker images used to contain the various [language collations](https://www.postgresql.org/docs/13/collation.html). However, in `13.7-alpine` it appears they are no longer bundled in the image. I do not see any mention of their removal in the Postgres 13.7 [Release Notes](https://www.postgresql.org/docs/release/13.7/). This only appears to affect the docker image.

Using this query to count the entries in the collation table:
```sql
SELECT count(*) from pg_collation;
```
When I query against a container started using this version I get the following results:
| Version      | Count Result |
| ----------- | ----------- |
| docker pull postgres:13.6-alpine      | 790       |
| docker pull postgres:13.7-alpine   | 9        |
| docker pull postgres:13.7   | 790        |
| docker pull postgres:13.7-bullseye   | 790        |

(Note that this does _not_ affect the `13.7` or `1.37-bullseye` (non-alpine) docker images - only the `-alpine` version is affected.)

It is unclear to me what caused this regression. I also am unable to identify how to correct this issue locally - it is causing automated builds for one of our systems to fail which use the alpine version to test against.

**Comment by wglambert** [comment]
Alpine 3.16 split the `ICU` package
https://github.com/docker-library/php/issues/1302

**Comment by tianon** [comment]
Ah, in this case I think it probably _does_ make sense to include the full ICU data, since we don't maintain `alpine3.15` images anymore. :grimacing:

**Comment by christopher-nash** [comment]
@wglambert / @tianon / @yosifkit - What is the basic process that these now go through after that PR is merged to show up in Dockerhub? When do you think I'll be able to check back and see the new versions available there?

**Comment by wglambert** [comment]
https://github.com/docker-library/postgres#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/12576 :eyes:
