### ISSUE TITLE
unable to modify postgresql.conf from docker-entrypoint-initdb.d/ scripts. 

### ISSUE THREAD

**Issue by danwyry** [docker-library/postgres#97]
I'm new to docker and it's practices so I'm not really sure if this is really an issue or not, but I'm tryint to set some configuration settings in postgresql.conf. 

I set up a Dockerfile to extend FROM postgres:9.4 image and within it I copy my script into docker-entrypoint-initdb.d/ directory. 

I ran some tests and I know the script runs but I get a "*can't find /var/lib/postgresql/data/postgresql.conf: not such file of directory*" when the script runs.

**Comment by yosifkit** [comment]
I am unable to reproduce.  I made a `test.sh` file:
```bash
#!/bin/bash
set -x
ls -al /var/lib/postgresql/data/postgresql.conf
```

And then ran it:
```console
$ docker run -it --rm -v "$PWD"/test.sh:/docker-entrypoint-initdb.d/test.sh:ro postgres
...
/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/test.sh
++ ls -al /var/lib/postgresql/data/postgresql.conf
-rw------- 1 postgres postgres 21297 Oct  9 20:15 /var/lib/postgresql/data/postgresql.conf
...
```

What are you running in your script?

**Comment by danwyry** [comment]
I'sorry

**Comment by danwyry** [comment]
I'm sorry I'm closing this issue, I found a misktake on my side. Athough I'm experiencing another problem, which I'm not sure how to solve. is it appropiate to ask in the github issues ? or is there a dedicated forum or something like that for these stuff ?

**Comment by yosifkit** [comment]
Glad you spotted the problem :tada:.  If it is a general dockerizing issue, the the #docker IRC channel on freenode is the best place.  There is also #docker-library for issues relating to building and maintaining the Official Images.
