### ISSUE TITLE
Out-of-band PostgreSQL 14.4 released

### ISSUE THREAD

**Issue by shleeable** [docker-library/postgres#972]
https://www.postgresql.org/about/news/postgresql-144-released-2470/

**Comment by shleeable** [comment]
Commit is in, but the image isn't tagged in the official repo yet.

**Comment by 1player** [comment]
Pinging @tianon and @yosifkit that seem to be the maintainers for this image.

**Comment by wglambert** [comment]
PR pushing the update to Dockerhub will be up shortly https://github.com/docker-library/postgres#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

**Comment by tianon** [comment]
Indeed, https://github.com/docker-library/official-images/pull/12668 :+1:

**Comment by galdor** [comment]
Thank you!
