### ISSUE TITLE
OSX host; psql connection refused

### ISSUE THREAD

**Issue by genei09** [docker-library/postgres#98]
I'm starting the basic 9.4 image as follows:
docker run -p 5432:5432 --name db_test -e POSTGRES_USER=ui_user -d postgres:9.4

and trying to connect with:
psql -U ui-user -h localhost

and get the message:
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

I have another container which is started with:
docker run -it -p 6543:6543 --name ui_test -d ui_app:latest bash

I am able to connect from another container "ui_test"
psql -U ui-user -h db_test

when I start the webserver on "ui_test" it is accessible from the host browser with:
http://localhost:6543

what am I missing?

**Comment by tianon** [comment]
Are you trying to connect using `psql` from your host, or from another container?

If you're trying to connect from your OSX host, you'll need to use `-h $(docker-machine ip machine-name)` instead of `-h localhost` for this to work.

**Comment by md5** [comment]
It's very surprising that you're able to hit http://localhost:6543 successfully on OS X. You should have to use the Docker Machine IP as @tianon suggested for your `psql` command.

**Comment by tianon** [comment]
True -- maybe some port forwarding settings in the VirtualBox configuration?

**Comment by genei09** [comment]
I installed the latest official release from docker which has the port forwarding built in.

**Comment by genei09** [comment]
I looked up the webserver container's IP using:
docker inspect wcui_test | grep IPAddress
when I tried to use it in the host browser it times out.  as does the psql command

**Comment by tianon** [comment]
Right, the IP address you get from `docker inspect` will be internal to the Docker virtual machine, not your OS X host.  You'll need to use `docker-machine ip machinename` to figure out the IP address of the VM, and hit that instead.

**Comment by genei09** [comment]
for reference: the vm created by the installer is 'default'
got the ip address
browser works
psql doesn't: same error

**Comment by genei09** [comment]
For some reason I had to explicitly add the port forward to boot2docker.  Works as expected connecting with localhost now.
