### ISSUE TITLE
POSTGRES_HOST_AUTH_METHOD not working as documented on 14.4

### ISSUE THREAD

**Issue by cap10morgan** [docker-library/postgres#981]
[The documentation on POSTGRES_HOST_AUTH_METHOD](https://github.com/docker-library/docs/blob/master/postgres/README.md#postgres_host_auth_method) says that specifying a value for the POSTGRES_HOST_AUTH_METHOD env var will add a `host all all all $POSTGRES_HOST_AUTH_METHOD` line to the `pg_hba.conf` file in the container. It also says, "If unspecified then scram-sha-256 password authentication is used (in 14+; md5 in older releases)."

Neither of these things happen in a newly-created 14.4 container. If I don't specify it, I don't get the expected `host all all all scram-sha-256` line in the `/var/lib/postgresql/data/pg_hba.conf` file in the container, ~~nor do I if I specify `-e POSTGRES_HOST_AUTH_METHOD=scram-sha-256` in my `docker run ...` command.~~ And I can't connect from another host (with the error that the host doesn't have an entry in `pg_hba.conf`).

UPDATE: Actually specifying it does work if its a newly-created `pg_hba.conf`. I had it in a volume so it wasn't modifying an existing file, which seems reasonable.

Am I misunderstanding something here?

**Comment by yosifkit** [comment]
> UPDATE: Actually specifying it does work if its a newly-created `pg_hba.conf`. I had it in a volume so it wasn't modifying an existing file, which seems reasonable.

Correct, it only appends to `pg_hba.conf` when it is a newly initialized database.

https://github.com/docker-library/postgres/blob/623c00456eab020e203704232c9bd7703ed7ff34/docker-entrypoint.sh#L310-L318

**Comment by soheilrahsaz** [comment]
There's also an important note in the documentation (which I missed I was confused for a bit):

> Note 3: If you set this to an alternative value (such as scram-sha-256), you might need additional POSTGRES_INITDB_ARGS for the database to initialize correctly (such as POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256).
