### ISSUE TITLE
Port forwarding to allow host to access guest with a pg client

### ISSUE THREAD

**Issue by ReinsBrain** [docker-library/postgres#99]
When developing i find it ideal to be able to inspect the database with a graphical client instead of running a docker to run a psql command. But the forwarding clashes :

Cannot start container dd3ff...5a06: Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use.

Note, I'm using vagrant to run multiple containers. Any suggestions?

**Comment by yosifkit** [comment]
it should work the same whether in a vagrant VM or not, just a docker run with `-p whatever-port-on-the-host-I-want:5432` and then connect to IP of said VM at the port you specified.  You'll need to make sure that the chosen port is open on said VM before starting the postgres container with the `-p`.  You might even need to clean up stopped containers in case one of them is causing docker to hold on to the port.

**Comment by ReinsBrain** [comment]
Thanks yosifkit, your response helped me overcome something un-intuitive to me - when I used docker ps to list my containers, the port (forward) is listed as:

 0.0.0.0:15432->5432/tcp

The way the arrow points here confused me (seems backwards to me) so I had the ports reversed. The conflict was happening with my local running postgres. Your prompt response helped me out of that rut. Thanks again.
