### ISSUE TITLE
Enhancement for replication

### ISSUE THREAD

**Issue by s-amundson** [docker-library/postgres#993]
Please add an enhancement for setting up replication. 

I added the a the following lines to a copy of the entry point script to docker-entrypoint.sh for bullseye and got a replication slave working with the addition of the PG_REPLICATE environmental variable. I am sure that this could be improved on. I used a custom postgres.conf and pg_hba.conf files although there may have been other ways to accomplish the same task.

`		if [ -z "$DATABASE_ALREADY_EXISTS" ]; then
      if [ $PG_REPLICATE == 1 ]; then
        pg_basebackup --pgdata $PGDATA --format=p --write-recovery-conf --checkpoint=fast --label=mffb --progress --host=$PGHOST --port=$PGPORT --username=$PGUSER
      fi
    fi
`
Thank you for what you have done. Hope this helps.

**Comment by tianon** [comment]
Unfortunately, this is something that's going to end up being fiddly enough (and opinionated enough) that we're not comfortable maintaining an implementation of it.  I would suggest that you could probably get pretty far by using a script in `/docker-entrypoint-initdb.d` though.
