### ISSUE TITLE
Version 11.17 is missing on docker hub

### ISSUE THREAD

**Issue by gigo64** [docker-library/postgres#996]
Release News
https://www.postgresql.org/about/news/postgresql-145-138-1212-1117-1022-and-15-beta-3-released-2496/

Version 11.17 is missing as a published tag, could it please be published?
https://hub.docker.com/_/postgres?tab=tags

**Comment by yosifkit** [comment]
Versions `10` and `11` do not have any plain tags; See https://github.com/docker-library/postgres/issues/582

**Comment by gigo64** [comment]
Ok, got it, thanks!

**Comment by schinery** [comment]
@gigo64 I see this has been closed but I'm not seeing a 11.17 image on the Docker hub, is one on the way?
